### ISSUE TITLE
Allow A-Frame to enter fullscreen mono mode if headset not detected

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1060]
Currently can't enter fullscreen because that's reserved for VR.

We should allow fullscreen (and swap out the Goggles icon for a fullscreen icon) for mono experiences if a headset is not detected.

If a headset is detected, then fullscreen will also enter VR mode.

**Comment by ngokevin** [comment]
This is related to https://github.com/aframevr/aframe/pull/1056 because there is less reason to have pointer lock until we support fullscreen + mono. 

vr + pointerlock doesn't seem to go well together (unless we maybe restrict the pointerlock to a single axis)

**Comment by cvan** [comment]
I like this. And I also like the idea of making the "enter VR" button a friendlier color (like green) when a headset is plugged in.

**Comment by ngokevin** [comment]
Maybe Goggles when headset plugged in or mobile...else fullscreen arrows?

**Comment by ngokevin** [comment]
The minimum work required for this when a VR headset is not detected, then clicking on the Goggles button triggers a simple requestFullScreen.

Then we can subsequently layer on proper UI for it.

**Comment by cvan** [comment]
perhaps, this is one way. but we shouldn't conflate "entering VR" with "entering fullscreen" (or even being a sufficient fallback). some folks may actually be using A-Frame and just want to enter fullscreen w/o VR. or may want to enter VR but on a VR-capable device (e.g., my phone). also, what would the icon look like? a VR googles/fullscreen icon - would it be conditional?

load https://mozvr.com/demos/SECVRITY/ in Chrome and Firefox Nightly to see how we handled this for the Unity WebVR template. since game devs often want to enter fullscreen, we just gracefully add VR icons if they have VR support (even if no devices are connected yet).

<img src="https://cloud.githubusercontent.com/assets/203725/15520475/80f8ed9c-21bb-11e6-8ff0-b239faefe0f9.png">

**Comment by ngokevin** [comment]
Just breaking up the chunks of work.

Right now, simply just allow fullscreen.

Then work on conditional icons:

- Desktop, headset connected: googles -> VR mode
- Desktop, no headset: fullscreen icon -> fullscreen
- Mobile: always goggles

**Comment by FrederickDesimpel** [comment]
Why not use the same conventions like Borismus webvr-boilerplate ? Like the icons more too.

I'd like mobile non-vr fullscreen as well

**Comment by ngokevin** [comment]
Fixed by https://github.com/aframevr/aframe/commits/master?page=2

**Comment by calumjamesgreen** [comment]
@ngokevin - was there ever an option made for fullscreen on mobile without forcing headset?

**Comment by riebling** [comment]
Oh man, it would be awesome to figure a way to do fullscreen split stereo to support devices that can 'do the right thing' with it. I ended up here googling for a way to do this, and hope to find one, then can remove this tangential comment :)
