### ISSUE TITLE
transparent=true not working for a-sky?

### ISSUE THREAD

**Issue by alexcheninfo** [aframevr/aframe#1104]
Example:

```
<a-sky class="pano" opacity="1" position="-9999" transparent="true" id="pano-1" src="/pano-0.jpg?1a2f7bc" material="color:#FFF;shader:flat;src:url(/pano-0.jpg?1a2f7bc);opacity:1;transparent:true" geometry="primitive:sphere;radius:5000;segmentsWidth:64;segmentsHeight:64" scale="-1 1 1">
</a-sky>
<a-sky class="pano active" opacity="0" position="0" transparent="true" id="pano-2" src="/pano-00.jpg?fdf7a6f" material="color:#FFF;shader:flat;src:url(/pano-00.jpg?fdf7a6f);opacity:0;transparent:true" geometry="primitive:sphere;radius:5000;segmentsWidth:64;segmentsHeight:64" scale="-1 1 1">
</a-sky>
```

In the code above `#pano-1` won't show. Instead, you'll see only white (`#pano-2`'s white shader?).

Is this a bug or `a-sky` can't be transparent?

**Comment by K4orta** [comment]
I ran into the same issue recently. While I'm not sure if it is supposed to be possible to set opacity on a-sky elements, creating a plain a-entity that worked like an a-sky ended up working for me:

```html
<a-entity id="sky" geometry="primitive: sphere;radius: 5000" material="side: back; src: url(./pano.jpg); repeat:-1 1" ></a-entity>
```

You should then be able to change the opacity by doing something like:

```javascript
document.querySelector("#sky").setAttribute("material", "opacity", 0.5);
```

**Comment by ngokevin** [comment]
Currently can't pass position as a single number. Has to be X Y Z

We have issue on file https://github.com/aframevr/aframe/issues/451

**Comment by ngokevin** [comment]
Actually the issue on file is just for scale. Position should be three numbers always

**Comment by Vamoss** [comment]
@ngokevin , I don't see how your point is pertinent to the transparency issue. I am still experiencing this. Can you reopen this card?

I tried the @K4orta solution, didn't work.

I also built my own shader, and as soon as the opacity is less than 1, the object disappears from the scene. The only way to fix this is setting the material="depth:false", but this generates other problems for me.


It is not related to the shader or the geometry, it is something related to the render :(

**Comment by donmccurdy** [comment]
Here's a demo: https://codepen.io/donmccurdy/pen/qxEpzy. Note that you can see only one `<a-sky/>` initially, but if you swap the order of the DOM elements you will be able to see both photospheres.

This problem occurs, in one form or another, in all realtime WebGL renderers. Because of certain limitations in the WebGL API, three.js renders opaque objects followed by transparent objects, sorting the objects in each group from front-to-back. Because these are spheres surrounding the camera, three.js can't effectively sort them, and so depending on the default order in the DOM you get different results.

You can work around the problem sometimes, reordering objects or by setting `el.object3D.renderOrder`, but neither three.js nor A-Frame can automatically guess how to resolve this problem in all cases. For more information see https://github.com/mrdoob/three.js/issues/4724.

Note that if you don't need partially-transparent materials, but just want to see through the 100% transparent parts of a PNG or GIF, you can set `material="alphaTest:0.5"` _without_ setting `transparency`, and avoid many of these issues. This can be helpful for things like leaves, fences, and shrubbery.

**Comment by Vamoss** [comment]
Thanks for clarifying @donmccurdy. 

For my case, where I have several a-sky switching opacity when a user interacts, some of them with transparent PNGs and others with transparent 3D objects, I think I will leave the issue behind, I spent 2 days trying to fix this :( There seems to be no perfect solution.
