### ISSUE TITLE
Allow components to be registered at runtime

### ISSUE THREAD

**Issue by RangerMauve** [aframevr/aframe#1152]
It would be useful if entities that are defined as using components which don't exist yet would get those components automatically added to them once they've been registered.

For example:

``` html
<a-entity somecomponent="foo: true"></a-entity>
```

`somecomponent` hasn't been reigstered yet, so it's not active, but is tracked somehow by the system.

``` javascript
AFRAME.registerComponent("somecomponent", {
  init: function(){
    // Wow!
  }
});
```

As soon as the component gets registered, it'll be attached to the entity that previously registered it.

The main use would be components loaded asynchronously (say, from a registry) or maybe components that are being generated dynamically via some dark voodoo magic.

**Comment by ngokevin** [comment]
One option:

1. When unknown component is attached to an entity, store the component in an object.

```js
var queuedComponents = {
  'some-unknown-component': [el1, el2, el3]
}
```

2. When a component is registered, and there is a queue for it, init the component on each entity.

```js
queuedComponents[registeredComponent].forEach(initComponent);
```

**Comment by wizgrav** [comment]
sounds good but what about dependencies, how would they get honored?

**Comment by wizgrav** [comment]
Also topological sorting could be applied to the dependencies graph to calculate the registration order

**Comment by ngokevin** [comment]
Good point. Will have to think about that. I hope there's a pub-sub way to do it without introducing asynchronous code into the core API because that will become infectious and spread through the entire codebase.

**Comment by wizgrav** [comment]
If registration is expressed with promises, as new component definitions come in asynchronously, the dependencies defined in them can produce more promises and then it's all a matter of chaining them

**Comment by RangerMauve** [comment]
Maybe depending on a component could be sync if it already exists, and have a deferred promise if it doesn't exist yet, which can resolve after something registers that component?

**Comment by xirvr** [comment]
A-few initial questions (not sure if I will have the time to contribute, but am going to try): 
- What would be the most minimal example of this?
- Will this be handled differently based on type of component?  For example:
- - <a-hyperbolic-star></a-hyperbolic-star>
- - <a-box turn-into-a-hyperbolic-star="resolution:20;"><a-box>
- - <a-hyperbolic-grouping-thing><a-box></a-box></a-hyperbolic-grouping-thing>
- - (etc?)
- Where would this functionality live in the existing code?  Are there any requirements/suggestions around how it should be hooked into the existing system?

**Comment by ngokevin** [comment]
- Entity attaches component that is not yet registered. That component is later registered. The entity initializes the component.
- `<a-hyperbolic-star>` and `<a-hyperbolic-grouping-thing>` are not components. If you mean primitives, those are just entities that attach components.
- Most logic will be in `src/core/entity.js`. Perhaps some in `src/core/component.js`

Implementation details and dependencies not sure about yet. This issue is marked as `easy` but that's more of a `help-wanted` label.

**Comment by wizgrav** [comment]
I think combining your suggestion about keeping lists of entities that need component initialization along with promises that resolve to component definitions could do the trick here. When an entity requests an unknown component it creates an entry in a map, allocates a new list and puts the element in. At the same time a promise is created that when resolved with the definition it would iterate the list and initialize the components on each entity contained therein. Some checking would be required because the entity may have removed the component in the meantime. If a component definition contains dependencies then these would create more promises which can be chained with Promise.all()

**Comment by ngokevin** [comment]
We are currently exploring the trade-offs and ramifications of allowing this.

**Comment by ngokevin** [comment]
I think we are not going to do this. It quickly gets messy. What happens when a component that is not yet registered is initialized via a `setAttribute`? Waiting for it to register will cause a big delay.

**Comment by donmccurdy** [comment]
Is this still considered "help wanted"? 

This issue seems to come up a lot, e.g. it's not possible to use the JS panel in Codepen because it is appended at the end of `<body/>`. And, for that matter, putting JS at the end of the body tag is pretty common practice.

Couple ideas:

1. At the bare minimum, component registration should throw an error if run after a scene has been parsed. Silently ignoring the newly registered components is not what the developer expects, and this is a common source of confusion. I'd even prefer a full error to a console warning, actually.
2. Agreed that resolving dependencies is difficult. My suggestion would be, if the scene gets to the point of initializing components and any components have dependencies that haven't been registered yet, don't wait or delay — throw an error. Then, we've simplified things and all that's left is a way to initialize on attributes that are already in the DOM.

**Comment by ngokevin** [comment]
We won't go for this due to the potential complications. 

We do have warnings now for when components are registered after a scene.
