### ISSUE TITLE
Rename primitive to prefab or assemblage

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#1207]
Primitives name collide with geometric primitives and it doesn't really convey what they really are.

**Comment by ngokevin** [comment]
Some thoughts. We want to describe a custom element that:

- Has a name
- Prescribes default components
- Prescribes component property values
- Proxies attributes to component properties
- Provides transforms in the process of the mapping to support `<a-box src="texture.png">` rather than `<a-box src="url(texture.png)">`

So this does more than what "aliases" conveys which is a simple rename. The next best term I can think of is "helper elements" or "convenience elements" since that is their true purpose.

**Comment by ngokevin** [comment]
And some aside thoughts on the collision:

- It is a name collision, but in separate contexts so it is not the worst thing. 
- Might want to consider renaming `geometry.primitive` to `geometry.type`. If we introduce and normalize a registerGeometry API, then it opens up use cases that will not always be true geometric primitives (e.g., `geometry="primitive: text"` or `geometry="primitive: teapot"`).

**Comment by dmarcos** [comment]
The collision is not what worries me the most. Primitive does not convey what they really are.
Primitive in a geometric context is used but a lot of creation tools in 2D and 3D.

**Comment by ngokevin** [comment]
Yeah, that's why my thoughts on the collision were just an aside. My first comment has more thoughts that do not disagree with the meaning of primitives.

**Comment by ngokevin** [comment]
The perfect term for this is `assemblage` - `factory to make objects with preset combination of Components`

http://gamedev.stackexchange.com/questions/58693/grouping-entities-of-the-same-component-set-into-linear-memory
http://vasir.net/blog/game-development/how-to-build-entity-component-system-in-javascript

**Comment by dmarcos** [comment]
In Unity world they are called prefabs but the concept has a larger scope. You can also encapsulate multiple entities in a prefab.

**Comment by ngokevin** [comment]
Final showdown:

- Assemblage: vivid in describing a bundle or grouping of components, have seen this term in some ECS theory articles
- Prefab: precedent and maps well with Unity

**Comment by dmarcos** [comment]
Not sure if this conversation is still relevant. I'm happy to keep the `primitive` name and move on. @ngokevin ?
