### ISSUE TITLE
window.hasNonPolyfillWebVRSupport returns true on regular FireFox

### ISSUE THREAD

**Issue by mayognaise** [aframevr/aframe#1244]
`window.hasNonPolyfillWebVRSupport` returns `true` on regular FireFox.

- A-Frame Version: all version
- Platform/Device: Mac OSX/Firefox
- userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:39.0) Gecko/20100101 Firefox/39.0"

**Comment by cvan** [comment]
39.0 is a very old version of Firefox (from July 2015). we're on 44.0.

and `window.hasNonPolyfillWebVRSupport` returns `false` for me:

<img width="1121" alt="screenshot 2016-03-24 18 55 12" src="https://cloud.githubusercontent.com/assets/203725/14035995/c7d41c9a-f1f1-11e5-8cfa-ed3b070a2392.png">

keep in mind that if you have the WebVR add-on installed (check in `Tools > Add-ons`), it'll be `true`. because actually WebVR support has made it to release channel; it's just stuck behind a flag. and we've made a ton of perf changes since release.

**Comment by ngokevin** [comment]
I think that addresses it ^

**Comment by mayognaise** [comment]
@cvan thanks for the checking. Actually version 45 got the same result too. But as you said, it becomes `true` because of the add-on. It super makes sense :100: :tada:
