### ISSUE TITLE
In video sphere there is no button to change back from VR mode to normal mode

### ISSUE THREAD

**Issue by MrBokeh** [aframevr/aframe#1296]
**Description:**
In video sphere there is no button to change back from VR mode to normal mode. You can only change from normal 360 videos to VR but not the other way around.
- A-Frame Version: v0.20
- Platform/Device: iOS and Android

**Comment by cvan** [comment]
You press the physical back button on your Android. I have a branch that updates to use the latest webvr-polyfill which now features a graphical back button on mobile in the top-left corner (used to be part of the webvr-boilerplate). There have been a few iOS bugs in the latest webvr-polyfill version so we've been holding off on updating: borismus/webvr-polyfill#46 and borismus/webvr-polyfill#57 Will be updating soon though, so stay tuned.

**Comment by MrBokeh** [comment]
How can I add another back button to go back to other screen then if the back button is for switching between normal and vr mode?

**Comment by cvan** [comment]
> How can I add another back button to go back to other screen then if the back button is for switching between normal and vr mode?

what do you mean "other screen"? on Android devices, pressing the physical back button will exit Fullscreen; pressing the physical back button twice will take you back in history in the browser. on iOS, since there there is no Fullscreen API, when you rotate from landscape to portrait we let you exit VR mode.

clicking on webvr-polyfill's back button icon exits Fullscreen on Android but doesn't do anything on iOS. it should exit pseudo-fullscreen/VR mode on iOS. I'll have to open a PR for it to do that.

**Comment by ngokevin** [comment]
wontfix, just use browser/physical back button or navigate somewhere else
