### ISSUE TITLE
Setting fog: false to a-sky is ignored

### ISSUE THREAD

**Issue by bnolan** [aframevr/aframe#1324]
**Description:**

`<a-scene fog="color: #fff"><a-sky material="fog: false" rotation='0 -45 0' src='https://www.scenevr.com/prerelease/images/sky.png'></a-sky></a-scene>`

The sky isn't rendered, you just see the fog color instead.

- A-Frame Version: 2.0.0
- Platform/Device: Chrome

**Comment by cvan** [comment]
I did some investigation, and it appears that the primitive attributes (e.g., `src`) aren't taking into account previous component attribute values (e.g., `material`).

Obviously because the primitive attributes break entity-component pattern, it can get confusing combining attributes like `material` and `src` - because you have to merge the existing properties of `material` with the properties that will change from modifying `src`. I didn't check, but I'd assume the same issues occur with mixins with component attributes.

**Comment by ngokevin** [comment]
Mixins are fine.
