### ISSUE TITLE
Test and ensure A-Frame scenes work with Samsung's Gear VR browser

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1346]

**Comment by luke-john** [comment]
https://github.com/aframevr/aframe/blob/57fc8cbfcd845b2aed547092b321c1f98145193f/src/utils/index.js#L116

To get it working I had this function return false.

Given more mobile devices may have webvr browsers in the future, this function may need renaming.

**Comment by loving1** [comment]
Yes, we have an A/VR headset that has mobile on it already and are not able to use the head tracking. It's not cell phone based which also causes a problem. Any advice on being able to have the browser recognize our device as unique would be helpful and to also connect to the head tracker.

**Comment by cvan** [comment]
Fixed by #1366. Thanks, @dbradleyfl!

**Comment by Marchhill** [comment]
This appears to still be an issue with the samsung internet vr browser (it works fine with the oculus browser), it is set to mobile mode when it shouldn't be

**Comment by dbradleyfl** [comment]
Looks like the isGearVR function isn't being used inside isMobile check anymore [here](https://github.com/aframevr/aframe/blob/739427d84099dd0d92b83dcdf878f032cc7fe81b/src/utils/device.js#L38). The [Gear VR User Agent String](http://developer.samsung.com/technical-doc/view.do?v=T000000203) should still match that regex so that doesn't seem to be the issue. I don't have time to test it right now, but I'd add an if statement under line 47 that sets _isMobile to false if isGearVR is true @Marchhill
