### ISSUE TITLE
stereo rendering not working on iphone 6 on newer builds of a-frame

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1362]
**Description:** Open scene on iPhone 6 with Safari, click on the Goggles. The scene renders, but it won't split into stereo mode.

- A-Frame Version: master
- Platform/Device: iphone 6 safari

**Comment by K4orta** [comment]
I looked into this some. It seems that Three.js r75 changed VREffect.js's render function to check that full screen mode is enabled before it will render in stereo mode. As a result Android is fine, because it supports the Full Screen API, but Safari can only render in mono because [it does not.](http://caniuse.com/#search=fullscreen)

A change will need to made made to VREffect.js in order to fix this.

**Comment by ngokevin** [comment]
cvan is on this . https://github.com/aframevr/aframe/pull/1132 will help

**Comment by K4orta** [comment]
Great! Good to know he's got a fix for it.

**Comment by ngokevin** [comment]
Should be fixed by now
