### ISSUE TITLE
Android tv should not be reported as mobile.

### ISSUE THREAD

**Issue by bnolan** [aframevr/aframe#1395]
**Description:**

I use a shield tv to view a-frame sites and it works well, except the viewport is pointed down at the ground, I assume because the orientation API returns a vector pointing straight down. It'd be good to categorize android tv devices as not mobile. Possibly this is a webvr-polyfill bug?

- A-Frame Version: 2.0.0
- Platform/Device: [Shield Android TV](http://www.webapps-online.com/online-tools/user-agent-strings/dv/brand728783/nvidia-shield-android-tv)

**Comment by bnolan** [comment]
Also, I think iPads and Android Tablets shouldn't be reported as mobile. Either that, or have the option to change away from VR display? Maybe click and hold the cardboard icon to show a little menu that flicks to thumbpad navigation on a scene?

**Comment by ngokevin** [comment]
I think for now, iPad/Android Tablet should be detected as mobile so that they still work without having to create custom touch controls. If they were not detected as mobile, then all of the Cardboard scenes that were built with accelerometer in mind would not work correctly.

You can open a PR for fixing TV detection; we're focusing more on VR rather than flat.

**Comment by bnolan** [comment]
Makes sense. I'll create the PR. Is #975 the best place to discuss control refactoring (adding thumbpads)?

**Comment by ngokevin** [comment]
For thumbpads or touch thumbpads, you'd be free to register your own controls. Each application has such specific controls requirements so we're leaving it up more to the dev.
