### ISSUE TITLE
Enable Dvorak Controls?

### ISSUE THREAD

**Issue by prichey** [aframevr/aframe#1409]
I'm a Dvorak user who is annoyed by having to switch modes every time I want to test out something with the WASD controls. I'm wondering if there has been any thought put into alternative keyboard layouts? I was thinking about making a PR for a new `dvorak-controls` component, but ultimately it'd just get used in development since the vast majority of production users will use QWERTY. I also had the idea of changing the `wasd-controls` component to something more general (`keyboard-controls`?), which could potentially allow the user to swap between WASD and Dvorak modes, maybe with some (optional) small text in the lower left that would appear on hover?

I'm willing to work towards a PR for this, I just wanted to open the issue to see if anybody else had any ideas, or if anyone has pursued this line of thinking as of yet.

**Comment by donmccurdy** [comment]
Hi! Dvorak user here as well. :) I think this will be fixed in #1248. It's a larger PR but the relevant part is that using the newer KeyboardEvent.code API lets us map hotkeys by *locations*, without considering keyboard layout. This works better for ZQSD layouts as well. 

(only applies in browsers that support KeybardEvent.code, though - otherwise there's no good way to support both modes simultaneously)

**Comment by prichey** [comment]
Excellent! Thanks @donmccurdy!

**Comment by ngokevin** [comment]
dupe #333
