### ISSUE TITLE
support collada animations

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1446]
**Description:**

Like http://codepen.io/anon/pen/XdGpEy?editors=1010

**Comment by ngokevin** [comment]
> https://files.slack.com/files-pri/T0FAGUM6W-F1846MQ5U/animations-from-dae

> Hey @ngokevin we got that dino animating yesterday — but it looks like AFrame is only set up for skinned animations (where the animation is a child of the geometry) — in (regular?) animations, they are in the Collada object which is discarded in Aframe’s loader implementation

**Comment by michael829** [comment]
Oh....I've some problems with this dae animation model....@ngokevin thank you for the sample... now the models works fine in my project! but is there any articles about AFrame's animations?? if I want use other format animation file, what can I do? like this: http://threejs.org/examples/#webgl_lights_hemisphere.

https://files.slack.com/files-pri/T0FAGUM6W-F1846MQ5U/animations-from-dae  <-- this link don't exist!

**Comment by ngokevin** [comment]
To contribute, check out how it's done in  http://codepen.io/anon/pen/XdGpEy?editors=1010

In the COLLADA component (src/components/collada-model.js), use `THREE.Animation` if the mesh is a `SkinnedMesh`. Once the animation is created, use component `tick` handler to step the animation.

**Comment by donmccurdy** [comment]
Discussing this a bit here: https://github.com/donmccurdy/aframe-extras/issues/82

@ngokevin any thoughts on what the play/pause API should look like, since models can include multiple animations?

**Comment by azmartone** [comment]
Seems like THREE.AnimationHandler, which is used in the codepen example, was deprecated as of r73 and I've only been able to find examples where the models were imported as json objects and not COLLADA objects.

https://github.com/mrdoob/three.js/issues/9426

**Comment by donmccurdy** [comment]
Making some progress on animation support in [three-model](https://github.com/donmccurdy/aframe-extras/blob/master/src/loaders/three-model.js). But since THREE.AnimationMixer (the replacement to THREE.AnimationHandler) isn't specific to a particular model format, it probably makes most sense to not bundle animation code into the `model-*` components themselves.

Strawman syntax:

```html
<a-entity collada-model="src: url(...);"
          model-animation="name: run;
                           duration: 0.5;
                           fps: 30;"></a-entity>
```

Animation name can be optional; perhaps the first animation available will just autoplay.

There are multiple kinds of animation: morph-based, skeletal, and keyframe-based (?). Options need to be set on the material to support morph and skeletal animations. [Perhaps that can be done automatically by loaders](https://github.com/donmccurdy/aframe-extras/blob/master/src/loaders/three-model.js#L46-L48), or retroactively applied to the material.

A `model-animation` component could be fairly detached from the model-loading code, so it might make sense to include it in core. It should be triggered by events, or programmatically.

Also, idle thought, would the current `animation` component be better named as `tween` to reflect that it's not the right choice for effects like changing `src` attributes?

**Comment by donmccurdy** [comment]
Wrote an [animation-mixer component](https://github.com/donmccurdy/aframe-extras/blob/feat-animation/src/loaders/animation-mixer.js) that works out of the box with [json-model](https://github.com/donmccurdy/aframe-extras/blob/feat-animation/src/loaders/json-model.js) and [gltf-model](https://github.com/xirvr/aframe-gltf). It should work for ObjectLoader aka `blend-character-model` too, but i'm working out some issues there.

I think it's possible worth having a dedicated component for animation, rather than baking it into model loaders, to support things like [blend tree animation](https://docs.unity3d.com/Manual/class-BlendTree.html) and to have a consistent API. This component depends on [THREE.AnimationMixer](https://github.com/mrdoob/three.js/blob/dev/src/animation/AnimationMixer.js) (the fancy new animation system in THREE.js).

But Collada models still require the [old animation system](https://github.com/mrdoob/three.js/blob/302c693b27663d4d280b156b5ebe4ed38cd062e4/examples/js/loaders/collada/Animation.js), which has been moved into a folder with just Collada-specific code. We could bundle both animation systems, but I'm more inclined to use the new system and encourage people to convert their Collada stuff to glTF with the online converter.

**Comment by donmccurdy** [comment]
The glTF-specific animation system has been removed in favor of the new/common animation system, THREE.AnimationMixer: https://github.com/mrdoob/three.js/pull/10276.

In terms of adding model animation support to A-Frame, I think it would make most sense to start with the THREE.js JSON format and glTF.

**Comment by msj121** [comment]
@donmccurdy Simply Amazing!

**Comment by donmccurdy** [comment]
@msj121 everything in THREE.js `dev` is now cross-compatible for that to work — hopefully all we need to do is update `gltf-model` to the latest version of THREE.GLTFLoader. 

But definitely a chance there will be version mismatch issues, and if so it may be necessary to wait for the next THREE.js + A-Frame releases.

**Comment by ngokevin** [comment]
Going to close in favor of supporting glTF animations. If COLLADA benefits from that then great. Otherwise, see the three.js code for playing COLLADA animations (use the `model-loaded` event to grab the collada scene):

1. Import animation code 

https://github.com/mrdoob/three.js/blob/dev/examples/webgl_loader_collada.html#L36


2. Traverse the model and play animations

https://github.com/mrdoob/three.js/blob/dev/examples/webgl_loader_collada.html#L57

3. Tick the animation

https://github.com/mrdoob/three.js/blob/dev/examples/webgl_loader_collada.html#L181

**Comment by donmccurdy** [comment]
For posterity, is an example implementation of animation with COLLADA:

https://github.com/donmccurdy/aframe-extras/issues/101#issuecomment-257197602
