### ISSUE TITLE
ASDF movement bug when using SHIFT key

### ISSUE THREAD

**Issue by flukeout** [aframevr/aframe#1479]
**Description:**
- In one of the Aframe demo scenes, start walking left by holding down the `A` key.
  - https://aframe.io/examples/showcase/helloworld/
- While holding the `A` key, press and hold the `shift` key
- Release the `A` key
- You will continue moving left

**A-Frame Version:** Whatever is running on the aframe site
**Platform/Device:** Chrome desktop

**Comment by msimpson** [comment]
The issue seems to be caused by the [onKeyUp handler ignoring events due to the shouldCaptureKeyEvent check](https://github.com/aframevr/aframe/blob/e32d8fa6d28183e941e864de3cb5351b73c0b9e6/src/components/wasd-controls.js#L149):
```
onKeyUp: function (event) {
  if (!shouldCaptureKeyEvent(event)) { return; }
  this.keys[event.keyCode] = false;
},
```
Is there a purpose to using `shouldCaptureKeyEvent` in the `onKeyUp` handler? It seems pretty idempotent without it.
