### ISSUE TITLE
Request: Make arrow keys work the same way as AWSD keys.

### ISSUE THREAD

**Issue by flukeout** [aframevr/aframe#1490]
**Description:**
Allow movement through a scene using the arrow keys in addition to ASWD, which only really make sense for people who have played first person shooters on PC in the past.

While using a mouse and arrow keys together feels awkward position-wise, it seems like a good idea to allow it for the initial experience.

- A-Frame Version: Any
- Platform/Device: Desktop w/ Keyboard

**Comment by ngokevin** [comment]
You can try https://github.com/donmccurdy/aframe-extras for now

There's a PR open for merging extensible controls in.

**Comment by donmccurdy** [comment]
@dmarcos an simple-ish fix for this, #333, and #1409 (short of the whole controls refactor) would be to (1) support the arrow keys, and (2) use `event.code` instead of `event.keyCode` if it's provided. In browsers that implement it, that will reflect the physical location of the key so that Dvorak and ZQSD keyboards work as expected.

Example:

```javascript
// Tiny KeyboardEvent.code polyfill.
var KEYCODE_TO_CODE = {
    '38': 'ArrowUp',
    '37': 'ArrowLeft',
    '40': 'ArrowDown',
    '39': 'ArrowRight',
    '87': 'KeyW',
    '65': 'KeyA',
    '83': 'KeyS',
    '68': 'KeyD'
};

var code = event.code || KEYCODE_TO_CODE[event.keyCode];

```

**Comment by darkwing** [comment]
Did a quick test on an example and I believe this can be closed with @donmccurdy 's PR

**Comment by ngokevin** [comment]
thanks
