### ISSUE TITLE
How to use correctly assets management for audio?

### ISSUE THREAD

**Issue by rafaeleyng** [aframevr/aframe#1633]
**Description:**

I'm trying to use assets management for preloading (or prefetching, I don't really know the difference) some audios before they are actually needed.

When I put a tag in `<a-assets>` like:
```
<audio id="sound-hall" src="./assets/sound/hall.mp3"></audio>
```

my browser makes a request and downloads the full audio. But, strangely, it finishes with HTTP status **206 Partial Content** (even though it has downloaded the full file, as I can check in the Content-Range header):

![image](https://cloud.githubusercontent.com/assets/4842605/16847846/5fe05f7e-49c9-11e6-8736-99a06e1f7508.png)

But when I actually want to use the audio, I need to place the URL to the audio again in the `src` for the `sound` component:

```
src: ./assets/sound/hall.mp3; autoplay: true
```

When this happens, a new request is made, and downloads the whole file again (no caching), with the same size, but this time with status **200 OK**:

![image](https://cloud.githubusercontent.com/assets/4842605/16847926/bb703512-49c9-11e6-90e7-8dd34f7ce056.png)

So my question is how to get this working for real? I would like to make a single request, that should end with a 200, or at least that the next requests end with status 304.

As a side question, one thing bothers me: when I use assets management for images, I can refer to the asset via its `id` attribute. Why when using `audio` should I refer to them via `src` attribute? At least this is what the docs show in the [example](https://aframe.io/docs/0.2.0/components/sound.html):

```
<a-scene>
  <a-assets>
    <audio id="river" src="river.mp3">
  </a-assets>
  <a-entity sound="src: river.mp3"></a-entity>
</a-scene>
```

- A-Frame Version: 0.2.0
- Platform/Device: any

**Comment by ngokevin** [comment]
Thanks for filing. This is sort of currently being addressed in https://github.com/aframevr/aframe/pull/1629 where we can refer to an `audio` tag by ID, but need to see if we can make THREE.AudioLoader accept audio tag contents.

**Comment by rafaeleyng** [comment]
Thanks, I'll stay tuned.

**Comment by ngokevin** [comment]
After talking with @mkungla, we have to:

- Detect if `src` is an `<audio>` or path.
    - If `<audio>` then don't use the Loader, and create context manually and get buffer.
    - If path, then use AudioLoader to fetch.
- Modify or fork the `src` type so that it preserves whether the data is media element or raw path. Right now, it always returns a string/path.

**Comment by mkungla** [comment]
@rafaeleyng #1629 *merged to master* 
````
// Setting it on element
<a-entity sound="src: url(river.mp3);"></a-entity>
// Using asset managment
<a-scene>
  <a-assets>
    <audio id="river" src="river.mp3">
  </a-assets>
  <a-entity sound="src: #river"></a-entity>
</a-scene>

**Comment by rafaeleyng** [comment]
@mkungla nice! Will try ASAP. Closing.

**Comment by rafaeleyng** [comment]
Is not working exactly how I expected, actually:

![image](https://cloud.githubusercontent.com/assets/4842605/17178539/3e4c6eb6-53ec-11e6-8b7d-fdcbbe57422f.png)

I'm dealing the same way with images and audios, but they seem to be handled differently by the assets management. For instance, the image `sl-hall.jpg`, it only appears once in my network tab, with a 200, but the corresponding sound, `sl-hall.mp3`, seems to make a request every time I go to the same room. The first one with 206, and subsequent with 200 but with `(from cache)` in the Size column.

This is basically the same situation that led me to open the issue initially, the difference here is that in my sound component now I'm referencing the src by id, not by the url anymore.

**Comment by mkungla** [comment]
@rafaeleyng since aframe depends on threejs and browsers limitation of the WebAudio API then most of it's behavior comes from there. You can't really compare images and audio since one is resource and other is buffer! So if you re enter the room then you see new request since request is made to reconnect the buffer. At this point there isn't cross browser way how to switch between cached audio buffer for audio element after it is initialized so therefore audio buffer is reloaded which is not a blocker since buffer does not download entire resource (as with images). So if you have audio file with 1 hour of sound track then your audio is not downloaded entirely but based on browser buffered some seconds ahead which is expected when you user might visit the scene only for few minutes. Difference between using aframe asset management or using audio source directly on element is that asset management will make sure that audio stream is ready to play as soon as scene is rendered while specifying src  on element  will first render the scene and then attends to buffer the audio.

**Comment by mkungla** [comment]
so therefore based on issue `How to use correctly assets management for audio? ` I don't find that this issue should be reopened since it does not direct real issue and it is covered how to use that! If something is unclear bring your questions into [slack](https://aframevr.slack.com/messages)

**Comment by rafaeleyng** [comment]
Thanks @mkungla , your explanation gave me a better understanding of the underlying problem.
