### ISSUE TITLE
Consider renaming 'src' property type to 'asset'

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1843]
**Description:**

With an extended deprecation period for the src type. 'asset' reinforces the relationship to a-assets and is less vague / more descriptive compared to 'src'. 

- A-Frame Version:
- Platform/Device:
- Reproducible Code Snippet or Demo URL [highly encouraged]:

**Comment by darkwing** [comment]
How does that relate to `<a-assets><img src></>`?  Does having two different attributes add complexity?

**Comment by ngokevin** [comment]
`<img>` is a type of asset within `<a-assets>` so it related. I'd intend to only have one property type, but giving time for deprecation.

**Comment by vrimaginar** [comment]
The src attribute has been around for ages and is completely understood by web developers. In my opinion changing the src attribute to asset adds complexity.

**Comment by ngokevin** [comment]
It's supposed to map to the concepts of assets, not 'src' which is a string. And 'src' in context of property types is not immediately obvious. 

Note this is only for property type name in schema, not the attribute name 'map: {type: 'asset'}'

**Comment by vassiliskrikonis** [comment]
Hey! I'm just into learning A-Frame and came across this. I wanted to comment on this because it really felt weird seeing a "src" attribute used to reference a CSS-ish selector. I mean, src is always used for implicit filenames. 
That said, although I've just started learning A-Frame I see the "src" used like everywhere, so deprecating this is gonna lead to serious code-breaks I think.

**Comment by ngokevin** [comment]
Hi! Again, this is for the name of the internal property type, not the name of the HTML attribute.
