### ISSUE TITLE
low resolution in VR mode V0.3.0

### ISSUE THREAD

**Issue by fuleinist** [aframevr/aframe#1873]
**Description:**
Hi guys,

I understand it's a known issue while is there a walk around or a timeline for resolving this issue for aframe master version?

Thanks & Best Regards,

- A-Frame Version: 0.3.0
- Platform/Device: iPhone6

**Comment by ngokevin** [comment]
We bumped the webvr-polyfill which had some issues with iOS. There is currently a bug in iOS Safari related to canvas resizing such that if we had it at full resolution, VR mode would look broken until you turned the phone. This should be fixed in iOS 10, so we told A-Frame to give it full resolution for iOS 10 Safari.

If you want full resolution (but it will look broken until you turn the phone), you can set `window.WebVRConfig = {'BUFFER_SCALE': 1}` before you include A-Frame.

**Comment by fuleinist** [comment]
Thanks Kevin : )
