### ISSUE TITLE
Throw warning if A-Frame script tag not in <head> (or after <a-scene>)

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2000]
**Description:**

Easiest way is to make sure it's in the `<head>` to reduce errors where people are including A-Frame after the scene HTML.

- A-Frame Version:
- Platform/Device:
- Reproducible Code Snippet or Demo URL [highly encouraged]:

**Comment by donmccurdy** [comment]
It might be helpful to also have a warning if components are registered after a scene is already in the DOM. Ideally that would "just work," but since it's complicated and we don't support it yet, nice to have a safety net for users putting A-Frame in `<head/>` but registering components after the scene.

(I've made this mistake myself a few times, since scripts that modify the scene do need to go later or wait for DOMContentLoaded)

**Comment by cvan** [comment]
The issue was originally filed as #485. Want to forward dupe?

**Comment by ngokevin** [comment]
Yeah, nice catch. I'll close that one as it's trying to support actually having the `<script>` in the body, and this is for a warning. We might be able to have `<script>` in the body with logic, but things could get messy, and components via `<script>` tag might not work as well if they also have to be in the body.

**Comment by jim-thisplace** [comment]
@ngokevin Thanks for logging this. I remember how long it took for me to figure out that was the cause initially. It should save people some time.
