### ISSUE TITLE
[0.4.0] Cannot opt-out of fog / apply flat shader

### ISSUE THREAD

**Issue by jesstelford** [aframevr/aframe#2142]
**Description:**

Opting out of fog with `material="fog: false; shader: flat"` no longer works on `master`:

```
<a-scene fog="type: linear; color: #AAB; far: 30; near: 0">
  <a-sphere
    position="0 10 0"
    radius="10"
    color="#93648D"
    material="fog: false; shader: flat"
  ></a-sphere>
</a-scene>
```

- A-Frame Version: `master` (909e5ec89cd2e0e11f56db51819deef170f0a115)
- Platform/Device: Desktop Chrome
- Reproducible Code Snippet or Demo URL [highly encouraged]:
  - `master` (not working): http://codepen.io/anon/pen/YpxPxz
  - `0.3.2` (working): http://codepen.io/anon/pen/NbvPvj

_Edit_: It appears to be working correctly on 32b1378109361e898eb47e51d1a7691013402c8b, which means something went wrong between [32b1378...909e5ec](https://github.com/aframevr/aframe/compare/32b1378109361e898eb47e51d1a7691013402c8b...909e5ec89cd2e0e11f56db51819deef170f0a115/)

_Edit 2_; Some `git bisect`ing reveals, the first bad commit is 8b0df2365c77dd43666afb6f63e922b4d4037753 / #2106 

_Edit 3_: Confirming; reverting the commits in #2106 fixes this issue.

**Comment by dmarcos** [comment]
Thanks for bisecting. This makes the fix much easier

**Comment by dmarcos** [comment]
I investigated this and It's a bigger problem than I thought. The root cause comes from the collision between the primitive mappings and some of the existing component names. Primitives map the `material.visible` to the `visible` attribute while `visible` is also one of the core components. When `visible` initializes it also triggers the primitive mapping update that sets the material component and the original `material` attribute is overwritten. 

I opened https://github.com/aframevr/aframe/pull/2145 to explore a solution. My first approach is to ignore mappings that have the same name as one of the registered components. This still won't work if components are register dynamically as the inspector does. @ngokevin What do you think?

I still don't know why https://github.com/aframevr/aframe/commit/8b0df2365c77dd43666afb6f63e922b4d4037753 unveiled the issue and we did not see it before.
