### ISSUE TITLE
scene reload() only shows a white page

### ISSUE THREAD

**Issue by giordyb** [aframevr/aframe#2239]
**the reload() method for a scene only shows a blank white page:**

- A-Frame Version: 4.0
- Platform / Device: tried on safari & chrome on macOS and windows 
- Reproducible Code Snippet or URL: 
with any scene open, just run document.querySelector('a-scene').reload(); in the developer console.

**Comment by sebi-b** [comment]
Hey there, I got the same error.
Are there any updates to this issue?

**Comment by rafaelboschini** [comment]
same here

**Comment by okwme** [comment]
same

**Comment by dmarcos** [comment]
@giordyb @sebi-b @rafaelboschini @okwme I'm curious to know what is your use case for the `reload` method? What are you trying to achieve?

**Comment by okwme** [comment]
@dmarcos i had aframe running as a thumbnail in a corner and when clicked it takes over the page. when it loads small like that the images are very compressed, if you just change the size the image compression becomes very visible. once it is large i destroyed the aframe and built it again so that the images appeared larger. if i had the ability to reload instead, the other state information like position of camera would not be lost on destroy and rebuild.
