### ISSUE TITLE
Controller events being emitted double (e.g., vive-controls `gripup`)

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2379]
**Description:**

1. Add an event listener to a controller (`gripup`) in the `showcase/tracked-controls` example.
2. Add a console.log in the event listener.
3. Open the scene and press the button. 

See the log shows up twice.

- A-Frame Version: 0.5.0
- Platform / Device: Vive / Windows / FF Nightly

**Comment by machenmusik** [comment]
is this due to https://github.com/aframevr/aframe/pull/2314#issuecomment-275812279 ?
specifically, if the event listeners for both `oculus-touch-controls` and `vive-controls` are active regardless of whether they are present...

**Comment by ngokevin** [comment]
Probably. Need to poke around to think of the best solution. @dmarcos would know best. Maybe introduce a property to force event listening that will be disabled by default, but enabled by replayers. 

What I don't think will work is trying to detect whether a different controller exists, that might be messy.

**Comment by machenmusik** [comment]
i think if you're not going to emulate the gamepad api (which would naturally emulate presence) then you need to inject something into the appropriate isControllerPresent to only attach when actively emulating, rather than leaving multiple instances of controls components with active listeners.  brings back to mind some of the earlier debates LOL.  note that if you have real vive and emulate touch or other supported controls, you would still have problems in all likelihood

**Comment by machenmusik** [comment]
@dmarcos ?  perhaps you can add an `emulated` property that controls the event listener behavior when not present, as @ngokevin suggests

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/2556
