### ISSUE TITLE
how to attach component on dynamically created element

### ISSUE THREAD

**Issue by jyprksh001** [aframevr/aframe#2421]
i am using react class to add dynamic elements 

cameraPosition(){
    var cameraEl = document.querySelector('#camera');
    var worldPos = new THREE.Vector3();
    worldPos.setFromMatrixPosition(cameraEl.object3D.matrixWorld);
    return (worldPos);
  }

  handler(){
    var el=$('a-scene');
    var pos=this.cameraPosition()
    var position=pos.x+" "+pos.y+" "+pos.z;
    var newEL=$('<a-cylinder  position="'+position+'" id="data-'+this.state.count+'"click-drag color="green" ></a-cylinder>').on('click',function(){
      $(this).on('dragend',function(data){
        console.log(data)
      })
    })
    el.append(newEL);
    this.setState({count:this.state.count+1});
  }

but the newly created element doesn't  register the component click-drag

**Comment by jbreckmckye** [comment]
I'm not sure, but a couple of thoughts come to mind:

Firstly, I would see if the component registers if you add it _after_ appending it to the DOM (by using .setAttribute).

Secondly, I would try adding the node using native DOM methods, rather than jQuery. It's possible the way jQuery manipulates the DOM isn't genial to how A-Frame listens for new scene nodes. A-Frame is not magic and does not, to my knowledge, use generic DOM mutation events to discover changes - it wraps specific DOM methods with interceptors that trigger Three.js operations.

As an aside, though - why are using jQuery in a React project? React already 'does' DOM manipulation. The whole purpose of JSX is to not have to create awkwardly interpolated template strings everywhere. Using jQuery in a React project is like buying a Ferrari and then taking it around town on the back of a flatbed truck.

**Comment by ngokevin** [comment]
Thanks for answering. Yes, DOM methods can be used as normal. It's up front on the introduction page: https://aframe.io/docs/0.5.0/introduction/#javascript (`We can use traditional JavaScript DOM APIs to manipulate A-Frame scenes to add logic, behavior, and functionality`).

Questions should also be asked on StackOverflow: https://stackoverflow.com/questions/tagged/aframe
