### ISSUE TITLE
Should isCoordinate be renamed areCoordinates?

### ISSUE THREAD

**Issue by kellyselden** [aframevr/aframe#2450]
I was confused for a moment when inspecting `AFRAME.utils.coordinates.isCoordinate` in the debugger. Seems it should be renamed (or aliased) to `areCoordinates`.

https://www.quora.com/Are-coordinates-plural-or-singular

**Comment by kellyselden** [comment]
I take it that label means you agree? If so, are you worried about breaking changes? Should it be aliased with a deprecation warning?

**Comment by dmarcos** [comment]
I don't think it should be renamed. It's a spread pattern in the code base to have isXXX to check for the type of a value. In this particular case I would even say that it's gramatically correct since it should be read as "is the string passed of the type coordinates?" maybe adding an s at the end would be enough `isCoordinates`

**Comment by kellyselden** [comment]
@dmarcos I like the idea of `isCoordinates`, saying "is of type `coordinates`".

**Comment by dye784** [comment]
@kellyselden , @dmarcos That's a good point since it's supposed to be read as type of coordinates.
