### ISSUE TITLE
Screen is going to sleep in stereoscopic mode on Android device

### ISSUE THREAD

**Issue by scottlittle** [aframevr/aframe#2514]
[Probably related to this previous issue.](https://github.com/aframevr/aframe/issues/1057) The screen is sleeping while in stereoscopic mode on my Android device (Chrome browser).

- A-Frame Version: 0.5.0
- Platform / Device: Nexus 5X, Android 6.0.1, Chrome 58.3029.21
- Reproducible Code Snippet or URL: https://codepen.io/scottlittle/pen/aJYBbd
- [Related Stack Overflow question](http://stackoverflow.com/questions/42936005/how-can-i-prevent-a-mobile-device-from-dimming-the-screen-or-sleeping-in-a-frame?noredirect=1#comment72969095_42936005)

**Comment by realitylab-ruben** [comment]
I recently ran into the same problem with a project of mine. What I've done is create a simple no-sleep component that starts playing a blank video on autoplay in the background when you press the VR button(because starting a video on a mobile generally requires user feedback). 

I believe AFrame is doing something similar, but it's not working on my own mobile.

Although it's not the best of solutions, it might be helpful for you...

```
AFRAME.registerComponent("no-sleep",  {
      schema: {
        video: {
          type: 'selector',
          default: "#nosleep"
        }
      },

      video: null,

      init: function() {
        document.querySelector('.a-enter-vr-button').addEventListener('click', () => { this.playVideo() });
      },

      playVideo: function () {
        this.data.video.play();
      }
    }
```
 I've uploaded the video I'm using at: https://www.dropbox.com/s/dudsnmo5gfs87q1/blank.mp4?dl=0. Just add this video into your a-assets with the id "nosleep", and this should work.

In the future, I'll turn this into a proper component in Github.

**Comment by frankymacster** [comment]
I'm observing the same thing. This is what I get in the console:
`Uncaught (in promise) DOMException: play() can only be initiated by a user gesture.`

A-Frame Version: 0.5.0
Platform / Device: LG-D852 (LG G3), Android 6.0.0, Chrome 58.3029.83

**Comment by scottlittle** [comment]
FWIW I updated Android to 7.1.1 and the screen is no longer going to sleep.
