### ISSUE TITLE
Option to enable databinding using Angular 2 or React

### ISSUE THREAD

**Issue by HeinPauwelyn** [aframevr/aframe#2523]
Continuing on this question #2518 using A-frame **version 0.5.0**, I would like that there is an option to enable databinding using Angular 2 or React in a next version of A-frame. 

In my opinion is the performance a little bit better when you're using databinding related to write if by yourself. Because not experienced programmers doesn't always think about the performance of JavaScript.

By using always `document.getElementById` for a lot of controles, the HTML DOM must be inspected every time and not performance at all.

**Comment by ngokevin** [comment]
It works with React https://github.com/ngokevin/aframe-react

I don't know what's needed to work with Angular 2, or maybe it does work. Check out https://github.com/brakmic/Angular2_VR_Starter

**Comment by wosevision** [comment]
For anyone finding this issue as of July 2017 onwards who might still be interested in the full picture: it doesn't work.

A-Frame components are impervious to Angular 2+ binding – it just does nothing in almost every case. The [Angular2_VR_Starter](https://github.com/brakmic/Angular2_VR_Starter) project that @ngokevin mentions doesn't make use of data binding whatsoever, and the lengths to which the author went to simply load up a scene using Angular as a basic launch platform are quite extensive. Angular feels less.. "familial" in the context of this app – more like a creepy uncle.

On a side note (just reporting from personal experiences), Angular 1.* doesn't exactly play nicely with A-Frame WRT data bindings either; a lot of them will _work_, but most of them present quirky issues with seemingly no remedy when used in real scenarios. Upgrading to my 1.* app to 4.* was my troubleshooting step for this since Angular 2+ seems much more "React-y" than its predecessor; turns out this is a misguided assumption.

> I don't know what's needed to work with Angular 2, or maybe it does work.

Perhaps it's time to consider removing Angular from the list of libraries under [this page/section's "Tool agnostic" subheading](https://aframe.io/docs/0.6.0/introduction/#features)? It works great with React (which is a solid achievement!) but there doesn't seem to be any interest from the A-Frame side in investigating compatibility with anything else but React (if I'm interpreting this thread correctly). Putting Angular and React in the same list seems more misleading the more information we have.

**Comment by ngokevin** [comment]
OK updating that page to remove the Angular piece

**Comment by wosevision** [comment]
Yup, it just suffers to from too little ROI. What was done in that integration was really quite clever, but really just the bare minimum of what A-Frame can offer and not much room to go upwards.
