### ISSUE TITLE
Provide or document a way to load a custom fragment shader.

### ISSUE THREAD

**Issue by oveddan** [aframevr/aframe#2541]
Is there a way to use a custom fragment shader for a material? If not, this feature should be added.  If so, the documentation should specify it.

I'd be glad to work on either.

**Comment by donmccurdy** [comment]
Hi @oveddan — there's some (admittedly light) documentation on the [registerShader](https://aframe.io/docs/0.5.0/components/material.html#example-1) API here, but you'll probably get more out of [this example](https://github.com/aframevr/aframe/blob/bbc2f0325cdd3c4bd95a69ce4ce9705b0e6a041d/examples/showcase/tracked-controls/shaders/skyGradient.js).

One thing that is lacking from the current implementation is a `tick()` method to update your uniforms. If you need uniforms other than the defaults provided by three.js, you may have a better time using a normal custom component with THREE.ShaderMaterial, as I've done in [this example](https://github.com/donmccurdy/webvr-experiments/blob/master/2-portal/components/portal.js#L48-L52).

More documentation is certainly welcome! But part of the reason we don't have it is because there's not a well-established best practice in A-Frame yet.

**Comment by oveddan** [comment]
Thank you @donmccurdy that example is great! Maybe we should document its existence?

**Comment by ngokevin** [comment]
Yeah, I think it's mostly because the API is half-cooked, and I'd prefer the component route for now. Adding documentation / disclaimers / links for that very welcome though.
