### ISSUE TITLE
Switch to Custom Elements v1

### ISSUE THREAD

**Issue by justinfagnani** [aframevr/aframe#2562]
Just looking through the source it appears A-Frame is still using the old "v0" Custom Elements API, which is only natively supported in Chrome. The newer v1 API is now natively supported in Safari, Chrome and has support from Firefox and Edge. Native support in mobile Safari should make initializing large scenes faster.

**Comment by ngokevin** [comment]
Thanks for filing! It's still not well supported, and since we override lots of Custom Element stuff, I imagine it being a large effort that would introduce bugs. Once it solidifies and is widely available, we could consider.

<img width="1253" alt="screen shot 2017-04-07 at 12 39 15 pm" src="https://cloud.githubusercontent.com/assets/674727/24816861/4ead8748-1b8f-11e7-9614-ad611596b265.png">

There's also https://github.com/aframevr/aframe/issues/567 so I'll dupe with that.

**Comment by justinfagnani** [comment]
@ngokevin Custom Elements v1 is way more supported than Custom Elements v0 which you're currently using. Safari, Firefox and Edge will never support v0. I'll take it to #567, since I wrote the v1 polyfill.

**Comment by ngokevin** [comment]
I understand. It's something we'll look at once there's wide support of V1. But switching from polyfill to polyfill will likely introduce bugs due to how closely A-Frame relies and overrides the current one. A-Frame doesn't use vanilla registerElement behavior.

**Comment by dmarcos** [comment]
Migration time has come. https://github.com/aframevr/aframe/pull/4167 moves A-Frame to Custom Elements V1. Thanks for patience.
