### ISSUE TITLE
Audio/sound currentTime returns 0 even as it is playing

### ISSUE THREAD

**Issue by memidgety** [aframevr/aframe#2762]
**Description:** 
When using <a-assets>, the <audio> src ('#audiosource') currentTime property does not seem to update. I am currently attaching a sound component to an <a-entity> ('#entity') and printing out the currentTime of the src which plays on init(). The return is always 0 even though the sound is playing.

```
<a-assets><audio id="audiosource" src="audio.mp3"> </a-assets>
<a-entity id="entity" sound="src:#audiosource; loop: true; autoplay: true; volume:2" ></a-entity>

<script>
var sound = document.querySelector('#audiosource');
// - some skipped code
console.log (sound.currentTime); // - this prints every render`
```

- A-Frame Version: 0.5.0

**Comment by memidgety** [comment]
When referencing to the sound component on the entity, the reference points to an undefined object.

**Comment by donmccurdy** [comment]
Ok, so it looks like the `#audiosource` element is no help at all here — presumably the three.js audio system is making its own copy of the sound, in order to do positional audio or something.

Instead, you need to use the element with the sound component attached to it, and then dig into the API a fair bit:

```js
var soundComponent = entity.components.sound;
// NOTE: If the audio file hasn't finished loading, `.source` will be null.
var audioSource = soundComponent.pool.children[0].source;
var audioContext = audioSource.context;
console.log('currentTime: %d', audioContext.currentTime);
```

Here's a demo: https://glitch.com/edit/#!/aframe-sound-demo

Clearly this isn't the most discoverable, and it's liable to break if there are multiple sounds in the pool... maybe we should expose a `getContext()` method on the `sound` component, for users to get at this programmatically?

**Comment by memidgety** [comment]
Using `pool` and `audioSource.context` does return the current time of the entity's sound component, however, it continues to increase even then when the sound source has stopped. This maybe because the sound pool object is "playing" even though it has stopped.

**Comment by agrafikr** [comment]
For the correct determination of the time you have to:
`var currenttime=audioContext.currentTime - soundComponent.pool.children[0].startTime;`

**Comment by agrafikr** [comment]
`var currenttime=audioContext.currentTime - soundComponent.pool.children[0].startTime  + soundComponent.pool.children[0].offset; `

Important: add offset when the audio is paused.
