### ISSUE TITLE
WakeLock/NoSleep.js Not Working on Android/Chrome(mobile)

### ISSUE THREAD

**Issue by 11fishem** [aframevr/aframe#2835]
The wakelock feature that is supposed to keep the screen from dimming with NoSleep.js is not working. The demo page for NoSleep.js does work on the same phone.

- A-Frame Version: 0.5.0
- Platform / Device: Samsung Galaxy S7 Edge w mobile Chrome browser
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/complete-capricorn?path=index.html:171:40

**Comment by rockwalrus** [comment]
If you attach the developer tools you can see a warning triggered by nosleep that says that the functionality it uses can only be used in response to a user event.

**Comment by 11fishem** [comment]
I'm hoping to the it into the VR Mode button and have that be the "User Event"

**Comment by dmarcos** [comment]
A-Frame already has a Wakelock mechanism when entering VR mode that works as expected for me on any of the aframe.io examples (https://aframe.io/examples/) and on a Samsung Galaxy S6. NoSleep.js is not working on the glitch example because it is not initialized by user action (NoSleep.js uses a video element playback mechanism), as the NoSleep.js demo (http://richtr.github.io/NoSleep.js/example/) does when the button is clicked. As mentioned above you can initalize NoSleep.js by putting a button or splash screen in your demo that user has to click. I don't think any action has to be taken on the A-Frame side, this is a general problem of integration of NoSleep.js with Chrome for Android.
