### ISSUE TITLE
WebGL errors being thrown when fog enabled

### ISSUE THREAD

**Issue by HAZARDU5** [aframevr/aframe#2897]
**Description:**

There's been a regression since A-Frame v0.6 (was also present in master since before the release of 0.6) which prevents the aframe-particle-system component from working when there is fog set on the scene. Details are logged here as an issue on that project: https://github.com/IdeaSpaceVR/aframe-particle-system-component/issues/26

It causes a WebGL error to be thrown:
```
THREE.WebGLProgram: shader error:  0 gl.VALIDATE_STATUS false gl.getProgramInfoLog Varyings with the same name but different type, or statically used varyings in fragment shader are not declared in vertex shader: fogDepth  
```
```
three.js:21505 WebGL: INVALID_OPERATION: useProgram: program not valid
```

- A-Frame Version: 0.6.1
- Platform / Device: Chrome / Desktop
- Reproducible Code Snippet or URL: https://codepen.io/maxakohler/pen/gRgZZP

**Comment by dmarcos** [comment]
The problem is the [SPE dependency](https://github.com/squarefeet/ShaderParticleEngine) of [aframe-particle-system-component](https://github.com/IdeaSpaceVR/aframe-particle-system-component/) that it's not compatible with THREE > r83. Since `r84` (A-Frame 0.5.0 used r83) there's a varying `fogDepth` declared in the [fog_pars_vertex](https://github.com/mrdoob/three.js/pull/10497/files#diff-e02b3101630f5ea2d12b18a6439d615a) chunk that [SPE](https://github.com/squarefeet/ShaderParticleEngine) has to [include](https://github.com/IdeaSpaceVR/aframe-particle-system-component/blob/master/lib/SPE.js#L900) when composing the vertex shader.

**Comment by dmarcos** [comment]
This is the THREE PR that introduced the change for reference: https://github.com/mrdoob/three.js/pull/10497

**Comment by faraazahmad** [comment]
So we use A-Frame 0.50?

**Comment by dmarcos** [comment]
Yes, you can use 0.5.0 or update https://github.com/IdeaSpaceVR/aframe-particle-system-component/ to make it compatible with THREE > r83

**Comment by etiennepinchon** [comment]
@dmarcos you mean just by adding THREE.ShaderChunk.fog_pars_vertex to the vertex array of SPE we should be able to fix the problem?
