### ISSUE TITLE
controller position updates only every half second (experimental Chromium, Oculus Browser...)

### ISSUE THREAD

**Issue by machenmusik** [aframevr/aframe#2975]
As mentioned in Slack
https://aframevr.slack.com/archives/C0GG937RN/p1502830167000371

It seems likely that this is a Chromium-specific regression due to the throttled tick optimizations.

**Comment by machenmusik** [comment]
Note that this also impacts Oculus Browser with GearVR Controller -- and may also impact Chrome on Daydream (can someone confirm?) -- only Firefox for Rift / Vive seems immune at the moment. @ngokevin @dmarcos this appears to be a significant regression

**Comment by machenmusik** [comment]
@fernandojsg says this happens on Daydream as well

**Comment by dmarcos** [comment]
@toji @DigiTec We found a discrepancy between Firefox and Chrome browsers concerning pose updates on gamepads. On Chrome (it manifests on both Chromium experimental builds and Oculus browser) once we get a reference to a GamePad the pose is not updated unless `navigator.getGamepads` is invoked and A-Frame has to call it once every frame. On Firefox, once we get the reference to the gamepad we can get the new `pose` by simply accessing the `pose` attribute. What is the expected behavior?

**Comment by machenmusik** [comment]
(Also Daydream Chrome)

**Comment by machenmusik** [comment]
#2984 should address this now
