### ISSUE TITLE
Use POT textures in examples

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#300]
Per https://twitter.com/mrdoob/status/677569574020100097

All images we use in the examples should be of power of two (for pef reasons):

![](https://pbs.twimg.com/media/CWc179zUkAAaCUC.png:large)

/cc @jcarpenter

**Comment by jcarpenter** [comment]
Thanks for filing!

**Comment by mattdesl** [comment]
POT is only needed if repeat wrapping is enabled and/or your `minFilter` is using mipmapping (see [here](https://github.com/mrdoob/three.js/blob/317d6f66542ab63323c5dab6c7a4e9d08c07ca05/src/renderers/WebGLRenderer.js#L2895-L2902)). If you set the following parameters, the texture won't be resized, and it will perform comparably to a POT size.

```js
tex.minFilter = THREE.LinearFilter
tex.wrapS = THREE.ClampToEdgeWrapping
tex.wrapT = THREE.ClampToEdgeWrapping
```

Though POT is always preferred since the GPU tends to handle it better, and could lead to (subtle) performance improvements in certain cases.

**Comment by ngokevin** [comment]
Fixed thanks @cemkod
