### ISSUE TITLE
Request: a docset for Dash/Zeal/etc

### ISSUE THREAD

**Issue by snoblenet** [aframevr/aframe#3052]
I would be absolutely marvellous if someone could create a comprehensive aframe docst for Dash/Zeal/etc.

**Comment by ngokevin** [comment]
That'd be cool, probably will elect not to maintain within the core repo though since there'd be overhead in keeping those resources up to date. The vast majority of people will be online.

Though what works for being offline is cloning the repo and doing `npm install && npm run docs` for offline docs.

**Comment by snoblenet** [comment]
I get:
```
$ npm run docs

> aframe@0.6.1 docs /Users/steven/code/aframe
> markserv --dir docs --port 9001

/Users/steven/code/aframe/node_modules/websocket.io/lib/socket.js:49
Socket.prototype.__proto__ = EventEmitter.prototype;
```
