### ISSUE TITLE
Canvas is not properly resized upon entering VR mode

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#3160]
**Description:**

1. Load an A-Frame example that is using `0.7.0`, such as the [`Shopping` example](https://aframe.io/aframe/examples/showcase/shopping/).
2. Click the "Enter VR" button.
3. Resize/maximize the browser window.
4. Notice that the canvas is not resized to the new dimensions of the browser window.

- **A-Frame Version:** `0.7.0`
- **Platform / Device:** Desktop / Any (reproduced on Windows and macOS)
- **Reproducible URL:** https://aframe.io/aframe/examples/showcase/shopping/
- **Screenshot:** ![Screenshot of 'Shopping' example, browser window maximized](https://user-images.githubusercontent.com/203725/31488313-217d960e-aef2-11e7-9520-d3b82167871d.png "Screenshot of 'Shopping' example, browser window maximized")

**Comment by NellWaliczek** [comment]
Is that really the expected behavior?  Shouldn't the canvas stay the correct size for the VR headset's resolution?

**Comment by cvan** [comment]
I `git-bisect`'d this regression back to this commit: https://github.com/aframevr/aframe/commit/4e98415

I see this was introduced in PR #3031. I see [this comment](https://github.com/aframevr/aframe/pull/3031#issuecomment-331105971), which was then handled in PR #3080.

Perhaps I'm missing something, but this doesn't fix the mobile cases.

> Is that really the expected behavior?  Shouldn't the canvas stay the correct size for the VR headset's resolution?

Totally reasonable concern, yeah.

Here's the common scenario where it looks really bad (on desktop):

1. Open an Edge/Firefox browser window
2. Launch an [A-Frame site](https://aframe.io/aframe/examples/showcase/anime-UI/)
3. Click the `Enter VR` button
4. Maximise the browser window
5. And you see a gaping white space

> Is that really the expected behavior?  Shouldn't the canvas stay the correct size for the VR headset's resolution?

On a Google Daydream or Samsung Gear VR, when you rotate the screen (as A-Frame's on-screen instructions tell you to), that triggers a canvas resize, which technically is increasing the resolution. If I return my phone to portrait mode, I'd expect the canvas to look like how it upon exiting VR as it did prior to entering VR.

On desktop, this is just an inconvenience and looks very much like a bug. But in the mobile scenario I described above, it jarbles up the screen. (I can provide a screenshot in a follow-up comment.)

**Comment by cvan** [comment]
As for screenshots I just promised, even better are these videos from @Pterko in #3166:

- https://www.youtube.com/watch?v=TyEItePPoPA
- https://www.youtube.com/watch?v=lk7ihgJwFQg

Let me know if you or @olga-microsoft have ideas on a solution that could benefit both our scenarios without too much compromise.

**Comment by cvan** [comment]
@NellWaliczek what are your thoughts on this, per my two comments above?

**Comment by olga-microsoft** [comment]
Hi @cvan,

My fix in #3031 was addressing a specific problem. When the user is in an immersive HMD the priority is for HMD resolution (which is set by the page), since the same canvas object is used both for HMD and desktop rendering. If the page does not use mirroring when presenting (preserveDrawingBuffer=false) then the canvas is not visible on desktop. This is preferred as it also reduces rendering costs.You shared the video of a mobile example. Do you expect the same behavior on mobile and desktop? I am not quite following, what is the expected behavior.
Do you agree that the canvas on desktop should be resized after exiPresent? 
The behavior is correct with MS Edge (mirroring is off): 
	1. Enter VR
	2. Resize the window
	3. Exit VR
The canvas size is updated.

**Comment by dmarcos** [comment]
@olga-microsoft you are right and your code is correct. The canvas should not be resized while presenting. The problem was an incorrectly `style.width` and `style.height` applied that were overriding the `width: 100%` and `height: 100%` applied by `a-canvas` style. https://github.com/aframevr/aframe/pull/3184 will fix the issue.

**Comment by olga-microsoft** [comment]
@dmarcos Thank you for fixing this!
