### ISSUE TITLE
AFrame DOM breaks existing HTML DOM conventions 

### ISSUE THREAD

**Issue by LeaVerou** [aframevr/aframe#3253]
We love AFrame and were looking to create an AFrame-[Mavo](https://mavo.io) demo, because we think it's a match made in heaven.

Sadly, it looks like AFrame components do not behave like normal HTML elements. We'd rather avoid having AFrame-specific code, and I suspect other libraries would have similar concerns.
The whole point of Web Components is that they’re supposed to work like normal HTML elements, and libraries that are element-agnostic should work with them out of the box.

Thankfully, it looks like we can still use `element.attributes[attrName]` and that works as expected.
However, the fact that `getAttribute()` returns an object will likely break a lot of code out there that assumes string or null.
Why not use the existing convention where `element.property` returns the object and `element.getAttribute()` the actual string (valid or not)?

cc @karger

**Comment by ngokevin** [comment]
A-Frame does not try to advertise pure 100% interoperability with the entire Web and Web Components stack. It piggybacks on top of DOM to provide a full game development framework that mirrors DOM APIs. In some cases, it works just fine (Preact, jQuery, d3.js). Since you were able to work around with `.attributes` (or `HTMLElement.prototype.getAttribute`, that's valid. But I don't think we will reinvent the entire framework at this point. Thanks!

**Comment by donmccurdy** [comment]
For a bit more context and some considerations behind A-Frame's API:

1. Scenes often call `setAttribute` and `getAttribute` many times per frame at 90fps. [De]serialization would add memory overhead likely to cause problems, which in-and-of-itself would be a major obstacle to using JS libraries with A-Frame. 😕
2. While we try to do what we can to support JS Frameworks, the vanilla developer experience does become noticeably worse with plain strings. Consider:

```html
<a-entity material="src: foo/diffuse.png;
                    normalMap: foo/normal.png;
                    aoMap: foo/ao.png"></a-entity>
````

```js
var material = el.getAttribute('material');
```

Practically we'd need to reflect the data to `el.property.foo` as you suggest, and this would be a pretty major breaking change for third-party A-Frame components. I assume we'd want to use ES5 getters/setters for that as well, and I'm curious what implications that has for performance... I'd love to see a proof-of-concept along these lines, but it seems like more of a rewrite than we can justify while working toward a stable 1.0.0 release.

**Comment by karger** [comment]
I can understand why you'd need object-based access instead of string-based for performance, but I don't understand why it's important to provide that object-based access by overwriting a standard method that is supposed to return a string.  If you're going to break the standard, why not do so by adding your own non-standard method so that the original one still works as advertised?

**Comment by ngokevin** [comment]
We wanted to provide a familiar API for web developers (including us), and in many cases, libraries happen to work (e.g., Preact, jQuery, d3.js, etc). The custom `<a-entity>` is documented with its custom behaviors, A-Frame doesn't break standard DOM elements. If developers needs a string form, there are several ways to retrieve that, although it'd have to be parsed again to be of any use.
