### ISSUE TITLE
laser-controls and oculus touch 6-dof controller

### ISSUE THREAD

**Issue by weddingdj** [aframevr/aframe#3260]
**Description:**

- A-Frame Version: aframe-master
- Platform / Device: latest FF 64bit, oculus rift and touch
- Reproducible Code Snippet or URL:

https://codepen.io/anon/pen/ooQXWy

On Master:
When using laser-controls the ray of the right controller is truncated. No entities are attached to the controller (no intersection). The left controller is working (click event as well) and the ray has its full length. The right controller's ray is not going far enough to reach an element to click on.

On 0.7.0 both rays have the right length, but clicking on elements does not work. If there is only one controller, then clicking works as well.

**Comment by dmarcos** [comment]
Does the laser-controls example work for you? https://aframe.io/aframe/examples/test/laser-controls/

**Comment by weddingdj** [comment]
Yes this example works in 0.7.0. It uses the mousedown event instead of click. But click should work too, or?

**Comment by dmarcos** [comment]
Yes, click should work. That demo uses
the click event on the cubes. Try mofify that demo as a starting point. It does not seem this is a bug on A-Frame since the demo works. It is something particular to your content. I recommend asking the question on stackoverflow or the slack channels. https://aframe.io/community/#slack

**Comment by weddingdj** [comment]
Ok, thanks. But on current master the ray of one controller is truncated.
