### ISSUE TITLE
Update three.js version to r88+

### ISSUE THREAD

**Issue by DJviolin** [aframevr/aframe#3263]
The latest three.js release corrected how handling gamma output with sRGB colorspace images: https://github.com/mrdoob/three.js/issues/12554

Can we have a build which is bundled with Three.js r88+ release? Even if it's in own branch or not named as `aframe-master.min.js`?

**Comment by donmccurdy** [comment]
The change coming with r88 can be patched in via:

```js
sceneEl.addEventListener('model-loaded', function (e) {
  e.detail.model.traverse(function (node) {
    if (node.isMesh) {
      if (node.material.map) node.material.map.encoding = THREE.sRGBEncoding;
      if (node.material.emissiveMap) node.material.emissiveMap.encoding = THREE.sRGBEncoding;
    }
  });
});
```

An effect of that will be that textured glTF models look darker. We can offset that by adding `renderer.gammaOutput=true`, which arguably should be the default anyway. The obstacle would be that `renderer.gammaOutput=true` will make existing scenes look brighter, so it's not fully backwards compatible. Compare these effects by dragging glTF models into https://gltf-viewer.donmccurdy.com/ and turning gammaOutput on or off.

I don't think we need a special one-off build with r88, since developers can opt into the sRGB texture encoding change easily, but when we do update we'll need to decide how to handle it for correct rendering vs backward compatibility.

**Comment by ngokevin** [comment]
A-Frame has upgraded to r89dev. Couple things to fix, but tracking in other issues.

**Comment by homerjam** [comment]
A vote for `renderer.gammaOutput = true` and `encoding = THREE.sRGBEncoding` as defaults from me!

**Comment by donmccurdy** [comment]
Proposed fix in https://github.com/aframevr/aframe/pull/3424. Encoding on `.map` and `.emissiveMap` will be handled by `gltf-model` and `THREE.GLTFLoader` already, so you'd just need to set `gammaOutput` for the correct result:

```
<a-scene renderer="gammaOutput: true" />
```

In retrospect it should likely have been true by default (same applies to three.js actually) but it will cause people grief if we change the default now. Consider that later on?
