### ISSUE TITLE
Making a Cone using a cylinder with different top/bottom radius doesn't work

### ISSUE THREAD

**Issue by staus** [aframevr/aframe#332]
Cone entity method is described here:
https://aframe.io/docs/components/geometry.html

Codepen showing that nothing happens:
http://codepen.io/anon/pen/bEexvM

**Comment by fernandojsg** [comment]
It works for me, can you give a try? http://codepen.io/anon/pen/OMXdZq

**Comment by cvan** [comment]
@staus: Unfortunately, we changed the cylinder geometry to no longer accept `radiusTop` and `radiusBottom` - so you need to use `geometry: cone` instead of `geometry: cylinder` if you want a cone shape.

https://aframe.io/docs/components/geometry.html#Cone

> <a-entity geometry="primitive: cone; radiusBottom: 1; radiusTop: 0.1"></a-entity>

if you do that, it works fine (also [confirmed](https://github.com/aframevr/aframe/issues/332#issuecomment-166773700) by @fernandojsg):

> http://codepen.io/team/mozvr/pen/dGXByq?editors=100

<hr>

We need to make a `<a-cone>` primitive, and that work will be done soon in aframevr/aframe#330 (also see https://github.com/aframevr/aframe-core/issues/741#issuecomment-166498744).

That should clear up things. But let us know if you have any other problems. Thanks!

**Comment by fernandojsg** [comment]
Ops sorry I just didn't notice that you said ```...using a cylinder...``` :)

**Comment by cvan** [comment]
Cone template was added in PR #337 :smile:
