### ISSUE TITLE
Add ZQSD for controller

### ISSUE THREAD

**Issue by tbalouet** [aframevr/aframe#333]
A simple request from France, if it would be possible to have the Z key mapped to the W action, and same thing with Q for the A, it would allow a seamless controller for AZERTY keyboards

**Comment by cvan** [comment]
:+1: Yes, we need to allow customisable keyboard mappings.

Specifically, https://github.com/aframevr/aframe-core/blob/1d07db6/src/components/wasd-controls.js#L83-L89 and https://github.com/aframevr/aframe-core/blob/a3855a3/src/core/a-scene.js#L539-L551 need to be developer-overridable (and possibly user-overridable, though that could be left as an exercise for the developer to do with JS; we'll have to make a call there).

We handled keyboard bindings with [simple language in Horizon](https://gist.github.com/cvan/a1e1a2ea9fb341dd6ad3). A popular library folks use is [Mousetrap.js](https://craig.is/killing/mice). I wrote a ["polyfill" for `KeyboardEvent.prototype.key`](https://github.com/cvan/keyboardevent-key-polyfill) (which lets you listen for `e.key == 'ArrowRight` instead of `e.keyCode === 39`). Open to alternatives.

**Comment by donmccurdy** [comment]
I was thinking of trying a general `keyboard-controls` component that emits arbitrary keyboard events on the target element (as opposed to `wasd-controls` focusing on movement) and the `e.key` polyfill seems like a really good way to go.

Apologies if this is horrifying and framework-ey, but any thoughts on using some sort of event-binding syntax?

Example:

```html
<a-model src="player.obj"
         keyboard-controls
         sound="src: pew-pew.mp3;
                on: keydown[key=f]">
</a-model>
```

Same thing could apply to more complicated actions like animations or WASD navigation, perhaps.

I tried something similar in gamepad-controls [here](https://github.com/donmccurdy/aframe-gamepad-controls/blob/bfa349214cb1ac9acedc0824e27adb2e4881770a/gamepad-controls.js#L215-L219), but i'm not entirely sure about the idea.

**Comment by donmccurdy** [comment]
Oops, just noticed the `<a-event />` syntax. That also seems nice, although I'm less clear about whether it would make sense for keyboard bindings.

**Comment by dmarcos** [comment]
Not sure about the DSL at the component property level. Those things get out of control pretty quickly and are very difficult to debug.

A more centralized way for components to listen to input events that adds some sugar (listening for a key name instead of using codes) could be cool. I thinks something at the ```a-scene``` level might work.  A keyboard-input module that the scene uses to broadcast keyboard events.

**Comment by ngokevin** [comment]
Don's new keyboard controls will help in the short-term, but I recommend against using FPS keyboard controls for VR.

**Comment by dmarcos** [comment]
I'm going to close this in favor of https://github.com/aframevr/aframe/issues/1490 to map the controls to the arrows so we don't have to consider every single keyboard layout
