### ISSUE TITLE
Tap or swipe on Gear VR touchpad crashes scene in Oculus browser

### ISSUE THREAD

**Issue by DougReeder** [aframevr/aframe#3333]
**Description:**

- A-Frame Version: 0.7.0 and 6019885
- Platform / Device: Gear VR + Galaxy S6 running Android 7.0
- Reproducible Code Snippet or URL:

1. In Gear VR, launch Oculus browser
2. Navigate to https://aframe.io/examples/showcase/helloworld/
3. Focus reticle on enter-VR button and tap touchpad. Device enters VR mode normally
4. Tap or swipe touchpad
    * expected result: no effect, as no click hander is set
    * actual result: scene crashes w/ toast: "Page has crashed and been recovered"

A tap or swipe on a paired Gear VR Controller does *not* crash the scene

(Samsung Internet VR doesn't properly go to VR mode, so it's unclear whether it has a similar problem)

**Comment by meatwallace** [comment]
We encountered the same issue while preparing our most recent production release and have determined it was an issue in `uglify-es`. We haven't worked out the exact version that introduced the issue, but we are having success building with `3.2.2`, and were facing the issue when using `3.3.5`. We haven't tested later versions.

We use `yarn`, have `uglify-es@^3.1.8` in our `package.json`, and although we enforce `frozen-lockfile` via `.yarnrc`, through a recent upgrade of `@storybook/react` we bumped our `uglify-es` version unintentionally. We solved it by using [yarn's selective dependency resolution](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/).

**Comment by DougReeder** [comment]
Thanks! It's good to know there's a path to getting it working.

**Comment by dmarcos** [comment]
@meatwallace Thanks for investigating.

**Comment by meatwallace** [comment]
- `uglify-es@3.3.7` (latest) has the same issue.
- When our page first renders we are seeing `components:text:error ReferenceError: nek is not defined` twice, presumably once for each of our 2 entities with the `text` component.Uglify is butchering [this function](https://github.com/mattdesl/word-wrapper/blob/master/index.js#L32), renaming it's args to something normal like `(a, b, c)` then where you'd expect `a.indexOf`, it puts `nek.indexOf`. Seems to be gracefully handled by A-Frame.
- Other functionality of our app is broken in Desktop Chrome with those versions of UglifyES due to things being `undefined`
- As per this issue, tapping the button immediately causes a crash. Can only speculate as to why, but presumably something similar.

The issue appears to be in UglifyES itself. It's affecting our entire app, not just A-Frame related code. It may be some specific configuration, but for now, we're settling for locking our version to `3.2.2` as we don't have the bandwidth to investigate further.

If someone has time, it'd be worth opening an issue on the Uglify repo. I couldn't see any related issues, but then again, I'm not really sure what I'm looking for.

**Comment by dmarcos** [comment]
@DougReeder is this still a problem with 0.8.2?

**Comment by DougReeder** [comment]
So far as I can test, this does not appear to manifest with 0.8.2 and later.
