### ISSUE TITLE
Component change or setAttribute() is much lower than v0.5.0 

### ISSUE THREAD

**Issue by a5507203** [aframevr/aframe#3362]
**Description:**
I am making a compass to indicate the camera look at direction
I add a listener to change the compass rotation when camera's rotation changed( component change event).
I found that for A-Frame 0.5.0 , the rotation of compass is really smooth, while in 0.6 or 0.7, it is really lag.

- A-Frame Version:
- Platform / Device:
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
Can you share a link with the before and after?

**Comment by dmarcos** [comment]
Have you tried `0.7.1`?

**Comment by ngokevin** [comment]
The componentchanged link was throttled in 0.6.0 onwards. Instead, use a tick handler to read rotation changes. You should be reading every frame because the camera rotation always changes in VR.

I've edited my answer here: https://stackoverflow.com/questions/38907857/how-to-listen-to-changes-in-the-rotation-of-the-camera-in-a-frame

**Comment by a5507203** [comment]
Yes, I tried, same issue.

**Comment by a5507203** [comment]
Thank you sooo much
