### ISSUE TITLE
Moving from 1 page to other , Pages does not retain the VR mode

### ISSUE THREAD

**Issue by Kshukla** [aframevr/aframe#341]
When we are in VR mode and redirect from page 1 to page 2 , page 2 opens in normal mode.

**Comment by dmarcos** [comment]
This is a limitation of the WebVR APIs relying on ```requestFullScreen``` API. Whenever the location of the page changes the full screen mode and hence the VR mode disengages. In future iterations of the WebVR APIs we will probably move away from ```requestFullScreen``` to allow page navigation without dropping the user from VR.

**Comment by cvan** [comment]
As @dmarcos says, we are in the process of writing a spec that will enable seamless link-to-link traversal of WebVR pages. We are evaluating our platform options at the moment. We will be public and transparent with the authoring of the spec (likely to live here on GitHub à la the the [WebVR Spec](https://github.com/mozvr/webvr-spec). Once implemented, this will be a non issue.

I can keep this issue open, but there's nothing in A-Frame we can do beyond hacks. We have previously implemented a solution that works in Firefox only using `<iframe>` - originally designed for [HIRO](https://github.com/mozvr/hiro), a browser prototype from back in 2014 (check out [this video here](https://www.youtube.com/watch?v=7-72zb81QFw), if you're interested).

And, there was also [a proof-of-concept solution](https://github.com/aframevr/aframe/pull/105/files) of swapping out the scene markup (and JS) from one A-Frame scene to another. But we decided to forgo this solution because it requires the scene to be an A-Frame scene to go from one to the next.

The third option is to embed multiple "pages" as different worlds wrapped in `<a-entity>`s and just use the `visible` component to do the toggling. It's not ideal, but you can achieve some pretty compelling effects using that.

Hope that helps :smile:

**Comment by Kshukla** [comment]
Guys got it, So this is not a A-Frame issue, makes sense thank you very much. 

As an alternate : Do you think an implementation which allows you to set the screen mode during page load either as URL param or a HTTP post parameter will help within A-frame. I believe such feature will only make it more agile to use for solving complex business problems. Anyways thank you very much.

**Comment by cvan** [comment]
Yeah, I've implemented this before using hashes.

So you'd have `http://localhost:8080/panoviewer/#paris`, `http://localhost:8080/panoviewer/#tokyo`, `http://localhost:8080/panoviewer/#boston` which would just toggle the visibility so only the one defined in the hash gets disabled. That's one way to go about it.

**Comment by cvan** [comment]
Also, if you're curious, here are how we've achieved (hacky) "link traversal" in Firefox before:

https://github.com/cvan/vrloader/blob/master/VRLoader.js
https://github.com/MozVR/hiro/blob/a6498dd/js/vrtab.js
https://github.com/MozVR/hiro/blob/a6498dd/js/vrmanager.js

**Comment by tbalouet** [comment]
Hi! How can you request full screen? I always get the error message that it needs to come from user's input, which is why I can't force it, even with a cookie telling me I was in VR before

**Comment by dmarcos** [comment]
User input is needed to request full screen. That's a security constraint of the requestFullscreen API so websites cannot take control of the display without the user being aware of it.

**Comment by cvan** [comment]
@tbalouet: we would have an "Enter VR" button which would trigger a fullscreen for the first scene. and then as long as you have `<iframe allowfullscreen>`, you'll be able to fullscreen the iframe (i.e., enter VR mode).

**Comment by ngokevin** [comment]
This will have to wait for the next WebVR API which we will have a separate issue for when it comes time. Thanks for filing!

**Comment by srdmathur** [comment]
Is it resolved?
