### ISSUE TITLE
a-primitive defaultComponents are not immediately accessible via getAttribute

### ISSUE THREAD

**Issue by robertlong** [aframevr/aframe#3431]
**Description:**

The components defined in an a-primitive's defaultComponents are not immediately accessible via `el.getAttribute()`. They seem to be added on the next tick.

For example on `<a-box>`, the `position` component (which is always added to `<a-entity>`) is available immediately, but `material` and `geometry` are not.

My Glitch snippet shows an example of this. Open the console to see the output.

My output is the following in both Chrome and Firefox:
```
Object { x: 0, y: 0, z: 0 }
null
null
Object { primitive: "box", buffer: true, skipCache: false, depth: 1, height: 1, width: 1, segmentsHeight: 1, segmentsWidth: 1, segmentsDepth: 1 }
Object { alphaTest: 0, depthTest: true, depthWrite: true, flatShading: false, npot: false, offset: {…}, opacity: 1, repeat: {…}, shader: "standard", side: "front", … }
```

- A-Frame Version: 0.7.0 / 0.8.0
- Platform / Device: Mac/PC, Firefox/Chrome
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/tranquil-cod

**Comment by ngokevin** [comment]
Thanks for filing!

Yeah, primitives are an abstract wrapper around `<a-entity>` where the `setAttribute` is the vanilla DOM `setAttribute`. That's why we'd recommend using `<a-entity>` for more serious work. Or living with the setTimeout. Unfortunately, I don't think we'll be changing or making major changes to primitives to improve this.
