### ISSUE TITLE
rayOrigin: mouse click event has wrong intersection location

### ISSUE THREAD

**Issue by rockwalrus** [aframevr/aframe#3467]
**Description:**

- A-Frame Version: 0.8.0
- Platform / Device: Firefox or Chrome on desktop
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/lace-coast

The example code should be placing objects so that they appear to be at the location clicked.

The intersection location given seems to have something to do with the location of the last object to have a `mouseleave` event, as if you set `raycaster: "objects: a-sky"` then the location never changes.

**Comment by donmccurdy** [comment]
Confirmed. @ngokevin, this is an indirect result of optimizations in #3250 — the `raycaster-intersected` event now only fires on _new_ intersections, meaning that `cursor` has outdated information when it fires a `click` event.

I think those changes to the `raycaster` API are reasonable; we shouldn't have events on every frame from the raycaster. What if we update `raycaster.checkIntersections()` to programmatically _return_ a copy of all current intersections, so that the `cursor` component can use recent coordinates?

**Comment by donmccurdy** [comment]
A further issue, in `cursor.onIntersection` we sort the intersections _in the current event_ and mark the nearest as active. if another nearer intersection is still be active, it is incorrectly lost.

**Comment by donmccurdy** [comment]
See #3475.
