### ISSUE TITLE
a-curvedimage's scale prevents lights from working

### ISSUE THREAD

**Issue by staus** [aframevr/aframe#348]
Codepen:
http://codepen.io/anon/pen/vLyzYq?editors=100

The cylinder to the left represents the way that a-curvedimage is currently implemented. It has a scale of 1 1 -1 to be able to show a given texture nonmirrored along the horizontal axis inside the cylinder. This has the side effect of only letting light from *outside* the cylinder illuminate it.

The cylinder to the right has a scale of 1 1 1 and as you can see the light illuminates it correct, but if you were to apply a texture to it, the texture would be mirrored along the horizontal axis.

For now I've solved it by using the cylinder to the right and then in photoshop mirror the original texture so it looks correct after being mirrored back in a-frame

**Comment by jcarpenter** [comment]
Thanks @staus. Curved image in general needs a lot of work to be "smarter". We're looking to address that when we move to a new implementation of the primitives. My first draft of the new approach for curved image is here: https://github.com/jcarpenter/aframe/blob/primitives/elements/primitives/a-curvedimage.js It does not yet have the logic for automatically determining theta-length / height based on image dimensions, but it does implement new approach to setting texture, using `repeat: -1 1` instead of scale. TBH I can't recall _why_ I went this route (a month ago seems so long!) but I do recall it was after much fiddling with different combinations of side, scale, and repeat.

**Comment by ngokevin** [comment]
now using repeat -1 1 https://github.com/aframevr/aframe/pull/883
