### ISSUE TITLE
Gear VR Controller does not work.

### ISSUE THREAD

**Issue by sabbir420** [aframevr/aframe#3483]
**Description:**
I am facing problem. I am using gear VR and I use 'gearvr-controls' but it does not work. It does not click. If I put cursor then by cursor is clicking but gear vr controller does not.  Here is an example. You can check from [here](https://odd-fortnight.glitch.me).

- A-Frame Version: 0.8.0
- Platform / Device: Gear VR
- Reproducible Code Snippet or URL:

**Comment by machenmusik** [comment]
this should be fixed by https://github.com/aframevr/aframe/pull/3429
see https://codepen.io/anon/pen/JLNRvx

**Comment by sabbir420** [comment]
@machenmusik  See my example. Clicking does not work. I checked your example too.

**Comment by machenmusik** [comment]
I don't think clicking does anything in the codepen I mentioned above (there are no handlers attached to the box entity that would do anything with clicks).

With respect to your previous glitch 
https://glitch.com/edit/#!/odd-fortnight?path=index.html:1:0
a few things:
- gearvr-controls is now built into A-Frame, don't include aframe-gearvr-controls-component anymore
- due to #3483, you need to use an A-Frame version that has #3429 built into it
- seems as though trackpad is acting as click with GearVR, rather than trigger

see this remix, which works with GearVR controller in Oculus Browser (and also Touch controllers in Firefox)
https://glitch.com/edit/#!/watery-teeth?path=index.html:56:0

**Comment by machenmusik** [comment]
note that in watery-teeth: 
- old component was removed
- patched A-Frame version is referenced instead of broken 0.8.0
- used laser-controls (which automatically includes cursors for controllers) instead of gearvr-controls
- removed explicit head-locked cursor (on the assumption that you'd want the controller cursor that laser-controls provides)

**Comment by machenmusik** [comment]
This should be fixed now in latest A-Frame master via #3489
