### ISSUE TITLE
Scene becomes "squished" when changing orientation on iOS Firefox and Safari

### ISSUE THREAD

**Issue by SteveX** [aframevr/aframe#3525]
**Description:**
Viewing the most basic example https://aframe.glitch.me/ on iPhone SE or iPad Pro 12.9" using Firefox and Safari, when you change device orientation the sphere, cylinder and cube can become "squished", so the sphere is ovoid etc. 

On the iPhone this happens when the browser is showing the controls, and also when started from a Safari Add to Home icon. 

On the iPad 12.9", this doesn't happen when the browser controls are showing, but does when the scene is started from a Safari Add to Home icon.

- A-Frame Version:0.8.0
- Platform / Device: Firefox and Safari on iOS / iPhone SE & iPad Pro 12'9"
- Reproducible Code Snippet or URL: https://aframe.glitch.me/

**Comment by RSpace** [comment]
I've investigated this issue. There's some funky bugs making it out into the Mobile Safari releases, like this one:
https://hackernoon.com/onresize-event-broken-in-mobile-safari-d8469027bf4d

However, there's already been a fix added for that (https://github.com/aframevr/aframe/issues/3282), and so this appears to be something else. Specifically, it has do to with how Mobile Safari returns the width and height of the window. Inspired by the article above and how it's done on apple.com, I found out that this bug goes away if we read the size of the viewport from `document.body.offsetWidth` and -`Height` instead of from `window.innerWidth` and -`Height`.

I've proposed this fix in this PR:
https://github.com/aframevr/aframe/pull/3711
