### ISSUE TITLE
Suggestion : Strongly Typed String Types?

### ISSUE THREAD

**Issue by PlumCantaloupe** [aframevr/aframe#3558]
Hi everyone,

One thing that has running in the back of my mind using this framework (and other javascript libraries) is why are all events, types, etc. left to the developer to type properly?

Could a framework like Aframe benefit from having all this string types saved as consts somewhere like (very rough implementation):

```javascript
//aframe.constants.js

const EVENT
{
    LOADED = 'loaded',
    MESHLOADED = 'object3DSet';
};

const SCHEMA_TYPE
{
    ASSET = 'asset',
    BOOLEAN = 'boolean'
    STRING = 'string'
};

module.exports = { 
    EVENT,
    SCHEMA_TYPE
 };
```
```javascript
//myComponent.js

AFRAME.registerComponent('mdmu-cutout-material', {
    schema: {
        property0:     {type:AFRAME.SCHEMA_TYPE.ASSET, default:''},
        property2:     {type:AFRAME.SCHEMA_TYPE.BOOLEAN, default:false},
        property3:     {type:AFRAME.SCHEMA_TYPE.STRING, default:''}
    },
    init: function() {
        this.el.addEventListener( AFRAME.EVENT.MESHLOADED, () => { console.log('loaded!'); });
    }
};
```

I know it is definitely more verbose but it may be helpful for beginners to have one place to see all functionality that could be "hidden" or "scattered across several pages of documentation (e.g. one place to see all events we can listen to aid async functionality). It will also make sure we reduce typing errors (something I am huge proponent of in C languages as compile and run-time errors are much better than invisible ones).

Thoughts?

**Comment by dmarcos** [comment]
Thanks for the ideas. In a cost-benefit analysis:

- As you said syntax is uglier an more verbose.
- We already have a [list of registered](https://github.com/aframevr/aframe/blob/master/src/core/propertyTypes.js#L11) types on a single place in code and docs. The list is not very long and most of types not often used. New users will still have to check [the documentation](https://aframe.io/docs/0.8.0/core/component.html#property-types) for details and more typing, uglier code for experts. 
- Extra maintenance to keep those lists up to date and greater risk of bugs. In the case of events specially there will be inconsistencies. We don't automatically collect all the events that all the components emit since they're not declared before hand (we could enforce event declaration). To emit an event you just call `el.emit('eventname');` anywhere in the code. We could manually collect the core events in a list but all 3rd party components would be missing from that list. Potential confusing: Why are some of the events in the list and not others?

I see some of the value on protecting against typos but after consideration of the costs an implications not sure if the balance is positive.

**Comment by PlumCantaloupe** [comment]
Thanks for the thoughtful considerations Diego.

**Comment by dmarcos** [comment]
@PlumCantaloupe Thanks for your suggestions. I'm closing but will reopen if you still think we need to revisit this.
