### ISSUE TITLE
Teleport Component does not work (teleport) anymore since 0.8.x

### ISSUE THREAD

**Issue by WintermuteGermany** [aframevr/aframe#3570]
**Description:**

- A-Frame Version: 0.8.x
- Platform / Device: Windows 10 / Firefox 59.0.3
- Reproducible Code Snippet or URL: https://github.com/fernandojsg/aframe-teleport-controls

**Comment by WintermuteGermany** [comment]
Using A-Frame teleport controls with A-Frame 0.7.0 is fine but since 0.8.x it is not possible to teleport any more: hands and teleportation sphere are still shown but no teleportation any more.
Since all A-Frame applications which also support mobile devices are forced to upgrade to 0.8.2 because of the recent mobile Chrome update a quick solution for using A-Frame teleport controls with 0.8.2 would be great.
Many thanks in advance.

**Comment by donmccurdy** [comment]
Are you using a `cameraRig` property, as shown in the example? A code snippet or demo URL would be useful.

```html
  <a-scene>
    <a-entity id="cameraRig">
      <!-- camera -->
      <a-entity id="head" camera wasd-controls look-controls></a-entity>
      <!-- hand controls -->
      <a-entity id="left-hand" teleport-controls="cameraRig: #cameraRig; teleportOrigin: #head;"></a-entity>
      <a-entity id="right-hand" teleport-controls="cameraRig: #cameraRig; teleportOrigin: #head;"></a-entity>
    </a-entity>
  </a-scene>
```

**Comment by WintermuteGermany** [comment]
http://www.winz-it.de/vr/index.html

**Comment by WintermuteGermany** [comment]
<a-entity id="left"
                      teleport-controls="button: trigger; collision-entities: #hall_low_floor"
                      hand-controls="left"
                      visible="true"
                      position="-10 30 120">
                <a-animation attribute="position"
                             dur="14000"
                             easing="ease-in-out"
                             to="0 1 -15">
                </a-animation>
            </a-entity>

**Comment by donmccurdy** [comment]
You'll need to use a camera rig (just an entity wrapper around your camera) with `teleport-controls` in A-Frame 0.8. From the changelog:

> Remove VREffect / VRControls for three.js WebGLRenderer API. VR camera pose is managed by three.js.

The docs for `teleport-controls` have been updated to reflect this as well. In VR mode, the position of the camera is locked to the pose of the device. This solves many issues from previous versions, but also requires a change to your markup. The rig should be moved when animating or teleporting, rather than the camera.

If you find that isn't working well with `wasd-controls`, you may want to try `movement-controls` from aframe-extras instead, which has better compatibility in this situation: https://github.com/donmccurdy/aframe-extras/tree/master/src/controls#usage

**Comment by dmarcos** [comment]
I have created a simple glitch example using teleports and A-Frame 0.8.2: https://glitch.com/edit/#!/fixed-range

**Comment by WintermuteGermany** [comment]
You're right, now it's working. Many thanks from Germany! :-)

**Comment by dmarcos** [comment]
@WintermuteGermany You’re welcome from a fellow Spaniard
