### ISSUE TITLE
WASD not working

### ISSUE THREAD

**Issue by Logabe** [aframevr/aframe#3664]
**Description:**
When I use the WASD controls for moving around, it glitches me to the outside of the world.
- A-Frame Version: 0.8.2
- Platform / Device: Chrome on linux
- URL: https://hover-tech.glitch.me/journey.html
- Code: https://glitch.com/edit/#!/hover-tech?path=public/journey.html:13:61

**Comment by ngokevin** [comment]
Works fine. May sometimes glitch if computer is under a lot of load.

**Comment by damned** [comment]
hi,
for anyone else with similar problem, i hit this: `wasd-controls` working intermittently for me on my trusty but old laptop (where i develop before opening in a Quest)

as Kevin suggested, this seems to be due to hitting a hard-limit on FPS - my 8-years old laptop was struggling to achieve the approx. 5 fps needed before `wasd-controls` stops itself working.  you could verify this by adding the stats attribute to a-scene:

`<a-scene stats> ...`

for development purposes this can be side-stepped by adding (something like) the following renderer attributes to the scene entity html, to configure the WebGL renderer for a lower resolution, which is one way to raise the FPS:

`<a-scene renderer="maxCanvasWidth: 600; maxCanvasHeight: 400">  ...`

for other ways to raise FPS search for aframe performance tips.
 
if happy with the low FPS but not with these workarounds, __i've not tried it__ guess you could fork wasd-controls and change the `MAX_DELTA` that triggers this here:

https://github.com/aframevr/aframe/blob/master/src/components/wasd-controls.js#L10
