### ISSUE TITLE
A-Frame + Trackingjs

### ISSUE THREAD

**Issue by DaniAframe** [aframevr/aframe#3674]
Hello! I'm trying to recognize a color (white for example) and then i wanna make appear some 3d objects using A-Frame (a-box, for example). I've tried so many times but never works, i don't know what i'm doing wrong. Does anyone have tried something like this?

Thanks!

**Comment by Utopiah** [comment]
Hi, "never works" isn't enough to see if the problem comes from : 
- A-Frame itself (which is what the issues here are for) or
- trackingjs (better ask there) or also
- improper usage of either in which case the documentation or Slack is best.

So does the console provide any error message? Do you have an online page it would be possible to test? What version of AFrame are you using on what configuration (device, browser with version)?

**Comment by DaniAframe** [comment]
Hi @Utopiah, when i try to use both AFrame and Trackingjs, i can't manage to put the 3D Object on the trankingjs scenario (webcam transmition), so it appears like this,

![image](https://user-images.githubusercontent.com/39561960/42080590-1d827488-7b7b-11e8-9fdf-7cc712643cad.png)

I don't think that the problem is A-Frame or trackingjs, i simple donno the correct way to put thhe 3D Object on the webcam transmition. So answering to your questions, it doesn't appear an error message on the console; I'm sorry but I don't have a online page where you can test it, but if you wanna i can provide some code; The A-Frame version is 0.8.0 and I'm using Google Chrome.

Thanks!

**Comment by Utopiah** [comment]
Thanks for the clarification @DaniAframe . 

Please join instead [A-Frame Slack](https://aframevr-slack.herokuapp.com/) or [StackOverflow](https://stackoverflow.com/questions/tagged/aframe?sort=newest) where me and others will try to help you and close this issue as those are restricted to A-Frame problem.

**Comment by DaniAframe** [comment]
Link to the question on StackOverflow: https://stackoverflow.com/questions/51098369/a-frame-trackingjs
