### ISSUE TITLE
Keep  Movement Controls (WASD or Controller or Touch) in headset

### ISSUE THREAD

**Issue by TheBiggestNumber** [aframevr/aframe#3702]
Hi,

WASD, Controller and Touch Movement Controls get disabled when entering VR headset mode.

Is there a way to keep these movement controls active in the headset?

Thanks!

**Comment by dmarcos** [comment]
This is intentional behavior. WASD based locomotion in VR is motion sickness inducing. I recommend other mechanisms like [teleport](https://github.com/fernandojsg/aframe-teleport-controls). This is also a question better suited for [StackOverflow](https://stackoverflow.com/questions/tagged/aframe). We use Github for bugs and feature requests.

**Comment by donmccurdy** [comment]
For future readers:

See aframe-extras and https://github.com/donmccurdy/aframe-extras/blob/master/src/controls/README.md - you’ll need to have an entity (“camera rig”) wrapping the camera. This also applies for things like teleportation.
