### ISSUE TITLE
Videosphere broken on Chrome destkop v66/67

### ISSUE THREAD

**Issue by VitoMatarazzo** [aframevr/aframe#3706]
Description:
360° videos in Aframe's videosphere are not working correctly in the last versions of Chrome desktop. In particular, the video blinks (video alternates visible frames with white frames) while it is playing and is completely white when it is paused, in Chrome v67. Instead, in v66 the video works but is continuosly vibrating.
The videos work well on Firefox and on Chrome for Android. 

- A-Frame Version: 0.8.1/ 0.8.2
- Platform / Device: Chrome Desktop v66/67
- Reproducible demo: you can use the code of the videosphere example in Aframe's homepage.

**Comment by ngokevin** [comment]
Probably a fault of Chrome's policies https://developers.google.com/web/updates/2017/09/autoplay-policy-changes ... I don't particularly agree with them, it's what happens when VR is not a first-class citizen in a browser.

I believe if developers want to support video on Chrome, they need to register a listener to a click on the page then play the video.

I think Chrome should address it, it's not worth trying to make it work out of the box for A-Frame as we've seen the struggles on iOS Safari. There's not a strong focus for A-Frame to support all the video cases, but more full VR applications. So I think Chrome should either address it, developers work around it, or just leave a notice not supporting Chrome...or start targeting the rising class of VR-first browsers.
