### ISSUE TITLE
npm install freezing

### ISSUE THREAD

**Issue by claytongulick** [aframevr/aframe#3753]
**Description:**
when doing npm install --save aframe on windows, the installation freezes. Looking at the verbose output, it looks like the freeze happens on a dependency: document-register-element. Tracing into that, it looks like document-register-element has a post-install script called lightercollective that some sort of donation thing?
```
C:\source\omiga\mobile\web\vr_src>npm install --save aframe --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\clayt\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--save',
npm verb cli   'aframe',
npm verb cli   '--verbose' ]
npm info using npm@6.4.0
npm info using node@v10.5.0
npm verb npm-session 6ac3bce3cfadc5af
npm http fetch GET 304 https://registry.npmjs.org/aframe 458ms (from cache)
npm timing stage:loadCurrentTree Completed in 1248ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 3ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 233ms
npm http fetch GET 304 https://registry.npmjs.org/load-bmfont 138ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/deep-assign 144ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/browserify-css 160ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/promise-polyfill 161ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/object-assign 177ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/present 224ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/style-attr 85ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/three-bmfont-text 74ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/webvr-polyfill 77ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/envify 327ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@tweenjs%2ftween.js 432ms (from cache)
npm info lifecycle document-register-element@0.5.4~prepack: document-register-element@0.5.4
npm info lifecycle document-register-element@0.5.4~postpack: document-register-element@0.5.4
[..................] - fetchMetadata: info lifecycle document-register-element@0.5.4~postpack: document-register-elemen
```
Is the polyfill for custom elements v1 even necessary any more?

- A-Frame Version: 0.8.2
- Platform / Device: windows 10

**Comment by claytongulick** [comment]
Looks like the issue was a npm one? It's fixed itself. Disregard :D

**Comment by ZendyLim** [comment]
I'm having the same problem now
verbose also showing same result

**Comment by haysclark** [comment]
Ran into this issue from a package that had `aframe` as a dependency. For me `npm install --verbose` helped show that files were downloading; however, it does not show the various `postinstall` or other steps that are running for some packages. 

Amazingly, `npm install` took over 11 minutes on a very new 2021 Apple M1 (Max) CPU and 1Gb fiber Internet access!

There are some _stackoverflow_ threads on the topic:

- https://stackoverflow.com/questions/37860219/npm-gets-stuck-on-fetchmetadata-network
- https://stackoverflow.com/questions/45433130/npm-install-gets-stuck-at-fetchmetadata

The fastest alternative to waiting I found was to simply use `yarn` to install the package instead of `npm`. 

via _npx_:
```bash
npx yarn install
```

or the global install method:
```bash
sudo npm install -g yarn
yarn install
```
