### ISSUE TITLE
Make component properties case insensitive.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#3759]
**Description:**

Avoid user errors from not remembering camel-casing or camel-casing component properties. Components shouldn't offer different properties that have the same name but different cases.

```js
// Which one?
material="colorSpace: srgb"
material="colorspace: srgb"
```

**Comment by donmccurdy** [comment]
I think the current warnings (`core:schema:warn Unknown property "colorspace" for component/system "material". `) are quite clear in cases like this, but could maybe be improved to suggest, `Perhaps you meant "colorSpace"?` when there's a case-insensitive match. To make properties case-insensitive we'd need to essentially lowercase the string by default, which would break a lot of existing components for what isn't a obvious UX improvement to me — `foobarbaz` is harder to read than `fooBarBaz`, and if my component's internal code is forced to switch to `foobarbaz`, as the component author, I'd be documenting `foobarbaz` rather than `fooBarBaz` and passing the legibility loss on to users.

**Comment by donmccurdy** [comment]
I agree we don't want a component to deliberately use two properties with names that vary only in case, but we've never seen a component do that either... if we wanted to prevent that, we could do so as a runtime check without loosening the API.

I'm worried that loosening the API to accept imprecise input is not the most elegant way to reduce errors, and it's impossible to revert without breaking changes. Is there user feedback suggesting things like `normalMap` are often mistyped? I haven't seen any, and colorspace/colorSpace isn't really motivating enough by itself. Console warnings are an effective solution to this, IMO.

**Comment by ngokevin** [comment]
Things probably get mistyped a lot or at least people need to double check the docs. Console log catches it but the point is to avoid the whole process of debugging altogether. There’s no reason to make them case sensitive is what it goes down to.

**Comment by ngokevin** [comment]
I just thought of the case of perhaps looping over a component schema though this wouldn’t be good so I could close.
