### ISSUE TITLE
Camera's child entities won't fix to camera in vr mode (in mobile)

### ISSUE THREAD

**Issue by fzaiatz** [aframevr/aframe#3771]
Cursor or any other camera's child entity doesn't seem to respect fixed position when in vr mode (this is working as expected in 0.8.2)

- A-Frame Version: master (19/9/18)
- Platform / Device: Safari/Chrome (iOS 11, iOS 12)

**Comment by dmarcos** [comment]
This is a side effect of the new VRManager API. The camera passed to the `render` method on of `THREE.Scene` is not the camera used to render on VR mode and hence its transforms don't carry on to the children of the `true` camera.

**Comment by ngokevin** [comment]
Gross workaround is just add the entities under `cameraEl.getObject3D('camera')` via JS (move the object3D over), or copy the `cameraEl.getObject3D('camera')` position/rotation to another entity.

**Comment by ngokevin** [comment]
What entity do you copy it to? Three.js requires to manipulate the camera, and had to fight a bit to even be able to send that data up to aframe. If you copy to the camera entity, the transforms will stack.

Moving completely to XR now is out of the question for me. Will want to support both. XR API is going to take a while to roll out, and from what it looks, it’s going to have less features and capabilities than the current API. Most likely will want to have aframe manage the vr/XR rather than three.js soon. Doesn’t offer enough control

**Comment by machenmusik** [comment]
Sorry, I thought from your description that it was a different camera and transforms wouldn't stack so it would be easy.

Yeah, WebXR may lag for a while, and it seems to me that the switch away from VRControls and A-Frame being in control isn't working out so well at the moment

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/3820
