### ISSUE TITLE
Animation events bubbling not constant

### ISSUE THREAD

**Issue by beyerz** [aframevr/aframe#3930]
**Description:**
When animating a group of entities, and listening for animationbegin and animationcomplete events
the animationbegin event is handled multiple times, while the animationcomplete event is handled once

This is due to animationcomplete not bubbling and animationbegin bubbling in the emit function.

The bubbling should be the same for both events and I think that they should not bubble.

- A-Frame Version: 0.8.2 (Date 2018-12-01, Commit #a35c367)
- Platform / Device: OSX/Chrome
- Reproducible Code Snippet or URL:

**Comment by lchsam** [comment]
Hi,

I was wondering why the events in the animation component should not bubble.
The reason I am asking is because a project can have many animations and having many event listeners for them may not be ideal.
I may be wrong but would it not be better if the events are allowed to bubble. Developers who want to add event listeners for each element with animations are allowed to do it. Those who want to use event listeners on parents/ancestors of the animated elements ([Event Delegation](https://stackoverflow.com/questions/1687296/what-is-dom-event-delegation)) are also allowed to do it.

(The `frame/CONTRIBUTING.md` doesn't seem to disallow commenting on old issues but if I made a mistake, I can move this question elsewhere).
