### ISSUE TITLE
Add iframe component

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#399]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcarpenter](https://github.com/jcarpenter)**
_Wednesday Aug 26, 2015 at 19:17 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/12_

----

Enables user to display a floating 2D web view in the world

* Source URL
* Width
* Height

**Comment by ngokevin** [comment]
<a href="https://github.com/nickdesaulniers"><img src="https://avatars.githubusercontent.com/u/1823839?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nickdesaulniers](https://github.com/nickdesaulniers)**
_Friday Aug 28, 2015 at 22:09 GMT_

----

cssvr shared depth buffer issues

**Comment by ngokevin** [comment]
Due to browser security, this is non-trivial.

With three.js, you can currently overlay a CSS-transformed I-Frame element over the canvas. This works okay, but this falls apart with VR and stereoscopic rendering.

It is possible to render a canvas as a texture, and we can create images using the DOM. But not sure if we can do that with I-Frames.

Crazier solutions involve a backend server streaming textures.

**Comment by davidje** [comment]
any follow up or solution?

**Comment by dmarcos** [comment]
Unfortunately, this is not possible without having a new Web API to render elements as textures in WebGL. We could indeed position an iframe with CSS 3D transforms that integrates in the same coordinate system as the WebGL content but:
1. For stereo rendering, we would have to manually duplicate the DOM which is inefficient and will introduce confusion when handling events and selecting elements. 
2. Distortion wont be applied to the iframe since it's handled by the browser on the canvas element pushed to the HMD.
3. The iframe would always sit on top of the WebGL content making it useful only for HUD kind of applications. You could hack your way with techniques like alpha punching (that creates multiple canvases with wholes that let DOM elements pass through) that are very inefficient.
4. No shading can be applied to the iframe to integrate it in the 3D scene. Imagine you want to show an iframe behind a glass surface that reflects the environment. 

Until we have a browser API to render an arbitrary element as a texture in WebGL you won't be able to use iframes (or any other DOM element) in an aframe. There's some discussion going on to bring such a feature to gecko. More info here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1237489

**Comment by ngokevin** [comment]
Parallel discussion https://github.com/aframevr/aframe/issues/974#issuecomment-189995329

**Comment by ngokevin** [comment]
Closing because not possible. If a solution ever lands, we can re-open and add the feature ASAP.

**Comment by cjroth** [comment]
Just for reference, I experimented with using PhantomJS to render a page continuously and stream it in as a video. From there you could forward click/keypress events back to Phantom. This works, but it's not very practical because phantom is very process intensive and can only render every so many milliseconds so the frame rate of the page is extremely low.

It sounds like some sort of new browser API will be the way to go.

https://github.com/cjroth/aframe-phantomjs-continuous-streaming

**Comment by cvan** [comment]
@cjroth btw, there is a MediaRecorder API (supported in both Firefox and Chrome/Chromium):

* https://hacks.mozilla.org/2016/04/record-almost-everything-in-the-browser-with-mediarecorder/
* https://mozdevs.github.io/MediaRecorder-examples/
