### ISSUE TITLE
[FEAT] make threejs peer dependency

### ISSUE THREAD

**Issue by Hulkmaster** [aframevr/aframe#4006]
**Description:**

right now threejs has strict version, hardcoded into package.json

i suggest making it a peer dependency, because it is more flexible and allows to use some later threejs features (like Quaternion.angleTo)

**Comment by ngokevin** [comment]
This cannot be done at the moment since the three.js version we use has a few patches that make A-Frame work with WebXR. We could make it a peer dependency if we ever get back to mainline, but there may be cases in the future where we need to upstream patches and would have to flip back and forth between peer and dep. Maybe better to just keep it as dep for now. You can copy and paste the methods since they are functions for now. Thanks!
