### ISSUE TITLE
objectPool property leakage

### ISSUE THREAD

**Issue by 3DataWill** [aframevr/aframe#4012]
**Description:** For components with schemas that change (e.g. geometry), the object pooling can lead to the presence of inappropriate keys in a components data object when a used object is picked up from the pool during component initialization

- A-Frame Version: 0.9.0
- Platform / Device: Desktop FF & Chrome
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/ultra-woolen?path=index.html:17:13
Expected behavior: console log of geometry.data keys contains only sphere-related values
Observed behavior: console log includes height,width,depth from recycled box data object

**Comment by 3DataWill** [comment]
Was the use of `object[key] = undefined` over `delete object[key]` in `objectPool.clearObject` a decision related to garbage collection minimization?

**Comment by ngokevin** [comment]
Yeah, sort of intentional, I remember it was better for GC, but forgot why. Only happens in dynamic schemas (wish there was a simpler way to support those). Maybe loop over the schema to enumerate keys instead?

**Comment by ngokevin** [comment]
Yeah, sort of intentional, I remember it was better for GC, but forgot why. Only happens in dynamic schemas (wish there was a simpler way to support those). Maybe loop over the schema to enumerate keys instead or check for undefined values?

**Comment by 3DataWill** [comment]
In the update case, there are checks in `extendProperties` and `copyData` that skip over undefined keys. I could only reproduce this in the initialization case. I could try applying the same logic to the initial object requests in the component constructor

**Comment by vincentfretin** [comment]
Related to this, I have simple code that do
```
const plane = document.createElement("a-plane");
plane.setAttribute("height", 0.196);
plane.setAttribute("width", 0.196);
AFRAME.scenes[0].appendChild(plane)
```
initially it shows a plane, now if I remove the dom element and recreate it, it will take an object from the pool and it will sometime show a box instead of a plane. Somehow I get "primitive: undefined" in the object.

Putting a `console.log(this.attrValue)` in `src/core/component.js` `initComponent`, I get initially 
`{width: "0.196", height: "0.196", primitive: "plane"}`
and if it take an existing object from the pool, I can get this:
`{width: "0.196", height: "0.196", primitive: undefined}` => this one is very problematic
and other time:
`{radius: undefined, width: 0.196, height: 0.196, primitive: "plane", buffer: true, …}`
triggering a warning:
core:schema:warn Unknown property `radius` for component/system `geometry`.

Now If I change the implementation of `clearObject` to delete the keys:
`for (key in obj) { delete obj[key]; }`
all the issues goes away.

**Comment by vincentfretin** [comment]
Your PR #4016 doesn't fix the `primitive: undefined`, creating a box instead of plane or ring. so it's probably another issue. I created #4027 with more details.
