### ISSUE TITLE
Cannot disable loading screen

### ISSUE THREAD

**Issue by bknill** [aframevr/aframe#4045]
This is in a React project,  but not sure that should make a difference. 

`<Scene loading-screen="enabled:false"  />`

Has no effect. 

I cannot disable the loading screen. 

- A-Frame Version: 0.9.0
- Platform / Device: Windows 10/ Chrome 72

**Comment by dmarcos** [comment]
It works for me https://glitch.com/edit/#!/twisty-salamande

Need to share complete test case to reproduce.

**Comment by bknill** [comment]
That one isn't loading. No project found at twisty-salamande, perhaps a typo?

I've tried with this setup (Aframe inside a React component)

https://glitch.com/edit/#!/eminent-spice

But I'm having trouble getting something in there that will trigger the loading-screen. 

Can you let me see your example so I can try and merge them?

**Comment by dmarcos** [comment]
I corrected the URL in https://github.com/aframevr/aframe/issues/4045#issuecomment-468022677

**Comment by dmarcos** [comment]
The loading screeen shows up while assets are loading: https://aframe.io/docs/0.9.0/core/asset-management-system.html#sidebar

Your example does not have an `a-assets` tag.  I don't use react so I can't tell if it's also interfering. We usually discourage using React because introduces glitches and performance issues.

**Comment by bknill** [comment]
ahh.. thanks.

I was still using <Scene... using <a-scene fixed it.

**Comment by olivier-wondavr** [comment]
In case it's worth sharing, it happens when scene is dynamically added to the page.

See glitch example: https://glitch.com/edit/#!/six-tabletop
You should see the loading screen appear whereas scene has loading-screen component with enabled set to false.

Does not happen when you create the scene element from an HTML template containing loading-screen="enabled: false"

**Comment by albirrkarim** [comment]
> This is in a React project, but not sure that should make a difference.
> 
> `<Scene loading-screen="enabled:false" />`
> 
> Has no effect.
> 
> I cannot disable the loading screen.
> 
> * A-Frame Version: 0.9.0
> * Platform / Device: Windows 10/ Chrome 72

You must pass params as an object, Its work for me

`<Scene
            embedded
            vr-mode-ui={{ enabled: false }}
            cursor={{ rayOrigin: "mouse" }}
            loading-screen={{ enabled: false }}
        >`
