### ISSUE TITLE
Cursor event being fired on Sphere even when the Sphere is not in the view.

### ISSUE THREAD

**Issue by aj019** [aframevr/aframe#4055]
**Description:**

- A-Frame Version: 0.9.0
- Platform / Device: Chrome Browser
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/chalk-bird?path=index.html:13:62

But the problem is solved by either making the radius of the sphere <= 1 or by making the sphere one sided. Is there any explanation for such behaviour ?

**Comment by ngokevin** [comment]
This can be resolved by using `<a-entity>` vs `<a-sphere>` or delaying the adding of event listener a tick. I suspect the asynchronous nature of primitive tags such as `<a-sphere>` is causing it to be first positioned at 0, 0, 0 before the position tag kicks in. The workaround is easy enough to mark as a wontfix since I sort of consider primitive tags to be second-class citizens in the world of A-Frame. Thanks for filing!
