### ISSUE TITLE
[webVR] slow controller movement Daydream chrome >=73 Android ( testing with laser controls) 

### ISSUE THREAD

**Issue by arpu** [aframevr/aframe#4099]
very slow movement of the controller movements on android Daydream 

tested with:
https://a-frobot.github.io/aframe/examples/test/laser-controls/   (aframe master) 
https://aframe.io/aframe/examples/test/laser-controls/  ( aframe v0.9.0 ) 

chrome android version 73 with enables webvr flag 
very slow movements of the controller in vrMode

chrome android 72 with enables webvr and gamepad extention flag 
works fine

**Comment by dmarcos** [comment]
Chrome WebVR / WebXR implementations are going through tons of breaking changes at the moment. Until the dust settles I recommend using Firefox or Supermedium on desktop.

**Comment by arpu** [comment]
WebVR will still be updated in Chrome for Windows mixed reality native implementation

**Comment by arpu** [comment]
open a chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=946277

**Comment by arpu** [comment]
@dmarcos   why is the gamepade polling trottle to 500ms ? ( see chrome bug information) 
https://github.com/aframevr/aframe/blob/master/src/systems/tracked-controls-webvr.js#L15

**Comment by dmarcos** [comment]
That's the frequency to query for connected devices. Not the frequency to get the pose and input state.

**Comment by dmarcos** [comment]
Thanks for the clarification. We will adjust accordingly

**Comment by dmarcos** [comment]
@billorr-google @arpu FWIW, slow update reproduces for me too with the samples in Chrome m73 (release channel): https://webvr.info/samples/XX-vr-controllers.html

**Comment by billorr-google** [comment]
We have to communicate flag and behavior changes better... sorry.

For M73, there is a bug in our gamepad polling - there is code that checks if gamepad state changed, and only updates if it changed, but webvr state like pose wasn't included, so effectively you have to move axes or buttons to get updates.  This was fixed late to merge for a feature behind a flag.

For M75, WebVR and WebXR are behind flags still.  However, for hardware support OpenVR/Oculus are still behind flags and Windows Mixed Reality is now default on.  Part of the reason we can enable this is the ability to run devices in a limited sandbox for security, which OpenVR and Oculus don't currently support, but WMR does.  Net effect, for OpenVR/Oculus you now have to explicitly disable the "XR device sandboxing" flag.

**Comment by ngokevin** [comment]
Is there an alternative to needing to poll every tick? I think the snapshot thing works okay on normal web since buttons are clicked once in a while and you can check buttons on demand.

But for querying pose, it's going to happen like 90 frames per second. Calling `getGamepads()` that many times produces a lot of memory garbage resulting in possible GC pauses and framedrops. I believe Firefox does not have issues with reusing the gamepad reference, is it possible for Chrome to do the same at least for VR pose?

**Comment by billorr-google** [comment]
I lean towards trying to make sure WebXR doesn't suffer problems with many small object creation.  For WebXR, there is a gamepad object obtained from XRInputSource, and the gamepad object doesn't expose poses, so the object could be reused over multiple frames.

In practice, I think this isn't a major concern in Chrome (the GC now does multithreaded and incremental marking, and doesn't need to stop the world for most collections).  In any generational garbage collector, the temporary objects like per-frame gamepad data should be quickly cleaned up and wouldn't live long enough to influence the slower older generation collection.  Its definitely worth measuring to ensure GC doesn't cause issues, but my guess is it won't.

For continuing to keep WebVR working, since there is a Chrome-specific branch in the a-frame code already, calling getGamepads and using the resulting list every frame instead of just calling it and ignoring the result should be fine.

In any case, I'll follow up in the Chrome bug (https://bugs.chromium.org/p/chromium/issues/detail?id=946277) to discuss possible Chrome changes with gamepad owners.

**Comment by arpu** [comment]
works now after #bcedcd3
