### ISSUE TITLE
gltf-model System not registering Draco path

### ISSUE THREAD

**Issue by idrumgood** [aframevr/aframe#4100]
**Description:** When attempting to use the new draco compression gltf-model System on a scene, the attribute is removed/not available during the System's `buildData` call.

In the linked reproducible code, open inspector, cmd+P and find `aframe-master.js`. Set a breakpoint at line 74220 and refresh the sandbox. See that when the System is initialized, all other attributes appear on the `this.sceneEl` including the `test-attribute` but the `gltf-model` attribute is not present. As such, the Draco path is never instantiated and the model fails to load.

`components:gltf-model:warn THREE.GLTFLoader: No DRACOLoader instance provided.`

Note: the path provided does not actually point to the Draco files, but it never actually consumes it so that is not the issue

- A-Frame Version: 0.9.0
- Platform / Device: Chrome/MacOS
- Reproducible Code Snippet or URL: https://codesandbox.io/s/zlxq1374wx

**Comment by donmccurdy** [comment]
I'm not very familiar with React, but as far as I can tell the `gltf-model` scene configuration is never added to the scene at all, while it needs to be there before the model is loaded.

It might be worth trying to use https://github.com/supermedium/aframe-react – it works around various issues combining A-Frame and React, although I couldn't say specifically what's causing the problem here.

**Comment by idrumgood** [comment]
This seems to be related to react specifically, not a-frame in general. Closing.

**Comment by devhims** [comment]
Hi @idrumgood, were you able to resolve this issue?

**Comment by idrumgood** [comment]
@devhims Sorry, it's been too long for me to have access to any of this code or remember if/what the solution was.
