### ISSUE TITLE
Cursor component allocates via setAttribute in onMouseMove

### ISSUE THREAD

**Issue by brianpeiris** [aframevr/aframe#4157]
**Description:**

Noticed this while optimizing my own code. The `cursor` component calls `setAttribute` continuously in `onMouseMove` which leads to some GC: https://github.com/aframevr/aframe/blob/master/src/components/cursor.js#L217 

Not sure how bad this is in the scheme of things, but it seems like an easy one to optimize away.

**Comment by ngokevin** [comment]
Could be improved slightly by setting raycaster origin / direction directly and updating raycaster component's internal `data` object. But not too major since mouse cursor used only in 2D mode, only one mouse cursor per scene, and only one `.setAttribute` per mouse move tick. I believe skipping `.setAttribute` advantages are more on saving CPU cycles than GC now, I think I've mostly removed dynamic memory allocation in most cases.

**Comment by brianpeiris** [comment]
Makes sense, I agree this is probably low impact. Feel free to close the issue if you like.
