### ISSUE TITLE
zlib not supported for NRRDLoader

### ISSUE THREAD

**Issue by kmilo9999** [aframevr/aframe#4213]
NRRDLoader from three.js (THREE.NRRDLoader().load )  requires Zlib which is not supported by super-three. 

Uncaught ReferenceError: Zlib is not defined
    at THREE.NRRDLoader.parse (NRRDLoader.js:296)
    at Object.onLoad (NRRDLoader.js:21)
    at XMLHttpRequest.<anonymous> (three.js:34675)

- A-Frame Version: master
- Platform / Device: windows
- Reproducible Code Snippet or URL: 

in aframe\src\lib\three.js  add:

require('super-three/examples/js/loaders/NRRDLoader');  // THREE.NRRDLoader
THREE.NRRDLoader.prototype.crossOrigin = 'anonymous';

Then in a component:

 new THREE.NRRDLoader().load( "../../models/nrrd/stent.nrrd", function ( volume ) { ..
}

**Comment by dmarcos** [comment]
It's not an A-Frame or a `super-three` issue. I don't recommend using the optional THREE loaders through npm since they're tailored to the examples. Copy, paste and serve `NRRDLoader` in your application. ezlib is a dependency that you will also have to serve or bundle. See [THREE example](https://github.com/mrdoob/three.js/blob/53143d58402fe78b137d222927c1d7ed800900a5/examples/jsm/loaders/NRRDLoader.js#L11) for the hardcoded route or modify to match your application.
