### ISSUE TITLE
wasd-controls flies for tens of meters during framedrops with a single key press.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#4241]
**Description:**

When wasd-controls became independent of frame rate, the behavior during frame drops worsened to flying at high-speeds across the world.

**Comment by ntamas** [comment]
I think the problem is in the incorrect handling of the `scaledEasing` multiplier in [this commit](https://github.com/aframevr/aframe/commit/4b25cecfddb37d7b4c01ee815b635e2d1d1ee736). 

The code refers to [this post on Stack Overflow](https://gamedev.stackexchange.com/questions/151383/frame-rate-independant-movement-with-acceleration). In the SO post, the `scaledEasing` value is calculated the same way as here, but then it is simply applied as a multiplier to the current velocity to implement exponential decay. This seems to be the mathematically correct way for me to treat deceleration due to friction. However, the code in A-Frame effectively multiplies the current velocity with `1 - scaledEasing` -- which means that if `delta` is sufficiently large (as it is after significant frame drops), we do not decrease the velocity at all (contrary to the expectation that it should decrease a lot due to friction).

I have fixed the code according to the SO post in my copy of `wasd-controls` because I also wanted to use the C/E keys for changing the altitude (just like the walkthrough navigation in 3DSMax), and it seems to work better.

**Comment by ntamas** [comment]
Furthermore, the current code has another problem that manifests itself when the browser schedules a new frame in quick succession to another frame (probably because it tries to compensate for a frame drop). In Firefox, on a Macbook with an integrated Intel Iris Pro, it often happens on my machine that two new frames are rendered in less than 3 msec after a longer frame drop (~100 msec), which brings `scaledEasing` very close to 1. The net effect is that the velocity suddenly drops to near-zero, which is definitely not what we want.

**Comment by dmarcos** [comment]
Please share your fix

**Comment by ntamas** [comment]
PR sent. I did not include my additional changes that implement movement along the Y axis with E/C as that is currently outside the scope of `wasd-controls`. I can prepare and submit that as a separate PR if it is a good idea to extend `wasd-controls` with additional functionality.
