### ISSUE TITLE
very poor performance with Vue

### ISSUE THREAD

**Issue by SeregPie** [aframevr/aframe#4311]
In version 0.9 it is nearly impossible to use A-Frame with Vue. Check the reproduction link below. But it worked great back than in 0.8.
0.8 https://codepen.io/SeregPie/pen/pooKwaZ works great
0.9 https://codepen.io/SeregPie/pen/YzzvQzK works poorly
What did change?

- A-Frame Version: 0.9.2
- Platform / Device: Chrome
- Reproducible Code Snippet or URL: https://codepen.io/SeregPie/pen/YzzvQzK

**Comment by eyexpo-dan** [comment]
Tested on both Firefox and Chrome. No issue on Firefox, but I see the mentioned issue on Chrome. Weird.

**Comment by richardtallent** [comment]
At first glance, it seems to be a problem of order of execution of the scripts... AFRAME is not defined when Vue initializes. Have you tried doing this in a webpack environment rather than directly using script tags?

That said, I have no actual experience with aframe -- I just landed here when looking for a simpler way to work with WebXR in my VueJS app than directly interacting with WebGL.

**Comment by SeregPie** [comment]
Looks like AFRAME 1.0 fixed the issue.
