### ISSUE TITLE
No Magic View On Chrome Mobile

### ISSUE THREAD

**Issue by Bobbyf90** [aframevr/aframe#4314]
**Description:**

Hello I am very new to coding but I created a VR 360 image gallery on glitch using a A-frame 0.7.0 base.

When I open the app on mobile chrome the camera automatically moves as I move the mobile. Which is perfect, BUT

I changed the code to A-frame version 0.9.2 and now when I open the app it does not have magic view and even if I press the screen to give it a gesture it does not go into magic view unless I go into the split screen VR button.

I have enabled WebVR in chrome flags.

Thank you for any input please speak in basic terms for me I am very very new.

- A-Frame Version: 0.9.2
- Platform / Device: Chrome / Mobile
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
FWIW, A-Frame examples work fine for me on a Pixel 3 with Chrome 78 without WebVR enabled. I recommend disabling WebVR since the [API has been deprecated in favor of WebXR](https://www.androidpolice.com/2019/11/01/chrome-beta-79-enables-webxr-api-by-default-opening-door-to-more-web-based-ar-vr-experiences/). Also notice that Google has [discontinued Daydream viewer and Cardboard and won't be supported in Pixel 4 and newer phones](https://www.engadget.com/2019/10/15/google-daydream-view-smartphone-vr-pixel-4/?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAKdoyCXsn36i6nZySoFwAyrCfzk1euaoKS7yS4cQTuhJJ2MvQa-6p1cDTXrxrfXKZbMH9QPyH_J69ahZlFAP3ZmuH3wb_bdgyuoiAHfOSeaPVIlM_piGy98IQaQu-dsD3E0nHGI_5Css7C2o9zYtwAPF8oC9pNugD13fGOQqNdJo).  You can start playing with WebXR today with [a-frame master](https://cdn.jsdelivr.net/gh/aframevr/aframe@df3e8672b77568845e5e360f54f4456fd4829a38/dist/aframe-master.min.js) and Chrome Beta after enabling WebXR on chrome://flags. Make sure you're serving content over https

**Comment by Bobbyf90** [comment]
Thanks. Disabling WebVR did in fact fix it, although controversial to previous advice. So im guessing my app that is based on WebVR Aframe is going to break when this WebXR is coming out? Or can I convert it at the time?

**Comment by dmarcos** [comment]
@Bobbyf90 WebXR is already supported on [master](https://cdn.jsdelivr.net/gh/aframevr/aframe@df3e8672b77568845e5e360f54f4456fd4829a38/dist/aframe-master.min.js). Applications will have to update (to master now or next release version expected when WebXR stabilizes) or they will break. At the moment there's still a bit of churn on the WebXR standard and Chrome Beta / Canary are the only browser implementations. Glitches like the one you're seeing are expected until the dust settles. Sorry for the inconvenience.
