### ISSUE TITLE
Enable "auto" logarithmicDepthBuffer only when EXT_frag_depth supported

### ISSUE THREAD

**Issue by kfarr** [aframevr/aframe#4398]
Issue: some devices exhibit artifacts with `logarithmicDepthBuffer` = `true` on the scene renderer when WebGL extension `EXT_frag_depth` is not supported by the device.

Impact: undesired artifacts, especially for objects close to the camera

Instead: if scene renderer attribute logarithmicDepthBuffer = auto, set this renderer setting logarithmicDepthBuffer true only if EXT_frag_depth extension is supported.

***

Psuedo code suggestion, starting here:
https://github.com/aframevr/aframe/blob/67d568c263173ef0a56efc1e0d9e08a6f2d2d2a8/src/core/scene/a-scene.js#L609

```
// Existing logic
if (rendererAttr.logarithmicDepthBuffer && rendererAttr.logarithmicDepthBuffer !== 'auto') {
  rendererConfig.logarithmicDepthBuffer = rendererAttr.logarithmicDepthBuffer === 'true';
}

// Additional logic
if (rendererAttr.logarithmicDepthBuffer == 'auto' && renderer.extensions.get('EXT_frag_depth') !== null) {
  rendererConfig.logarithmicDepthBuffer = rendererAttr.logarithmicDepthBuffer === 'true';
}
```

**Comment by dmarcos** [comment]
We have a renderer component that might include the flag: https://aframe.io/docs/1.0.0/components/renderer.html#sidebar

**Comment by dmarcos** [comment]
Oh I see. Maybe a new flag is not necessary?

**Comment by kfarr** [comment]
Correct, it seems like auto is actually treated as false

**Comment by jbaicoianu** [comment]
The tricky part is that it is possible to use logDepthBuf without EXT_frag_depth, it's just that there are certain degenerate cases which can only be solved with the extension. If your scene is crafted in such a way that it avoids very large polygons, it's perfectly reasonable to use logDepthBuf on hardware that doesn't support EXT_frag_depth.

My general thinking on this topic is, if you can get your scene to work ok without logDepthBuf (by tweaking the camera's near/far parameters) or with (by sufficiently tesselating your polygons), you're better off doing one or the other, rather than having logic to switch between the two based on device capabilities.

**Comment by jbaicoianu** [comment]
I'm not sure what aframe's default near/far parameters are, but the "near" parameter is actually just as if not more important than the "far" parameter - having it set down in the .01 unit range means the range of precision is "wasted" on nearby objects, and distant objects start to flicker.  If your camera isn't meant to go so close to objects, often bumping the near plane up a bit can make a world of difference.

Gets even trickier if you're using WebXR though, since in that case the near/far parameters are specified by the HMD, and I'm not actually sure what happens in that case.

**Comment by kfarr** [comment]
I suppose you're right, this "magic" auto behavior really isn't that useful for general cases.

So really what I proposed is more of a short-term hack and shouldn't be promoted behavior in A-Frame. Best to close this then and look for better solution

**Comment by jbaicoianu** [comment]
One trick I've had success with in the past using regular depth buffer is to dynamically update your near/far parameters based on the contents of the scene, and their distance to the player.  Normally the type of z-fighting you're dealing with in your scene is only visible when you zoom out, in which case the default near parameter is unnecessarily small.  The closest object to the camera may be 10s or 100s of meters away so precision of 1cm isn't necessary.
