### ISSUE TITLE
Canvas texture not updating on Oculus Browser with https

### ISSUE THREAD

**Issue by bgarciadenali** [aframevr/aframe#4457]
I have an animated 2D canvas being rendered and I'm using it as a texture in my A-Frame scene. This no longer works in the Oculus Browser when using https in VR mode. It works if I use regular http but I get a warning each time that it needs https to get access to the sensors. It works properly in Firefox on Quest.

https://www.tacolamp.com/aframe/

- A-Frame Version: 1.0.4
- Platform / Device: Oculus Quest

**Comment by dmarcos** [comment]
Phaser render loop is based on `requestAnimationFrame` that doesn't fire when WebXR is engaged. It used to work on Firefox because it has not yet transitioned to WebVR. To use Phaser in VR you have to drive the render loop via a component and the [tick method](https://aframe.io/docs/1.0.0/core/component.html#tick-time-timedelta). I'm not familiarized with Phaser but there should be a render / update function you should be able to call in the tick method instead of using Phaser default render loop that as I mentioned won't work in VR. There's nothing actionable on the A-Frame side.
