### ISSUE TITLE
DeviceMotion dialog does not work in WKWebView from framework

### ISSUE THREAD

**Issue by cloke** [aframevr/aframe#4508]
**Description:**

When using aframe inside a WKWebView the aframe dialog that requests permissions for motion access does not work as addressed by this ticket https://github.com/aframevr/aframe/issues/4287

If I run `DeviceMotionEvent.requestPermission()` directly in the javascript that is rendered by WKWebView then the native permissions request will show as expected and access is granted and then the aframe dialog shows as well. 
 
Ideally the framework would test for WKWebView or have a setting to use the required native request. 

- A-Frame Version: 1.0.3
- Platform / Device: iPhone / iOS 13+ (maybe older)
- Reproducible Code Snippet or URL:

This is the code that will request the native dialog, but then the user is presented with the aframe dialog and the native dialog:

```    
DeviceMotionEvent.requestPermission()
      .then(response => {
        if (response == "granted") {
          window.addEventListener("devicemotion", e => {
            console.log(e.acceleration)
          });
        }
      })
      .catch(console.error); ```

**Comment by dmarcos** [comment]
Sorry. Not sure if I understand the problem. A-Frame [already calls requestPermission](https://github.com/aframevr/aframe/blob/master/src/components/scene/device-orientation-permission-ui.js#L50) and the dialog is show because permission has to be granted via user gesture. Is the WebView policy any different?

Consider disabling the builtin dialog if you want to handle differently: https://aframe.io/docs/1.0.0/components/device-orientation-permission-ui.html#properties_enabled

**Comment by cloke** [comment]
This may be a bug in WKWebView as it now appears to be random as to when it will work and when it does not work. My current solution is to invoke the permissions request before the app even loads the view so that it is already granted to the app before UIKit renders anything. Going to close as this seems more an iOS issue and not aframe.
