### ISSUE TITLE
Thumbstick Up/Down/Left/Right Events for Oculus Controller

### ISSUE THREAD

**Issue by d0nd3r3k** [aframevr/aframe#4585]
**Description:**

The current Thumbstick implementation doesn't handle all events, most notably the Analog axis of the Thumbsitck. 

- A-Frame Version:
- Platform / Device:
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
Notice that `thumbstickdown` and `thumbstickup` don't refer to the direction but if the thumbstick is pressed or release since it also acts as a button. Listen to the `thumbstickmoved` event to track the direction. I added an [example to the documentation](https://github.com/aframevr/aframe/blob/master/docs/components/oculus-touch-controls.md#read-thumbstick-values) with a component that logs the thumbstick direction. [Runnable version](https://glitch.com/edit/#!/desert-jewel-candy?path=index.html%3A15%3A70)

**Comment by d0nd3r3k** [comment]
This is extremely helpful, thank you for adding that to the documentation!
