### ISSUE TITLE
Controller examples all broken in Oculus Quest Browser

### ISSUE THREAD

**Issue by lynnhu** [aframevr/aframe#4606]
**Description:**
Trying to play with the controller examples in Oculus Quest but they are all broken. I'm guessing it's because all of them are using older versions of A-Frame which didn't support Oculus Quest. For example A-Painter is still using 0.7.0.

I am trying to decide whether to build something with A-Frame and Oculus Quest is one of the most popular headsets. The controller tracking in newer versions is probably working fine, but having working examples on the website would be really helpful for my decision! Thanks.

- A-Frame Version: 0.7.0
- Platform / Device: Oculus Quest
- Reproducible Code Snippet or URL: https://github.com/aframevr/a-painter

**Comment by dmarcos** [comment]
Correct, A-Painter has not yet been updated to A-Frame 1.0.4. Still on 0.7.0 that doesn't support WebXR but the old and now deprecated WebVR. 

A-Frame 1.0.4 works well on Oculus Quest. See the following examples:

https://aframe.io/aframe/examples/showcase/tracked-controls/

https://aframe.io/aframe/examples/test/laser-controls/

For a more elaborate full application see https://moonrider.xyz/

Let me know if you have any problems and we can reopen the issue.

**Comment by Fasani** [comment]
**Oculus Quest 2 and A-Frame** 

Sorry to add to an old thread, but finding this post made my day. I nearly gave up because I thought "a-frame does not work with Oculus Quest 2".

Let me explain:

I tried many of the demos on https://aframe.io using the Oculus Browser, and they do not work. But I discovered that If I open the iframe's for each demo, then they mostly work.

2 example experiences:

This works:
https://moonrider.xyz
![com oculus browser-20211120-193708](https://user-images.githubusercontent.com/448410/142737617-66b7167f-ec50-4b13-8312-40ad2a9ee78c.jpg)

This does not:
https://aframe.io/examples/showcase/moonrider/
![com oculus shellenv-20211120-193614](https://user-images.githubusercontent.com/448410/142737645-4fb14b45-b23a-4a15-8cba-d7e2561a81bb.jpg)

This is true for many demos. I think it could make sense to add a link to exit the a-frame site wrapper to try out the demos?

Is this a known issue? Perhaps I overlooked a note somewhere.

**Comment by cybernetic-research** [comment]
I just started with aframe for the oculus quest2. It looks to me like you either have head tracking like in the older versions, and no motion control, or in the newer versions you just have the desktop experience shown in a small browser with some hand control but no head tracking. Are there any examples of any simple working oculus quest2 demos with hand controlelr and head tracking?

**Comment by Fasani** [comment]
@cybernetic-research you saw the moonrider link above? This works for me from the Quest2 home browser.

**Comment by dmarcos** [comment]
@cybernetic-research Make sure you're using A-Frame 1.2.0. One of the examples with motion controls:

https://aframe.io/aframe/examples/test/laser-controls/

code:

https://github.com/aframevr/aframe/blob/master/examples/test/laser-controls/index.html

**Comment by cybernetic-research** [comment]
I just tried that with node express. It works you get head tracking and pointer control. - Thanks. Can I read the direction thumb stick and buttons so I can move my camera around too?  
    On Sunday, 28 November 2021, 01:15:28 GMT, Diego Marcos ***@***.***> wrote:  
 
 


@cybernetic-research Make sure you're using A-Frame 1.2.0. One of the examples with motion controls:

https://aframe.io/aframe/examples/test/laser-controls/

code:

https://github.com/aframevr/aframe/blob/master/examples/test/laser-controls/index.html

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dmarcos** [comment]
Yes you can read the dumb stick and buttons values by listening the [corresponding events listed in the docs](https://aframe.io/docs/1.2.0/components/tracked-controls.html#events_axismove)

If you still need help I recommend [joining the Slack / Discord channels or ask questions on Stack Overflow](https://aframe.io/community/). Nice folks there to help. We use Github for bug reports and feature requests. Best of luck.

**Comment by cybernetic-research** [comment]
Thanks - Im only just starting to learn Aframe, after having just recived an oculus quest2. I can see that Aframe is an awesome framework and has lots of potential. I had no idea such experiences were possible in a web browser. 
    On Wednesday, 1 December 2021, 00:30:51 GMT, Diego Marcos ***@***.***> wrote:  
 
 


Yes you can read the dumb stick and buttons values by listening the corresponding events listed in the docs

If you still need help I recommend joining the Slack / Discord channels or ask questions on Stack Overflow. Nice folks there to help. We use Github for bug reports and feature requests. Best of luck.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AlexanderKozhevin** [comment]
https://aframe.io/a-painter/ not working as expected on oculus quest 3s right now
brush not working, even though I can see menu around controllers

**Comment by vincentfretin** [comment]
@AlexanderKozhevin that hosted a-painter is really old indeed still using aframe 1.3.0, it doesn't work on Quest 2 or 3 either. Look at https://github.com/aframevr/a-painter/pull/279 for a working version. @dmarcos you should merge that PR.
