### ISSUE TITLE
Black screen above the webcam

### ISSUE THREAD

**Issue by chhamza** [aframevr/aframe#4625]
**Description:**

- A-Frame Version: 0.8.0
- Platform / Device: Web, Android, iOS

a-scene is working fine with Vue but it has black screen above the webcam

![sof](https://user-images.githubusercontent.com/28686382/84763896-2f016b00-afcd-11ea-9dce-2bdcdd3ccc3b.PNG)

**Comment by dmarcos** [comment]
You're on an old version of A-Frame. Make sure you're using 1.0.4

**Comment by chhamza** [comment]
> You're on an old version of A-Frame. Make sure you're using 1.0.4

I tried with all the versions but problem still remains

**Comment by dmarcos** [comment]
Issue is sparse in details. Is the webcam view render as part of the a-frame scene? Outside? Without simple code to reproduce is hard to help

**Comment by chhamza** [comment]
yes it's part of the a-frame scene. In all the browsers behaviour is same whether its chrome or safari, android or iOS. Without vue its working fine. I did it in angularJS too, its working fine with it. 

Here is the simple code:

<a-scene embedded arjs='sourceType: webcam;'>
      <a-assets>
            <a-asset-item id="tree" src="Bee.glb"></a-asset-item>
      </a-assets>
      <a-marker preset='bee'>
             <a-entity 
                  scale="0.05, 0.05, 0.05" position="0,0,0" rotation="0, 0, 0" gltf-model="tree" material="color: #A52A2A">
             </a-entity>
      </a-marker>
  <a-entity camera>
  </a-entity>
</a-scene>

**Comment by dmarcos** [comment]
This looks like a Vue integration issue that I have no experience with. You will be more likely to get help over [Stack Overflow](https://stackoverflow.com/questions/tagged/aframe). Nice folks there. A link with code to reproduce will help people help you. https://glitch.com/~aframe is nice because people can easily suggest fixes. I'm closing this because we we use github issues for bugs and feature requests.
