### ISSUE TITLE
<a-sky>images are flipped 

### ISSUE THREAD

**Issue by lchthanhth615** [aframevr/aframe#4657]
**Description:**

- A-Frame Version:1.0.4
- Platform / Device: PC Chrome Browser
- Reproducible Code Snippet or URL:

I used the API 0.7.0 for my application but when I upgraded to use version 1.0.4. I see the images are flipped horizontally 

This is sky image in ver 0.7.0
![version 070](https://user-images.githubusercontent.com/26566815/88626933-ae5a8200-d0d5-11ea-8f56-48d5f53ba637.PNG)

This is sky image in ver 1.0.4:
![Version 104](https://user-images.githubusercontent.com/26566815/88626937-b1557280-d0d5-11ea-9b66-0d72df601fd0.PNG)

Please show me how to fix it

**Comment by lchthanhth615** [comment]
I found one solution from Stackoverflow: https://stackoverflow.com/questions/51485783/a-sky-only-display-image-with-sideback
to using  scale="-1 1 1"
But how can I make it as default as 0.7.0 version. Currently, it's not only a-sky face this issue but also the videos are flipped when playing.

**Comment by dmarcos** [comment]
`a-sky` in 1.0.4 shows images correctly. It's older versions that did display the wrong orientation. You can see one of the A-Frame examples:

https://aframe.io/aframe/examples/boilerplate/panorama/

that loads the following image:

https://aframe.io/aframe/examples/boilerplate/panorama/puydesancy.jpg

In your case you can use the scale as you pointed out or flip the image horizontally in your favorite photo editor. Closing this because I don't think there's any action to be taken on the A-Frame side.
