### ISSUE TITLE
Aframe 1.0.4 Lag in Firefox Browser Both Mobile and Desktop

### ISSUE THREAD

**Issue by albirrkarim** [aframevr/aframe#4679]
### Description

I'm trying the A-Frame demo in the Mozilla Firefox browser both mobile android and desktop Linux.

use gyroscope or pinch gesture to look around, still have lag. 

I don't know why this happens, 
I use google chrome, safari, Samsung internet, Microsoft edge it works fine, no lag
Maybe there's something wrong in Mozilla firefox memory allocation and graphic rendering

### - A-Frame Version:

Aframe 1.0.4
### - Platform / Device:

**Device Asus Zenfone Max Pro m1**

Mozilla Android version 80.1.3

Specification:
CPU 8 Core
RAM 3 GB
Android 9 

**Lenovo g40-45**

Mozilla Desktop 79 

Specification:
RAM: 4GB
CPU: AMD A4
Xubuntu 20.04

### - Reproducible Code Snippet or URL:
https://aframe.io/

**Comment by dmarcos** [comment]
FWIW, Firefox doesn't lag on my Windows 10 laptop. It looks like a Firefox issue since other browsers work as expected. Some ideas:

1. Try Windows 10 and compare performance.
2. Firefox might be using integrated graphics instead of the discrete GPU in your laptop.  You can control this on Windows (I don't know the Linux equivalent) by locating Firefox in the `NVidia Control Panel` -> `Manage 3D Settings` -> `Program Settings` and select `High-performance Nvidia processor` in `Select the preferred graphics processor for this program`

I don't think there's anything actionable on A-Frame side. We can reopen if necessary.
