### ISSUE TITLE
3D Model (gltf) not loading at Location

### ISSUE THREAD

**Issue by Gaurav-chopra** [aframevr/aframe#4695]
Hi,

I have used the code as written in your blogpost of location based AR. I have changed the location as per Google Lat Long address. When i launch the webapp, the text appears properly at the location but the 3d model is not visible. Please let me know if i have missed something.

 Below is my code
`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>GeoAR.js demo</title>
    <script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
    <script src="https://unpkg.com/aframe-look-at-component@0.8.0/dist/aframe-look-at-component.min.js"></script>
    <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js"></script>
  </head>

  <body style="margin: 0; overflow: hidden;">
    <a-scene
      vr-mode-ui="enabled: false"
      embedded
      arjs="sourceType: webcam; debugUIEnabled: false;"
    >
      <a-text
        value="This content will always face you."
        look-at="[gps-camera]"
        scale="50 50 50"
        gps-entity-place="latitude: 21.1396932; longitude: 72.766791;"
      ></a-text>
      
      <a-entity gltf-model="./assets/magnemite/scene.gltf" rotation="0 180 0" scale="0.15 0.15 0.15" gps-entity-place="latitude: 21.1396932; longitude: 72.766791;" animation-mixer></a-entity>
      <a-camera gps-camera rotation-reader> </a-camera>
    </a-scene>
  </body>
</html>`

**Comment by dmarcos** [comment]
- The [syntax of the gltf-model is not correct](https://aframe.io/docs/1.0.0/components/gltf-model.html#sidebar):

```
 <a-entity gltf-model="url(/path/to/tree.gltf)"></a-entity>
```
- Make sure your model loads in the [gltf-viewer](https://gltf-viewer.donmccurdy.com/)
- Read the [guide on how to load assets](https://aframe.io/docs/1.0.0/introduction/faq.html#why-does-my-asset-e-g-image-video-model-not-load)
- Make sure you can load the model without the `gps-entity-place` component.

If none of the above works I recommend opening a question in [Stack Overflow](https://stackoverflow.com/questions/tagged/aframe) sharing runnable code on glitch https://glitch.com/~aframe

Closing this since we use github issues for bugs and feature requests. Good luck.
