### ISSUE TITLE
error about dependent - Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by OORaiser** [aframevr/aframe#4701]
**Description:**

- A-Frame Version: v1.0.4
- Platform / Device: Chrome v85 on MacOS Catalina
- Reproducible Code Snippet or URL:
```
<!DOCTYPE html>
<html lang="en">
<head>
<script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
<script type="text/javascript">
AFRAME.registerComponent('test-dependency', {schema: {type: 'vec3'}});
AFRAME.registerComponent('test-component', {dependencies: ['test-dependency']});
</script>
</head>  
<body>
<a-scene>
  <a-entity id="target" test-component></a-entity>
</a-scene>
<script type="text/javascript">
setTimeout( () => {
  var target = document.getElementById('target');
  var parent = target.parentElement
  parent.removeChild(target);
  parent.appendChild(target);
}, 3000)
</script>
</body>
</html>
```
above would raise the exception
```
core:a-node:error Failure loading node:   TypeError: Cannot read property 'constructor' of undefined
    at extendProperties (aframe.min.js:903)
    at i.callUpdateHandler (aframe.min.js:903)
    at i.updateProperties (aframe.min.js:903)
    at HTMLElement.updateComponent (aframe.min.js:895)
    at HTMLElement.updateComponents (aframe.min.js:895)
    at aframe.min.js:895
    at aframe.min.js:899
```

[some analysis](https://github.com/n5ro/aframe-physics-system/issues/159#issuecomment-703022959) by @Galadirith

**Comment by dmarcos** [comment]
Can you provide a link with core to reproduce? Glitch is great https://glitch.com/~aframe

**Comment by OORaiser** [comment]
> Can you provide a link with core to reproduce? Glitch is great https://glitch.com/~aframe

https://aframe-error-dep-demo.glitch.me/

**Comment by dmarcos** [comment]
[There are no issues with the component dependency](https://glitch.com/edit/#!/orchid-truth-chameleon?path=index.html%3A18%3A14). The problem comes from removing / reattaching an existing entity. It's an expensive operation and reinitializing components is messy. Most won't get it right. We discourage the approach and we recommend operating at the [THREE.js level if you want to change the hierarchy](https://stackoverflow.com/a/52322043/717508). I don't think there's anything actionable on the A-Frame side.
