### ISSUE TITLE
Use `requestPointerLock` to hijack mouse

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#471]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Thursday Sep 10, 2015 at 23:34 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/120_

----

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Wednesday Dec 02, 2015 at 05:38 GMT_

----

Is this something we still want to do?

**Comment by ngokevin** [comment]
I think https://github.com/alexrkass/aframe-no-click-look-controls is the best solution, but we can track in #848

**Comment by cvan** [comment]
If alexrkass/aframe-no-click-look-controls#1 is not addressed, I'm not sure. not sure why there are haters, but honestly Pointer Lock is without a doubt the best way to give users a great experience and control (you enable and disable Pointer Locks controls when you want to). anything else is unpredictable and/or annoying.

especially when there's other content on the page I may want to click on, I don't want my mouse movements to be hijacked. it's just awkward and too prescriptive.

the only gotcha is that the Pointer Lock API requires a user-initiated event to happen.

anyway, I filed [an Asana ticket](https://app.asana.com/0/89423211979120/95168600485666) for me to file a Firefox platform bug about changing the Pointer Lock API permissions UX.

I'd suggest either keeping this issue open or addressing alexrkass/aframe-no-click-look-controls#1. I'd prefer the former because I think Pointer Lock would be a nice feature to have with A-Frame out of the box.

**Comment by ngokevin** [comment]
There's https://github.com/aframevr/aframe/issues/848 to do this

**Comment by cvan** [comment]
ah, okay - I missed that
