### ISSUE TITLE
Dragging on computer and mobile is not aligned

### ISSUE THREAD

**Issue by antoninklopp** [aframevr/aframe#4716]
**Description:**

- A-Frame Version: 1.0.4
- Platform / Device: Mobile / Desktop
- Reproducible Code Snippet or URL:

I think that [this change](https://github.com/aframevr/aframe/pull/3761/files) that was made quite sometimes ago misaligned behaviors on Desktop and Mobile. 
Now dragging from left to right in a scene does not have the same dragging direction on Desktop or Mobile which is surprising in my opinion. 

Is this expected?

**Comment by dmarcos** [comment]
The commit pointed should not have changed the default behavior.

- [Example with 1.0.4](https://glitch.com/edit/#!/steadfast-sparkling-pancake)
- [Example with 0.9.2](https://glitch.com/edit/#!/vast-leeward-celsius?path=index.html%3A7%3A49)

Dragging direction is intentional. Mobile and desktop expectations are different:

- On desktopndragging follow conventions of 3D games and applications. Mouse moves the camera.
- On mobile your finger moves the world as people got used from maps and photo gallery applications.

If convention doesn't work for your users you can use [the look-controls flags you mentioned](https://aframe.io/docs/1.0.0/components/look-controls.html#properties_reversemousedrag)

**Comment by antoninklopp** [comment]
Thanks for this explanation @dmarcos 

The commit pointed has been introduced in the 0.9.0 release if I am not mistaking.
If I take an example with version [0.8.2](https://glitch.com/edit/#!/noisy-smoggy-minute?path=index.html%3A7%3A63) the behavior is the opposite.

**Comment by dmarcos** [comment]
As mentioned you have control over the panning direction with the [look-controls properties](https://aframe.io/docs/1.0.0/components/look-controls.html#properties_reversemousedrag)
