### ISSUE TITLE
Git commit hooks mistakes class name as a undefined variable

### ISSUE THREAD

**Issue by Elettrotecnica** [aframevr/aframe#4721]
Dear all,

I commit on an own fork of aframe and to my great pleasure I have realized you have introduced git hooks to check quite a few coding standards. I try to abide by them in the remote case one of my fiddlings might end up in a pull request.

However, if one has a boolean expression in their file such as:

`if (this.data.src instanceof HTMLMediaElement) {
   // do whatever
}`

this gets flag as a undefined variable. There might be workarounds for this, but as IMO the idiom is perfectly fine, I prefer to inform you. Of course one can just skip the check, but I am not sure how this would play out in the CI pipeline...

All the best

**Comment by dmarcos** [comment]
In the context provided, `HTMLMediaElement` is referring to `window.HTMLMediaElement`. Referring to the global scope implicitly is error prone since another variable with `HTMLMediaElement` name could be defined in the function scope breaking your code. The linter protects against those cases.

You can refer to the global scope explicitly by doing `window.HTMLMediaElement` and the linter will stop complaining
