### ISSUE TITLE
loading 3d model

### ISSUE THREAD

**Issue by thaotran9** [aframevr/aframe#4731]
When I loaded with a 3d model, the lighting inside the model is dark, do you have a solution to fix that?

**Comment by dmarcos** [comment]
Try `<a-scene renderer="colorManagement: true;">` It it still doesn't work I recommend opening a question on [StackOverflow](https://stackoverflow.com/questions/tagged/aframe) providing the model and simple code to reproduce preferably with [Glitch](https://glitch.com/~aframe). Otherwise it will be hard to help.

I'm closing. We use Github issues for bug reports and feature requests. Good luck
