### ISSUE TITLE
Arjs cannot work in immersive mode

### ISSUE THREAD

**Issue by ericdacal** [aframevr/aframe#4746]
- A-Frame Version: 1.4
- Platform / Device: Magic Leap 1

I'm developing a app with Arjs and Magic Leap 1, when I use Image Tracking in inline mode works well but when I use in immersive mode cannot works. The code use is the following:
```html
<!DOCTYPE html>
<html>
  <script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
  <!-- we import arjs version without NFT but with marker + location based support -->
  <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js"></script>
  <body style="margin : 0px; overflow: hidden;">
    <a-scene embedded arjs>
      <a-marker preset="hiro">
        <a-entity
          position="0 0 0"
          scale="0.05 0.05 0.05"
          gltf-model="https://arjs-cors-proxy.herokuapp.com/https://raw.githack.com/AR-js-org/AR.js/master/aframe/examples/image-tracking/nft/trex/scene.gltf"
        ></a-entity>
      </a-marker>
      <a-entity camera></a-entity>
    </a-scene>
  </body>
</html>
```

**Comment by dmarcos** [comment]
I don't have a Magic Leap 1 to test with and [ar.js](https://github.com/AR-js-org/AR.js) maintainers will be better equipped to answer your questions. Your problem is likely not an issue with A-Frame but related to how `ar.js` is architected.

As far as I know `ar.js` is designed to work in magic window mode where the camera feed is rendered in a `<video>` element as the page background. In immersive mode only WebGL content is rendered. 

For Magic Leap I suppose you want to replace the camera feed with the real world view. I don't think `ar.js` accounts for that use case or it's tested in head mounted devices. I encourage contacting `ar.js` folks. It will help them investigate if you also provide a browser console log since Magic Leap 1 devices are not easily available.

I don't think there's anything actionable on the A-Frame side. Good luck with your project
