### ISSUE TITLE
Using any component with tracked-controls as a dependency will prevent generic-tracked-controller-controls from functioning

### ISSUE THREAD

**Issue by fordacious** [aframevr/aframe#4770]
generic-tracked-controller-controls will not set its data if there is already a tracked-controls component present. This means that any component that adds tracked-controls will cause generic-tracked-controller-controls to not function (e.g. vive-controls, thumb-controls, haptics)

**Comment by dmarcos** [comment]
That's intentional. `generic-tracked-controller-controls` has the lowest priority. 

Only active if there are no other controls available. Vendor specific controls take precedence.  If `vive-controls`, `oculus-touch-controls` are defined and active (because there's an inputSource with associated vender profile) `generic-tracked-controller-controls` won't do anything. `aframe-thumb-controls` and `aframe-thumb-controls` should not depend on `tracked-controls` but listening to `controllerconnected` event. It looks [thumb-controls](https://github.com/supermedium/superframe/blob/master/components/thumb-controls/index.js#L59) does it already `partially`

**Comment by dmarcos** [comment]
Fix for this should be on https://github.com/supermedium/superframe/blob/master/components/thumb-controls/index.js#L59

**Comment by dmarcos** [comment]
I think there's nothing to be done on A-Frame side. Closing and can reopen if necessary.
