### ISSUE TITLE
Animations don't occur when the same animation is requested twice in a row.

### ISSUE THREAD

**Issue by diarmidmackenzie** [aframevr/aframe#4810]
**Description:**

If you invoke the same animation twice in a row, the 2nd time, it does not occur, and does not trigger an animationcomplete event.

See example here:
https://successful-giddy-chime.glitch.me/

One use case this severely impacts is where an application tries to chain a series of animations together, using the animationcomplete event to trigger the next animation.  When the animationcomplete event does not occur, this leads to a complete blockage of the chain of animations.

The reason for the problem appears to be that when the value set on the animation component is unchanged, the update method of the animation component doesn't get called by A-Frame, so the animation component is never invoked at all for the duplicate animation request.

While in general it makes sense not to invoke update functions when properties are unschanged, in this specific case, it's perfectly reasonable for an application to want to trigger the same animation twice in a row, and so the animation component *should* be invoked in this case.

One workaround which I have tested, and works, is to add a tiny additional delta to the animation duration (I used a random float between 0 & 1).  While this has no practical impact on the animation duration, it's enough to cause A-Frame to call the animation component's update function, and everything seems fine from that point on.

- A-Frame Version: 1.2.0
- Platform / Device: All
- Reproducible Code Snippet or URL:
https://successful-giddy-chime.glitch.me/

It is possible that this issue was the cause of what was reported here: https://github.com/aframevr/aframe/issues/3806

However the code linked to in that issue is no longer available, so it's not possible to confirm that this was in fact the same problem.

**Comment by kylebakerio** [comment]
Responded on slack, copying here:

kylebaker.io  5 minutes ago
I think I know why this is happening

kylebaker.io  5 minutes ago
basically, you're setting exactly the same values

kylebaker.io  5 minutes ago
when that happens, no update is performed, it doesn't run again

kylebaker.io  4 minutes ago
this is true of any component--the 'update' method is only called when the 'newData' isn't the same as the 'oldData' .

kylebaker.io  3 minutes ago
so if you add this line `          this.el.removeAttribute('animation')`
to the top of your animateRotation method, it works fine. See:
https://abstracted-perfect-sunset.glitch.me/

kylebaker.io  1 minute ago
this 'feature' of components helps them run performantly when they're getting dozens of update calls per frame, not updating when they get identical input. But they does mean that sending values to a component is not like calling a pure function and getting an idempotent result.

**Comment by diarmidmackenzie** [comment]
Agree your workaround is better than mine & simple to apply.

The issue here is that it's not obvious that this is necessary, and so the API sets a nasty trap for the user.  The workaround may only take a minute to apply, but I lost a couple of hours trying to figure this out.

My code that generates the animations is non-trivial, so doesn't necessarily know in the moment whether it's sending a repeat of a previous rotation.

Sure, you can clear out the rotation in advance in all cases, but if that's what's required to use the API, then at a minimum it should be covered in the API docs, and it would be much better to have a usable API that didn't require this at all.

**Comment by kylebakerio** [comment]
I'm seeing double. I'll stop responding in slack and just respond here now, since this is the location of record. ;)

But I agree that's a valid point, it is a silent unexpected behavior for new users, and it would be nice if there were some way to help new devs catch this without learning it the hard way. It does mean that an 'update' call isn't analagous to a 'pure' function in a sense, which is a nice quality to have. But I think in VR world, it is the right optimization to make, and is a nice feature. It's mostly a question of communicating that API to devs. Not sure how that can be done--we don't want something that helps make the code more performant--sometimes substantially--"opt-in", since users may not discover it and have less performant code by default. We can try to make it more obvious in the docs, but lots of people won't go looking in there until they need to.

Do you have a proposal on how to improve this?

The only thing I can think of is that it might be nice to have a 'verbose mode' for A-Frame. In that verbose mode, it could log when it drops an update, I guess.

Outside of that, I'm not sure how to improve this without making some other sacrifice, unless just updating the docs is sufficient. (The docs are on github, so you can make a pull request at any time if you see a way to improve them.)

**Comment by dmarcos** [comment]
Not sure if I fully understand the issue. Just read on passing. Animations only either `autoplay` or are triggered by events. You can [add an event to startEvents](https://aframe.io/docs/1.2.0/components/animation.html#api_startevents) and emit it on the entity when you want to restart the animation e.g: `el.emit('fireanimation')`

**Comment by diarmidmackenzie** [comment]
The issue I see her is that the animation component uses an idempotent API (applying the same operation twice has no effect) to offer a service that is fundamentally not idempotent.

If I request the same animation twice, I would expect to see 2 animations, not one.  I think that's what all users of the interface would natrually expect.

So the only good solution I see is to allow this interface (as an option) to operate in a mode that is not idempotent, where every call to setAttribute results in an update to the component.  The animation component could make use of this option.

That seems to point to what you suggested before: an extension to the component API to allow components to declare that they always want to see updates.

I've never looked at the internals of A-Frame before, but it looks to me like a fairly minor addition here should be enough...
https://github.com/aframevr/aframe/blob/965dd23c7e7fbe272a9c120d88d4ccee2e0a8200/src/core/component.js#L407

(plus the code to manage the setting of the new attribute by components).

I don't think there'd be any perf impact, since the new behaviour would only be enabled for a small number of components (like animation) that don't want an idempotent interface.

Do you think there are circumstances where users of the animation component value the interface operating in idempotent mode?  Would there be a need to maintain the legacy idempotent behaviour for the animation component?  I would hope we could eliminate it.

**Comment by diarmidmackenzie** [comment]
@dmarcos just saw your comment (last post was in response to @kylebakerio).

The scenario I hit this was in chaining together a series of animations.  I was waiting for one to complete, then starting the next one (always using autoplay) on the animationcomplete event.

In almost all cases, this worked fine.  Setting the animation attribute triggered the start of the animation.

The only time this didn't work was when the next animation triggered happened to be identical to the last one (which, in my code, happened unpredictably).  In this case nothing happened, and I never got the animationcomplete event.

Net result was that individual animated elements in my scene would freeze permanently, seemingly at random.  I spent a lot of time looking for bugs in my own code before finally realizing that the lock-ups occured whenever the same animation occurred twice in a row.

So the issue is that the API appears to work in a way that allows you to start an animation by setting the animation attributes, but then fails to work in this way consistently.

Does that help clarify my concern?

**Comment by diarmidmackenzie** [comment]
This fix addresses the problem (I have tested locally and it fixes the glitch I linked to above).

https://github.com/aframevr/aframe/compare/master...diarmidmackenzie:duplicate-animation-fix

I doubt this is the right fix (I suspect adjusting oldData from within the component is an interface violation), but could we do something along these lines?

I'd also want to think more carefully about:
- exactly what circumstances to do this in.  Is non-looping autoplay animations the right subset?
- exactly when to do it?  when beginning the animation?  or should we wait until the animation is completed?

But could a fix along these lines be a viable option?

**Comment by dmarcos** [comment]
Just to fully understand. Triggering an event in the entity (after setting the new animation values) would cover your use case?

```
 <a-entity animation="startEvents: triggeranimation,...; ..."></a-entity>

 // In your JS.
 entityEl.setAttribute('animation', {... new values ...});
 entityEl.emit('triggeranimation');

```

**Comment by kylebakerio** [comment]
When the animation component receives the same input twice, it doesn't do anything the second time--including not firing an 'animation complete' event (which it shouldn't, I think, since it didn't do the animation). @diarmidmackenzie expects to see an `animation complete event` after every call to animation, and when he didn't get one because he called the same animation twice, it broke his code.

There are many easy possible workarounds for his particular case, but he wants the unpredictable api to change. He points out that if pass params to the animation component, you expect an animation to occur. You don't expect the last params you passed to affect whether the next params will do anything.

Personally, I think this just means that the animation component isn't ideal for his use case, and that he should instead make his own copy of the animation component. That's the 'aframe way'. But I also can understand where he's coming from, it's a reasonable point of confusion.

**Comment by diarmidmackenzie** [comment]
@dmarcos - yes, not using autoplay & triggering an event manually works fine as a workaround.  So does removing the attribute before setting it.

@kylebakerio has summed up my concern well.  This is not about making my application work.  It's about this component presenting an API that behaves in a clear and consistent manner.

Making a copy of the animation component for my purposes would not solve the problem because (a) I don't need to: I can easily work around the issue in my own code, and (b) the mainline animation component would still be out there with its problematic API.

One more attempt at characterising the problem with the API...

By offering autoplay of finite duration announcements, the animation component provides a behaviour that is fundamentally event-like, but using an API that is idempotent, and hence well-suited to managing states but not events.

- Looping animations are state-like, so the idempotent API works well for them.
- Finite animations are event-like.  When autoplay is not used, they are controlled using events, and so there are no problems.
- When finite animations are triggered by autoplay, you have an event-like behaviour controlled through an API that's intended for controlling states.  That's when problems arise.


Solutions I can see are:
1. Break idempotency on the API in the case of finite, autoplay animations.
2. Remove support for autoplay of finite animations, and insist on an event to start them.

1. is hacky, but seems to cause minimal inconvenience.  2 is a much cleaner solution, but creates inconvenience and non-back-compatible interface change.

Other option of course is 3: leave things as they are, ad document.  Adding an explicit section explaining how to set animations using setAttribute might be a useful addition, and would provide a good place to put this content...

**Comment by kylebakerio** [comment]
I hear you, but the thing is:

- We shouldn't change the component API, because its default behavior makes sense. A-Frame has chosen to prioritize performance over simplicity/purity, and that makes sense because of A-Frame's goals. Can this confuse people who don't yet realize that components are not pure functions? Yes, but that's just the developer's task--learning the API they are working with, learning that a component is not a function, etc. Setting attributes on a component is not the same as calling a function. If it were, what would be the point of components? They exist specifically to give a tailored execution pattern that works for A-Frame's goals. _In other words, the confusion here is the result of mistaken assumptions._

- You might argue that animations shouldn't be handled within a component, then. Thing is, the history of animations in A-Frame involves a few iterations of different concepts before the modern standard was selected. It makes sense for most use cases. If you want something that behaves differently, you're free to not rely on the built-in animation component and spin off a variation that works for you. As you are aware, there are also ways to easily work around this issue.

- The final alternative would be a 'flag' to change this behavior. But I might ask at that point, what difference it makes? It's still going to catch the same developers making the same assumptions off guard until they find and learn about the flag. Meanwhile, switching that flag is not going to be any easier than the other workarounds that are also one-liner changes. In effect, it doesn't solve any problems, but causes the API of A-Frame to get just a little bit bigger--one more little thing to maintain, document, and know. Not a big deal, but A-Frame seems to prioritize being no bigger than necessary. 

- Subpoint to that last one, you might argue that there should be a flag, but the default state should be the behavior that is idempotent. That would be (a) not matching the component api, and (b) not defaulting to high-performance behavior, which is a critical concern for a VR-centered library.

So, my $0.02, "It's about this component presenting an API that behaves in a clear and consistent manner", this goal is already met. You just needed to learn an important detail of the component API and update cycle. The animation component follows exactly what every other component does, which is how it should be. But it's only offered for convenience--you can always modify it, work around it, expand it, fork it, or work with the underlying animation library directly if desired.

That said, as I have said before, I agress it's not the smoothest possible developer experience. It's incredibly user friendly when you consider that you're animating in 3d space on a cross platform codebase with barely any code in a pretty intuitive, predictable way that mostly just works, but there is still some room for "DX"/developer experience improvement here.

But I think the A-Frame way would be to build out an alternative animation component that you think is better, and then lobby for it to replace the built-in if you think appropriate. Either way, you can offer it as an alternative yourself for anyone else to include.

(Also, to be clear, I'm not an A-Frame maintainer, I'm just playing devil's advocate and sharing my thoughts.)

**Comment by diarmidmackenzie** [comment]
@kylebakerio - thanks for taking the time to write up your thoughts.

Having reflected on this, I agree that for aimation to deviate from the standard idempotent behaviour on setAttribute would lead to a different kind of inconsistency, which could be just as problematic and confusing.  That rules out option 1 that I had suggested.

With hindsight, IMO, it was not a good idea to have offered autoplay of non-looping animations via component attributes - it would have been much better to have insisted on an "event" trigger to start all non-looping animations, which would have avoided 

But the interface has been offered, and it would cause a lot of hassle to remove this function now.

So I think the best way forwards is probably just to document the pitfall here.  I will work on a PR for that.

(unless @dmarcos wants to advocate for a different approach, having caught up on this discussion).

**Comment by dmarcos** [comment]
Thanks @diarmidmackenzie I agree we should at least document. Thanks so much for the PR. It's supper appreciated.

**Comment by diarmidmackenzie** [comment]
I think we can close this now.  Managed to hit this *again* today... fortunately I remembered this issue after only about 15 mins of trying to figure out what was wrong with my code.
