### ISSUE TITLE
Init called on system not included in scene

### ISSUE THREAD

**Issue by EPurwanto** [aframevr/aframe#4837]
**Description:**
The init lifecycle method is called on systems that are registered in AFRAME, regardless of whether they are included in the scene or not. 

I'm using a common library of components across a few different scenes, and the library includes systems that are only applicable to a handful of scenes. The init method should only be called on those systems that are attached to the a-scene element.

- A-Frame Version: 1.2.0
- Platform / Device: tested on latest versions of Chrome and Firefox.
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/ancient-even-trust

**Comment by dmarcos** [comment]
That's expected behavior. Systems are global services initialized at scene load and to be available for when components need them. I don't know the particularities of your use case. One solution could be to makin your systems as lazy as possible. `init` method is lightweight or even empty and heavier initialization happens when the component services are used.

**Comment by EPurwanto** [comment]
So there's no difference between this:
`AFRAME.registerSystem("some-system", {});
<a-scene some-system></a-scene>`

and this:
`AFRAME.registerSystem("some-system", {});
<a-scene></a-scene>`

That feels wrong to me, that you can't have a system that is available but not in use. Would be good if the documentation mentioned this somewhere. But ok, I can work around it.
