### ISSUE TITLE
The vive-controls component does not detect all kinds Vive controllers

### ISSUE THREAD

**Issue by juliusikkala** [aframevr/aframe#4846]
**Description:**

- A-Frame Version: 1.2.0 (& master branch as well)
- Platform / Device: Chrome 89 & HTC Vive Pro on Windows 10 w/ SteamVR 1.16.10

I have these dark blue Vive controllers which were bundled with the HTC Vive Pro. The first entry of XRInputSource.profiles for them is just `htc-vive`, not `htc-vive-controller-mv` as the vive-controls component expects after #4348. This results in the controllers not being detected by that component. I can write a pull request fixing this, but I would need to know the preferred approach before doing so.

The easiest fix would surely be to just change it back (and make hand-controls do its test using startsWith instead of ===). Since the change was made, I assume that some controllers report themselves as `htc-vive-controller-mv`. It looks like reverting `GAMEPAD_ID_WEBXR` back to `htc-vive` should match those too, but is there a future-proofing decision behind the change (if HTC decides to add completely different controllers with a profile like `htc-vive2` or something)? So should `GAMEPAD_ID_WEBXR` be an array of acceptable exact profile names instead of just one value? That solution would probably be very tedious as it would affect all other controllers too due to the way `findMatchingControllerWebXR` would have to be modified for exactness.

**Comment by dmarcos** [comment]
Thanks, For a while Chrome reported Vive controllers incorrectly as `htc-vive-controller-mv` instead of `htc-vive` as stated in the [WebXR profiles](https://github.com/immersive-web/webxr-input-profiles/blob/main/packages/registry/profiles/htc/htc-vive.json#L2). It seems the bug has now been fixed. I replaced the id to match the one in the WebXR profile. Could you give it a quick try using one of the [master builds](https://cdn.jsdelivr.net/gh/aframevr/aframe@ece0b6509adc60a73718f1ee94d7eb84de232413/dist/aframe-master.min.js)? I don't have access to a Vive at the moment. Thanks!

**Comment by juliusikkala** [comment]
The build you linked works! Thanks!
