### ISSUE TITLE
documentation: Warn against arrow functions in components.

### ISSUE THREAD

**Issue by ccrraaiigg** [aframevr/aframe#4857]
If one uses an arrow function for the init() method of a component, then "this" will be bound to the window, not the component. This would be a good thing to mention in the documentation. Thanks!

**Comment by dmarcos** [comment]
Is not that Javascript general knowledge?

**Comment by dmarcos** [comment]
it’s the same for any component function

**Comment by dmarcos** [comment]
I believe this problem is not specific to A-Frame and it's beyond the scope of the docs. Javascript developers should know the scoping differences between regular and arrow functions. The issue is not limited to the `init` method. We would have to add a note to any function / method where A-Frame expects a regular function. I'm closing this for now but can reopen if necessary. Thanks for filing.
