### ISSUE TITLE
Hand Tracking mesh broken

### ISSUE THREAD

**Issue by kylebakerio** [aframevr/aframe#4918]
**Description:**
Using hand-tracking-controls with default values produces a disturbing warped hand mesh.

- A-Frame Version: 1.2.0
- Platform / Device: Quest 2, oculus browser v91, quest software version 32.
- Reproducible Code Snippet or URL: https://hand-track.glitch.me/

Maybe by a recent oculus browser update? I'll file an issue, here's a glitch showing it. Just open in quest and put your controllers down and wave your hands in front of your face.

Also, note that setting `modelStyle: dots` works nicely, still. 

I noticed that the models referenced in the A-Frame source code look correct when I open them in blender, but the models in [this repo](https://github.com/marlon360/webxr-handtracking/tree/master/models) (that is seemingly out of date) seem 'sideways' when I open them in blender:

however, in quest, they look sideways, so... I wondered if those might compensate somehow correctly...? But it doesn't seem like there's any obvious way to get them to work. I went as far as making my own local version of the component, but just was not able to get those models to load either. 

![hands-twisted](https://user-images.githubusercontent.com/6391152/131261770-62b7b3be-e896-447f-966e-52cc84c0cab5.png)

a picture of what those 'other' hand models look like from marlon360's repo (which I can't get to show at all, and probably isn't relevant):
![l_hand_blender_import](https://user-images.githubusercontent.com/6391152/131261779-e3b8e09b-452b-4bf6-81ae-81889fa4a4ae.png)

**Comment by dmarcos** [comment]
Have you tried master? https://cdn.jsdelivr.net/gh/aframevr/aframe@5fba101050ece59ff57daa9539592ede0adfbf05/dist/aframe-master.min.js

**Comment by gftruj** [comment]
With this (https://cdn.jsdelivr.net/gh/aframevr/aframe@5fba101050ece59ff57daa9539592ede0adfbf05/dist/aframe-master.min.js) i get a black screen and:

> The XRSession has completed multiple animation frames without drawing anything to the baseLayer's framebuffer, resulting in no visible output.

I guess the dots are working properly because only the orientations changed twisting the joints.

<hr>

I've copied the [hand-tracking-controls](https://github.com/gftruj/aframe-hand-tracking-controls-extras/blob/master/dist/oculus-hand-controls.js) and for whatever reason - they're working fine:


![241056612_5009858312362251_739896969972346064_n (1)](https://user-images.githubusercontent.com/17348360/131570389-57461b46-b657-4f7d-83be-227faad2fb71.jpg)

[website](https://gftruj.github.io/hand.tracking.controls.extras/examples/hands.html)([source](https://github.com/gftruj/aframe-hand-tracking-controls-extras/blob/master/examples/hands.html) - [oculus-hand-controls](https://gftruj.github.io/hand.tracking.controls.extras/dist/oculus-hand-controls.js) is my copy.)
On the right is my copy, which shouldn't be working fine..... since it should be the same code??? 😵‍💫 

@kylebakerio I wonder if get the same results.

**Comment by dmarcos** [comment]
Try this build https://cdn.jsdelivr.net/gh/aframevr/aframe@b78a9f4552e01d2cd933f26b07a223c43007a97c/dist/aframe-master.min.js

**Comment by kylebakerio** [comment]
https://user-images.githubusercontent.com/6391152/131690649-ec8164ed-0926-4e6f-81bf-148e0a03abd5.mp4

same result as you, piotr.

**Comment by kylebakerio** [comment]
@dmarcos that build works perfectly for me in my app. Nice!
