### ISSUE TITLE
AFrame, click and SpeechSynthesisUtterance

### ISSUE THREAD

**Issue by irwinwilliams** [aframevr/aframe#4939]
**Description:**
When I try to get speech synthesis, it fails on iOS.

- A-Frame Version: 1.2
- Platform / Device: iOS
- Reproducible Code Snippet or URL: https://invincible-purrfect-shoemaker.glitch.me/

If you go to the above URL, it will have a play button that onclick plays a sound across chrome on windows and iOS. But when I try to keep using SpeechSynthesisUtterance, it works on Chrome on Windows but not on iOS. The subsequent sounds that get played are triggered on click of a component. 
Some research I did seems to point to a limitation in iOS: "The problem is that the iOS would not let the speech API run programmatically unless we have triggered one time under the user's interaction" - [From StackOverflow](https://stackoverflow.com/questions/32193704/js-speech-synthesis-issue-on-ios)

So, is it that component click events aren't considered "true" expressions of user interactions?

**Comment by dmarcos** [comment]
No, synthetic events like those fired by the cursor component are not consider gestures. List of that [constitute a gesture](https://stackoverflow.com/questions/56388258/what-constitues-user-gesture). You can add an HTML button on screen (it looks you already have a `play` button) that the user taps / clicks. In the event listener you can enable SpeechSynthesisUtterance (sorry not familiar with it). Closing this because there's nothing to do on A-Frame side. Best of luck!
