### ISSUE TITLE
Can't move camera in A-Frame with Oculus Quest 2

### ISSUE THREAD

**Issue by andrejsmelnikovs** [aframevr/aframe#5012]
Is it possible to move camera in A-Frame projects with Oculus touch controllers?

Can't find any working example.

- A-Frame Version: 1.3
- Platform / Device: Oculus Quest 2
- Reproducible Code Snippet or URL: https://aframe-aincraft.glitch.me/ (not working)

I asked this question in StackOverflow, but no one answered me.

**Comment by dmarcos** [comment]
I saw your question on StackOverflow and asked additional information. Also gave you a couple of tips to help you getting started. I recommend share your code with your attempts. It will be much easier to help you and can provide solutions over working code. I'm closing this because we use github bugs for bugs and feature requests. Thanks for understanding. Best of luck

**Comment by dmarcos** [comment]
FYI, the demo you linked. Uses a very old A-Frame version that it's outdated. Make sure you're using A-Frame 1.3.0 (or newer for future readers)
