### ISSUE TITLE
VR mode not working on iOS devices

### ISSUE THREAD

**Issue by tomasbrownnz** [aframevr/aframe#5019]
**Description:**

- A-Frame Version: 1.3.0
- Platform / Device: iPhone 11 Pro - iOS 15.3.1 - Safari (latest)
- Reproducible Code Snippet or URL: [Link](https://aframe.io/aframe/examples/showcase/anime-UI/)

A blank white screen is showing on mobile and tablets trying to access VR mode on personal projects and A-Frame examples. Image shows console logs that are being thrown when this issue is replicated.

![image](https://user-images.githubusercontent.com/18434502/157337811-665ee87a-daa7-493a-a930-c0d9bda6545c.png)

**Comment by rsiqueira** [comment]
I also have this problem (blank screen when using A-FRAME VR mode in iphone).
I see that previous version (e.g. 1.1.0) works, but I need to use the most recent version.
Thanks.

**Comment by EricRorich** [comment]
same problem here http://quantumscans.de/gallery/loewe/loewe.html

**Comment by shabarito** [comment]
AFRAME uses THREE.js WebXRManager or WebVRManager for VR. But as the XR is becoming more acceptable and defined on the browsers, VR is receiving less attention. IOS uses WebVRManager as navigator.xr is not available yet.

On the last AFRAME update (1.3.0) and THREE recent updates some functions became classes. This happened to **EventDispatcher** 
And also, some changes implemented for WebXRManager broke WebVRManager. 

The first error is because EventDispatcher became a class and does not have enumerable methods anymore. Therefore, Object.assign between WebVRManager and EventDispatcher do not work.

To fix it, you can copy the EventDispatcher **function** from an older THREE version and replace it on aframe 1.3.0 . It looks something like this.
<img width="284" alt="image" src="https://user-images.githubusercontent.com/70118897/186531380-e457f42f-dbfb-409d-ad24-fe760fa1b3f4.png">

Or you can replace/add this just after WebVRManager.
<img width="404" alt="image" src="https://user-images.githubusercontent.com/70118897/186555023-006fae94-9747-48db-8641-cfd0f4304411.png">

For the other errors,  **this.render** inside **WebGLRenderer** function was changed.  Noting is being passed to the xr.getCamera function. This leads to the camera errors.

<img width="347" alt="image" src="https://user-images.githubusercontent.com/70118897/186529304-3eb0bdea-0014-4170-a0f5-7dc0c6897074.png">

But, WebVRManager requires the camera on that function.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/70118897/186529457-6ba293d1-1d10-4420-86f3-1f89e19e15d8.png">

Adding the camera on this.render, fixes the problem. And, I believe this change does not break anything else, as  WebXRManager does not use it.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/70118897/186529701-e9c07b9b-6899-4703-a98c-bc1b810af2cb.png">

@dmarcos is this something that can be officially added to allow CDN usage again?

**Comment by vincentfretin** [comment]
@shabarito If you figured out all the changes needed and you have it working, you probably should create a PR to have further discussion on it and have a chance for the changes to be merged.

**Comment by shabarito** [comment]
Thanks @vincentfretin. I am new to GIT.
This was my first PR. I think I did everything correctly.

**Comment by vincentfretin** [comment]
Don't worry, we all did our first PR at one point. :) When you create a PR, it's nice to reference the issue. Here the PR you created is #5102

**Comment by vincentfretin** [comment]
For context, getCamera changed with this commit https://github.com/mrdoob/three.js/commit/ec96437a05b7c3f9f3e64951a9b17f6be6314129

In your fix you're changing the implementation of `WebGLRenderer` https://github.com/mrdoob/three.js/blob/2d9a9f0b546aaf22dc0dcbfe56402bee075b9509/src/renderers/WebGLRenderer.js#L961-L967
I don't think we want to maintain a change in WebGLRenderer, it will be a conflict nightmare for @dmarcos :)
I think you better should do a similar change than WebXRManager in WebVRManager and don't touch WebGLRenderer.

**Comment by dmarcos** [comment]
This has been fixed in master by https://github.com/aframevr/aframe/pull/5102 Can reopen if necessary.
