### ISSUE TITLE
Access this site over HTTPS to enter VR mode and grant access to the device sensors.

### ISSUE THREAD

**Issue by whp22** [aframevr/aframe#5039]
Hello,  I am a newbie at this. What does this mean? 

> Access this site over HTTPS to enter VR mode and grant access to the device sensors.

Thanks

**Comment by msub2** [comment]
Most likely you're either trying to view an HTML file using A-Frame directly (would show as a `file://` link in your browser) or you're viewing it over http. If you're trying to do local development you'll need to have a web server that's either serving it as https or serving it on localhost. There are tools like [http-server](https://www.npmjs.com/package/http-server) that can greatly simplify this process.

**Comment by whp22** [comment]
> Most likely you're either trying to view an HTML file using A-Frame directly (would show as a `file://` link in your browser) or you're viewing it over http. If you're trying to do local development you'll need to have a web server that's either serving it as https or serving it on localhost. There are tools like [http-server](https://www.npmjs.com/package/http-server) that can greatly simplify this process.

I have tried a web server with localhost, which works well. However, when I built a web server with my computer IP (192.168.0.27) instead of localhost ip, the error shows up.

**Comment by dmarcos** [comment]
It's a [browser policy](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts) where browser vendors limit certain APIs to secure origins (https). WebXR / Devicemotion that A-Frame uses are some examples hence the message you see.

localhost is exempt from the policy as you've seen. if you serve to other machines you need to an `https` end point. Options are: host your content on [glitch](https://glitch.com/~aframe) or [github pages](https://pages.github.com/), serve with [ngrok](https://ngrok.com/) or can use [http-server](https://gist.github.com/jakub-g/d3349e8bab99ab7b08fdccf92662a9aa) as mentioned above.

Closing this because there's nothing actionable on the A-Frame side

**Comment by nikolas** [comment]
Is there a way to turn off this message? I am just using A-frame for a browser application, and not using any device sensors.

**Comment by nikolas** [comment]
Nevermind, I figured it out!
```
<a-scene device-orientation-permission-ui="enabled: false">
```
