### ISSUE TITLE
IOs: doesn't show a-entitiy wih patt marker

### ISSUE THREAD

**Issue by profjlmh** [aframevr/aframe#5045]
Im creating a WebAPP using arjs, a-frame. I used marker and a-entity as GLB models. And it works well on PC and Android devices. But when i try to open the webapp on iPhones the camera start but the marker doesn't show up the content.

**Comment by dmarcos** [comment]
For support I recommend using the [Community resources](https://aframe.io/community/) Mainly Discord and StackOverflow. Make sure you share your code with [Glitch](https://glitch.com/~aframe) so people can help you. Best of luck. Closing this since we issue github issues for bug reports and feature requests. Thanks for understaning.
