### ISSUE TITLE
Does aframe support remote rendering?

### ISSUE THREAD

**Issue by whp22** [aframevr/aframe#5054]
Hi, I want to develop an VR game with aframe, which is rendered on a server and displayed on a client, like oculus. I do not know if aframe support remote rendering? Thanks

**Comment by dmarcos** [comment]
Not sure if that would be within the A-Frame scope in particular or WebGL / Web Browser in general. A-Frame uses WebGL underneath and it’s the browser that takes the framebuffer and presents it in the display through whatever runtime is underneath (e.g OpenXR).

I don’t know of anyway you can have a browser runtime that renders your content, sends the frames over the wire and ultimately presents it on the headset. Likely the experience wouldn’t be great due to latency (send sensor input, render and send frame back)
