### ISSUE TITLE
How to control .glb model animations in A-FRAME via Three.js

### ISSUE THREAD

**Issue by Frantz32** [aframevr/aframe#5060]
Hi, I'm trying to play a glb animation in A-FRAME with Three.js.. now it works just for a second and then it stop, could someone help me please? this is my code:
[https://stackoverflow.com/questions/72519879/how-to-control-glb-model-animations-in-a-frame-via-three-js](url)

**Comment by dmarcos** [comment]
For support I recommend using the [Community resources](https://aframe.io/community/) Mainly Discord and StackOverflow. Make sure you share your code with [Glitch](https://glitch.com/~aframe) so people can help you. Best of luck. Closing this since we issue github issues for bug reports and feature requests. Thanks for understanding.
