### ISSUE TITLE
why does my picture keep looking like this

### ISSUE THREAD

**Issue by KingKutt6000** [aframevr/aframe#5066]
why do i keep getting this when i try to open the picture
![Capture coding help](https://user-images.githubusercontent.com/108086011/175351740-7b1c2dbf-339c-424d-9b26-c8e571bd1cdd.JPG)

**Comment by dmarcos** [comment]
Make sure you're using a [local server to host your content](https://aframe.io/docs/1.3.0/introduction/faq.html#why-does-my-asset-e-g-image-video-model-not-load)

For usage questions I recommend [joining the community](https://aframe.io/community/) on Discord or StackOverflow. Nice folks there to help. Closing this because we use Github for bug reports and feature requests. Best of luck and thanks for understanding.
