### ISSUE TITLE
Oculus Quest 2 animations on trigger / grip / button press don't work

### ISSUE THREAD

**Issue by diarmidmackenzie** [aframevr/aframe#5067]
**Description:**

- A-Frame Version: 1.3.0
- Platform / Device: Oculus Quest 2
- Reproducible Code Snippet or URL: Any A-Frame Example that uses controllers.  E.g. https://aframe.io/examples/showcase/responsiveui/

When I press the trigger or grip, the trigger & grip on the controller models as viewed in VR.  Similarly, changes to button colors (as configured via buttonColor, buttonHighlightColor, buttonTouchColor) are not applied.

I hadn't realized this was expected function, but looking at the code in [oculus-touch-controls](https://github.com/aframevr/aframe/blob/master/src/components/oculus-touch-controls.js) there is code to animate the trigger & grip & change colors of buttons.  It looks like it would work for the Oculus Quest 1, but hasn't been updated to work for Oculus Quest 2.

The key bit of code is [here](https://github.com/aframevr/aframe/blob/a7d1154146e915b0e739bcd761457ff9ed097776/src/components/oculus-touch-controls.js#L302-L310), which uses getObjectByName to access the relevant sub-components of the controller 3D model.

I've been looking at the controller models in a GLTF viewer.

the "gen2" model (used for Quest 1) has subcomponents with names that match the code.
![image](https://user-images.githubusercontent.com/16045703/175561716-ff686227-4339-42bf-ab9f-0758664c6349.png)

the "v3" model (used for Quest 2) has a different set of names for the subcomponents (as well as a much more complicated hierarchy).
![image](https://user-images.githubusercontent.com/16045703/175562589-a7f95ba1-0c6a-4538-985b-e6be216c31ba.png)

Because the names don't match, the calls to getObjectByName all fail, and the component has no references in buttonMeshes, for example [here](https://github.com/aframevr/aframe/blob/a7d1154146e915b0e739bcd761457ff9ed097776/src/components/oculus-touch-controls.js#L281-L288) and [here](https://github.com/aframevr/aframe/blob/a7d1154146e915b0e739bcd761457ff9ed097776/src/components/oculus-touch-controls.js#L337-L341)

I haven't looked into what's involved in fixing yet.  It might be a matter of just using the alternate names on the calls to getObjectByName.  Or it's possible that the details of exactly what rotations & position offsets need to be applied also need to be adjusted to reflect the different controller model.

I'd be happy to look at doing a PR to fix this.  I have Quest 2, so I can test that.  I don't have a Quest 1, so I won't be able to regression test live, but should be able to cover with Unit Tests.  Just wanted to check first that you'd be happy to receive such a PR.  And also that the fix should be in the oculus-touch-controls component (rather than e.g. fixing up the v3 model to match the gen2 naming conventions).

**Comment by diarmidmackenzie** [comment]
Lookign at the structure of the v3 controller object, I'm guessing that the _max and _min Object3Ds are intended to provide guidelines for the transforms for the trigger, grip etc as they are pressed.

And therefore these sub-components should be animated by setting the matrix4 of the _value Object3D to a suitable interpolation between the _max and _min matrix4s (which I'm assuming should be treated as read-only).

Interpolation between matrix4s will need to be done by decomposing them into position & rotation (quaterion) and scale (though I assume scale won't change), interopolating each of these components using lerp for position and slerp for quaternions, and composing these into the new matrix4.

I'd propose a fix along those lines.  The gen2 controller model, just uses hard-coded position & rotation updates, but if this additional info is embedded in the model for v3, it surely makes sense to use it (and hopefuilly this will future-proof the implementation for future controller models).

I don't suppose we know of any documentation for the controller models that could confirm my interpretation of the _max, _min and _value object3Ds?

**Comment by dmarcos** [comment]
Thanks so much. It seems the feature was lost as we incorporated more controller. There are no docs for the models unfortunately.

**Comment by kylebakerio** [comment]
Nice work diarmid, I was wondering why animations weren't working and found this issue. Do we know what the source of these controller models are? Were they extracted from somewhere?

Would be cool to see either a new component that supports this controller model or to see an updated model that fits the design expected by the component.

**Comment by diarmidmackenzie** [comment]
I don't know about the source of these, but pretty sure the best path forwards it to update A-Frame to fit the new model format rather than trying to engineer back-compatible models.

I don't think it's a big job, but I've had other things on my plate.  I can see myself getting to this within a couple of weeks.  If you'd like to have a go at this before then, please do!

**Comment by kylebakerio** [comment]
I'm well outside of my realm of expertise, but I started looking through the model design and then took an experimental stab. **I have the trigger and grip buttons working!** As far as I can tell, no interpolation between matrix4's necessary.

The grip button is perfect, and both buttons move in precise increments that match real-world button activation.

That said, the trigger button movement isn't flawless--it looks like the button has the wrong origin, perhaps? Not sure, not my wheelhouse, would love commentary from someone else.

The non-rotating buttons (a/b/x/y) do not move, though that makes sense since I am only applying a rotation transform, will take a stab at correcting them soon.

It looks like the thumbstick x/y rotation capabilities should also be available, the model has some complexity there to facilitate that use, which is very exciting, though I haven't gotten into adding that yet. Pressing it down is not yet facilitated, either.

I will probably play with it more later and try to get it working.

I had thought to make a new component, but since the controller still reports as oculus-touch, I am now thinking it probably makes sense to just update this component to handle the differences for this model. (Where did it come from? It's very well made, surely oculus put this out there themselves?)

You can try the working demo here, which will give the existing component for the right hand and the experimental new component for the left hand: https://basic-tracked.glitch.me/

The main changes are here:

```js
  onModelLoadedV3(evt) {
    var controllerObject3D = this.controllerObject3D = evt.detail.model;
    var buttonMeshes, buttonRanges;

    if (!this.data.model) { return; }    
    
    buttonMeshes = this.buttonMeshes = {};
    buttonRanges = this.buttonRanges = {};

    buttonMeshes.grip = controllerObject3D.getObjectByName('squeeze');
    buttonRanges.grip = {
      min: controllerObject3D.getObjectByName('xr_standard_squeeze_pressed_min'),
      max: controllerObject3D.getObjectByName('xr_standard_squeeze_pressed_max'),
    }
    
    // should maybe use 'min' value instead
    this.originalXPositionGrip = buttonMeshes.grip && buttonMeshes.grip.position.x;
    
    buttonMeshes.thumbstick = controllerObject3D.getObjectByName('thumbstick'); // todo: this one is pretty complex, with x/y stuff, so verify this works
    buttonRanges.thumbstick = {
      min: controllerObject3D.getObjectByName('xr_standard_thumbstick_pressed_min'),
      max: controllerObject3D.getObjectByName('xr_standard_thumbstick_pressed_max'),
    }    
    
    buttonMeshes.trigger = controllerObject3D.getObjectByName('trigger');
    buttonRanges.trigger = {
      min: controllerObject3D.getObjectByName('xr_standard_trigger_pressed_min'),
      max: controllerObject3D.getObjectByName('xr_standard_trigger_pressed_max'),
    }
    
    // should maybe use 'min' value instead
    this.originalXRotationTrigger = buttonMeshes.trigger && buttonMeshes.trigger.rotation.x;
    
    buttonMeshes.xbutton = controllerObject3D.getObjectByName('x_button');
    buttonRanges.xButton = {
      min: controllerObject3D.getObjectByName('x_button_pressed_min'),
      max: controllerObject3D.getObjectByName('x_button_pressed_max'),
    }
    buttonMeshes.abutton = controllerObject3D.getObjectByName('a_button');
    buttonRanges.aButton = {
      min: controllerObject3D.getObjectByName('a_button_pressed_min'),
      max: controllerObject3D.getObjectByName('a_button_pressed_max'),
    }    
    buttonMeshes.ybutton = controllerObject3D.getObjectByName('y_button');
    buttonRanges.yButton = {
      min: controllerObject3D.getObjectByName('y_button_pressed_min'),
      max: controllerObject3D.getObjectByName('y_button_pressed_max'),
    }    
    buttonMeshes.bbutton = controllerObject3D.getObjectByName('b_button');
    buttonRanges.bButton = {
      min: controllerObject3D.getObjectByName('b_button_pressed_min'),
      max: controllerObject3D.getObjectByName('b_button_pressed_max'),
    }    
  },
  ```
  
  and here:
  
  ```js
   updateV3ButtonModel(buttonName, state) {
    console.log("update v3 model", buttonName, state)
    const releasing = (state === 'up' || state === 'touchend') ;
    const touching = state === 'touchstart';
    const depressing = !releasing && !touching;
    const min = this.buttonRanges[buttonName].min;
    const max = this.buttonRanges[buttonName].max;
    console.log(depressing ? "depressing" : releasing ? "releasing" : touching ? "touching" : "N/A")
    if (!touching) {
      console.log("setting new position")
      this.buttonMeshes[buttonName].setRotationFromEuler(this.buttonRanges[buttonName][releasing ? min.rotation : max.rotation]);
    }
    // works: trigger.val.setRotationFromEuler(trigger.max.rotation)
    // max = depressed, min = released
  }
  ```

**Comment by kylebakerio** [comment]
I'm well outside of my realm of expertise, but I started looking through the model design and then took an experimental stab. Some interesting progress.

1. grip works perfectly out of the box utilizing the existing oculus-touch-controls code, just by grabbing the correct mesh.
2. trigger almost works same way, but the rocking is not quite ont he right axis.
3. in the console, working with the model directly, I am able to confirm that that 'max'' and 'min' values do indeed correspond to the correct range. You can use something like this to manually click the button on/off:

```js
buttonMeshes[buttonName].setRotationFromEuler(buttonRanges[buttonName][ /*min || max */].rotation);
```
(this is assuming you use my updated code to grab the correct meshes and ranges, see below for some code you can lightly tweak to do so.)

This seems to me like the matrix4 interpolation shouldn't be necessary. Using this method for the grip also works, but more interestingly using it for hte trigger immediately produces a correct result (unlike the existing code). Just a matter of applying it proportionately to its application.

Thumbstick values are provided in the model as well and should be able to be applied, too, which is pretty cool. In the console, I was also able to move the thumbstick around using a very similar command to the trigger/grip buttons, as above. I haven't gotten a/b/x/y yet, haven't really tried yet.

You can try the working demo here, which has a bunch of gross proof of concept code just to give a sandbox for me to experiment on the model and with how the component might be updated. Only the right hand has the experimental component: https://basic-tracked.glitch.me/

working way of adding the meshes and the provided ranges:
```js
  
  onModelLoadedV3(evt) {
    var controllerObject3D = this.controllerObject3D = evt.detail.model;
    var buttonMeshes, buttonRanges;

    if (!this.data.model) { return; }    
    
    buttonMeshes = this.buttonMeshes = {};
    buttonRanges = this.buttonRanges = {};

    buttonMeshes.grip = controllerObject3D.getObjectByName('squeeze');
    buttonRanges.grip = {
      min: controllerObject3D.getObjectByName('xr_standard_squeeze_pressed_min'),
      max: controllerObject3D.getObjectByName('xr_standard_squeeze_pressed_max'),
    }
    
    this.originalXPositionGrip = buttonMeshes.grip && buttonMeshes.grip.position.x;
    
    buttonMeshes.thumbstick = controllerObject3D.getObjectByName('thumbstick'); // todo: this one is pretty complex, with x/y stuff, so verify this works
    buttonRanges.thumbstick = {
      min: controllerObject3D.getObjectByName('xr_standard_thumbstick_pressed_min'),
      max: controllerObject3D.getObjectByName('xr_standard_thumbstick_pressed_max'),
      x: {
        min: controllerObject3D.getObjectByName('xr_standard_thumbstick_xaxis_pressed_min'),
        max: controllerObject3D.getObjectByName('xr_standard_thumbstick_xaxis_pressed_max'),
      },
      y: {
        min: controllerObject3D.getObjectByName('xr_standard_thumbstick_yaxis_pressed_min'),
        max: controllerObject3D.getObjectByName('xr_standard_thumbstick_yaxis_pressed_max'),
      }
    }    
    
    buttonMeshes.trigger = controllerObject3D.getObjectByName('trigger');
    buttonRanges.trigger = {
      min: controllerObject3D.getObjectByName('xr_standard_trigger_pressed_min'),
      max: controllerObject3D.getObjectByName('xr_standard_trigger_pressed_max'),
    }
    
    this.originalXRotationTrigger = buttonMeshes.trigger && buttonMeshes.trigger.rotation.x;
    
    buttonMeshes.xbutton = controllerObject3D.getObjectByName('x_button');
    buttonRanges.xbutton = {
      min: controllerObject3D.getObjectByName('x_button_pressed_min'),
      max: controllerObject3D.getObjectByName('x_button_pressed_max'),
    }
    buttonMeshes.abutton = controllerObject3D.getObjectByName('a_button');
    buttonRanges.abutton = {
      min: controllerObject3D.getObjectByName('a_button_pressed_min'),
      max: controllerObject3D.getObjectByName('a_button_pressed_max'),
    }    
    buttonMeshes.ybutton = controllerObject3D.getObjectByName('y_button');
    buttonRanges.ybutton = {
      min: controllerObject3D.getObjectByName('y_button_pressed_min'),
      max: controllerObject3D.getObjectByName('y_button_pressed_max'),
    }    
    buttonMeshes.bbutton = controllerObject3D.getObjectByName('b_button');
    buttonRanges.bbutton = {
      min: controllerObject3D.getObjectByName('b_button_pressed_min'),
      max: controllerObject3D.getObjectByName('b_button_pressed_max'),
    }    
  },

```

**Comment by kylebakerio** [comment]
Everything is now working, except

1) applying thumbstick motion correctly
2) modifying button mesh colors

Looking very close!

**Comment by kylebakerio** [comment]
thumbsticks working!

**Comment by kylebakerio** [comment]
Nothing seems to color a single mesh, for some reason--applying color to any mesh seems to apply color to every mesh.

This is not at all my specialty, but it does not seem this is a limitation of the model, as I am able to selectively color this node in babylon's sandbox model viewer:

![image](https://user-images.githubusercontent.com/6391152/186116601-fa3cdf08-00db-436d-b097-dd894fbd7486.png)

In the meantime, I'll work on refactoring this prototype into something cleaner and making a pull request.

**Comment by diarmidmackenzie** [comment]
A threejs geometry can have multiple materials, but the A-Frame material component doesn't support this.

I suspect that's the issue you are hitting.

Whenever I've wanted to do multiple materials on an object I had to hand-code at the three.js level.

I did once look at extending the material component to support multiple materials per-geometry, but it wasn't at all straightforward, and I didn't manage to get a working solution.

**Comment by diarmidmackenzie** [comment]
Great work BTW.  Looks like my initial analysis that this was fairly straightforward may have been some way off the mark!

**Comment by kylebakerio** [comment]
> A threejs geometry can have multiple materials, but the A-Frame material component doesn't support this.
> 
> I suspect that's the issue you are hitting.
> 
> Whenever I've wanted to do multiple materials on an object I had to hand-code at the three.js level.
> 
> I did once look at extending the material component to support multiple materials per-geometry, but it wasn't at all straightforward, and I didn't manage to get a working solution.

I see, that's an interesting detail. Do you have a code sample? Honestly didn't even realize I was working with something A-Frame specific at that point.

**Comment by diarmidmackenzie** [comment]
See e.g. penguin component in this module.

https://github.com/diarmidmackenzie/christmas-scene/blob/main/src/christmas-utils.js

Geometry constructed with 3 groups, and then materials are provided as an array.  A-Frame can't do this.

![Screenshot_20220823-143950-726.png](https://user-images.githubusercontent.com/16045703/186173490-cbc47128-8202-4603-8060-62d0211f0f00.png)

**Comment by kylebakerio** [comment]
@dmarcos not entirely a coincidence, but the reason I started working on this issue / noticed this issue is because I was working on the networked aframe controllers component.

While doing that work, and digging into the controller components, a design issues with these components became a thorn in my side.

What I'm trying to do is pick up events from local controllers, and then send the necessary event information to simulate the same controller model changes (colored button meshes, moving button meshes) and replay those model updates on a networked instance of the controller.

Rather than duplicate the code of all the controller components, which would obviously not be ideal, I have it working by loading up the controller component, but disabling pose tracking for that instance. On `oculus-touch-controls`, injecting the model is done separately from injecting the pose tracking, so it's easy; for older components like `vive-controls`, I have to allow it to inject hte pose tracking alongside the model, and then disable the pose tracking.

I've been using a wrapper around `updateButtonModel()` to grab the arguments fed to it and re-pass them, networked, to the non-local networked instance of the controller to replay the button model updates.

What I now realize is that this only half works, because only half of the model update is done in that function--the color being applied to button meshes. The other update, the rotation/position updates, are done _before_ the event is emitted that triggers these updates, in `onButtonChanged()`.

Basically, it looks like this:


native API event picked up and emitted by `tracked-webxr-controls` 
-> a raw event is picked up and handled in component by `onButtonChanged()`, buttons meshes moved, and it re-broadcasts the event with an added interpreted button name
-> a bound `onButtonEvent()` from AFRAME.utils.trackedControllers is called, but **right here, everything except for button name and start/touch/end is stripped, including analog value used to position/rotate button mesh**
-> onButtonUp/down/touchstart/touchend all call `onButtonEvent` from utils, which calls back into component with 
-> updateModel(), which in this component just calls
-> updateButtonModel() adds colors to the meshes of buttons


The analog value gets stripped out in these event listeners that take it in but do not propogate it, declared in init in oculus-touch-controls:

```js
    this.onButtonDown = function (evt) { onButtonEvent(evt.detail.id, 'down', self, self.data.hand); };
    this.onButtonUp = function (evt) { onButtonEvent(evt.detail.id, 'up', self, self.data.hand); };
    this.onButtonTouchStart = function (evt) { onButtonEvent(evt.detail.id, 'touchstart', self, self.data.hand); };
    this.onButtonTouchEnd = function (evt) { onButtonEvent(evt.detail.id, 'touchend', self, self.data.hand); };
```

It would be nice if all button model/mesh updates were done in buttonModelUpdate(), but to facilitate that, it would be necessary to pass along the `evt.detail.state.value` used as `analogValue` that indicates 'what percent pressed' the given button is. `updateModel` calls the argument it receives "evtName", but `updateButtonModel` mistakenly calls its argument `state` (which may be leftover from a time when this data used to be passed down?).

Any thoughts on passing this analog value along, and moving all controller updates into one function as a standard going forward?

## Alternatively

it might just be simpler to move the updateButtonModel call to happen in the `onButtonChanged()` event. Then the changes would at least be in one place--however, for my purposes, it would be nice if I could update the model with arguments without triggering an event being broadcast, so that users would be able to trust those events without needing to know whether it came from a local controller or not (plus the unnecessary overhead--those controllers emitting events would just be a pitfall that could confuse users, not something anyone would want).

**Comment by kylebakerio** [comment]
Thanks for that tip. Got colors working! Now I'm tempted to go try and fix the A-Frame standard mesh material... Anyways, let's get this done first, haha.

**Comment by kylebakerio** [comment]
Current iteration also fixes colored buttons for all the quest controllers, which have all shared the characteristic of being broken and having all buttons light up when any button is pressed.

**Comment by kylebakerio** [comment]
Pull request submitted:

https://github.com/aframevr/aframe/pull/5103

**Comment by kylebakerio** [comment]
> A threejs geometry can have multiple materials, but the A-Frame material component doesn't support this.
> 
> I suspect that's the issue you are hitting.
> 
> Whenever I've wanted to do multiple materials on an object I had to hand-code at the three.js level.
> 
> I did once look at extending the material component to support multiple materials per-geometry, but it wasn't at all straightforward, and I didn't manage to get a working solution.

Hey @diarmidmackenzie is there an open A-Frame issue for this somewhere?

**Comment by kylebakerio** [comment]
Also, feel free to weigh in on #5103 if you get a chance.

**Comment by diarmidmackenzie** [comment]
No I don't think there is an issue for this.

I'd just seen this as a limitation of the framework that I had learned to work around, and never raised it as an issue.

**Comment by kylebakerio** [comment]
It seems like unexpected behavior to me... Like some kind of optimization, at best, that one should be able to turn off with a flag if desired if nothing else.

**Comment by dmarcos** [comment]
fixed by https://github.com/aframevr/aframe/issues/5067
