### ISSUE TITLE
System crashes while adding about more than 20 spotlights/point lights in a scene. 

### ISSUE THREAD

**Issue by Akhileshpm** [aframevr/aframe#5100]
**Description:**
I was creating a virtual store and it requires about 30+ ceiling lights. At first, I used a js file to add light components in the required positions, then the result came out to be a plane scene where only <a-plane> component existed, so I checked the A-Frame inspector where the layout of lights was seen but not the actual component, not even the walls of the mall that I implemented using <a-box> was visible. Then, I tried adding it manually so after adding more than 13 lights my browser slowed down and my CPU started making loud noises. Can someone suggest a better way of implementing lights in an optimized way? I have shared the link to one similar problem. Thanks.
- A-Frame Version: v1.3.0
- Platform / Device: 16GB RAM, i7
- Reproducible Code Snippet or URL: https://disco-three-parent.glitch.me/

**Comment by dmarcos** [comment]
Real time lights are very expensive and should be used very sparsely. Lighting is a very broad topic in real time 3D graphics. You should look for techniques that approach the style you want to but are cheap resource-wise. This is more of a usage question and out of the scope if Github issues that we use for bug reports and feature requests. I recommend using [Stack Overflow](https://stackoverflow.com/questions/tagged/aframe) or [Discord](https://aframe.io/community/)

FWIW, I didn't see any lights in your glitch example.

Best of luck and closing this because there's nothing actionable on A-Frame side.
