### ISSUE TITLE
new webpack system not working over localhost

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#5131]
`npm start`. I can't do `localhost:9000` on the browser as before. Any ideas @vincentfretin ?

I have to use full local IP `http://XXX.YYY.ZZZ.AAA:9000/`

**Comment by vincentfretin** [comment]
With browserify I got 
```
[0000] info  Server running at http://192.168.1.15:9000/ (connect)
```
but it listened really on both the ipv4 and localhost I didn't know that.

When I switched to webpack, I specified 
https://github.com/aframevr/aframe/blob/2f38f5ac85aa9bfb1f2ffef6527aa90e88aa661d/webpack.config.js#L15-L17
https://webpack.js.org/configuration/dev-server/#local-ip
to have it listen to the ipv4 address only.
so that it matched what I was seeing in browserify, here the webpack console output:
```
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.15:9000/
```

You can remove the `host: local-ip` line and commit it.
Then it will listen to all localhost, ipv4 ipv6:
```
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:9000/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.15:9000/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::bf2a:e5e2:8f9:4336]:9000/
```

Also if you want you can add `open: true` there, it will open the browser just after running `npm start`.
