### ISSUE TITLE
Crash when exiting VR on Master Branch #0fe1f286

### ISSUE THREAD

**Issue by wyzwon** [aframevr/aframe#5137]
**Description:**
Upon exiting VR, I get the following error in the browser console:
Uncaught TypeError: Cannot read properties of null (reading 'removeEventListener') at XRSession.onSessionEnd (three.js:18792:1)
This error leaves the page entirely unresponsive and does not show up in release 1.3.0

- A-Frame Version: Master build #0fe1f286
- Platform / Device: gen 1 HTC Vive / Windows 10 / Steam VR / Chrome 106.0.5249.119
- Reproducible Code Snippet or URL:
Enter VR mode then hit Esc to exit VR. The scene should then become un-responsive.
Any A-frame scene using build #0fe1f286. Such as from:
<script src="https://cdn.jsdelivr.net/gh/aframevr/aframe@c27d4a2156bde2ec249600fca4967ba49fecfdc3/dist/aframe-master.min.js"></script>

**Comment by dmarcos** [comment]
Chrome WebXR support on desktop has had a lot quirks since transition to OpenXR. It would be worth trying on Quest / Oculus browser and see it the issue reproduces consistently.

**Comment by wyzwon** [comment]
I was able to exit VR on the Quest 2 without any fatal crash on both the standalone Quest browser and via a desktop link. I also reconfirmed the issue still persists for the Vive in Chrome version 107.0.5304.88

**Comment by dmarcos** [comment]
Chrome WebXR on desktop has a lot of quirks. Might want to read https://github.com/aframevr/aframe/issues/4709 and add your experience if not covered

**Comment by wyzwon** [comment]
I have narrowed down the introduction of the bug to between c937479ed9f4e70c1cadacc4e14af6a9a82e3cef and d8de4098e6985f604e36002e00bd3b6cc37c8385. The only code changes between these two builds appear to be:

1. An update to wasd-controls (480a303)
2. A super-three bump from 0.137.0 to 0.141.0 (837023c)

I am also confirming that the error still persists in version 1.4.0 running Chrome 108.0.5359.125/Steam VR beta 1.25.2

I did notice that even in older versions, the relaunched game is a little twitchy, but I suspect it's unrelated to the bug at hand.

**Comment by vincentfretin** [comment]
I remember I saw this error on Quest 1 Meta browser sometimes while I was developing. I didn't really care at that time because I just refreshed the page between each VR test. So I don't know if the page was also unresponsive or not in my case.
If you do a build with this change @wyzwon https://github.com/MozillaReality/aframe/commit/0fa14187b8f3e90726385904591eba799380df79 does it fix the issue?

**Comment by vincentfretin** [comment]
My guess is there may be a race condition between the threejs cleanup and aframe cleanup. That's why I don't always see this error.
When I looked at WebXRManager commits history https://github.com/mrdoob/three.js/commits/dev/src/renderers/webxr/WebXRManager.js I didn't see a recent change in r141 related to cleanup as @netpro2k mentioned in the comment.
Also does this `vrManager.setSession(null)` really did something at all? We didn't `await` it, or call `.then()` on it, `setSession` is an async function.

**Comment by vincentfretin** [comment]
https://github.com/aframevr/aframe/blob/fbfb4de0827fc7806706c7508cab4df82601a45a/src/core/scene/a-scene.js#L405-L407

session is set to null after the `end` event here:
https://github.com/mrdoob/three.js/blob/4fa01465053d3d95e5c6e05fee701b1b217878aa/src/renderers/webxr/WebXRManager.js#L262
https://github.com/mrdoob/three.js/blob/4fa01465053d3d95e5c6e05fee701b1b217878aa/src/renderers/webxr/WebXRManager.js#L175

`setSession(null)` is setting `session = null` here:
https://github.com/mrdoob/three.js/blob/4fa01465053d3d95e5c6e05fee701b1b217878aa/src/renderers/webxr/WebXRManager.js#L248-L250

It seems the issue will trigger if `setSession(null)` is called before `onSessionEnd` is called via the `end` event.

But if `onSessionEnd` is already setting `session = null`, we don't even need `setSession(null)` that is just doing  `session = null` too as far as I can tell.

**Comment by vincentfretin** [comment]
I found it, in three r132 `session = null` was added
https://github.com/mrdoob/three.js/commit/daffe80204b1d9153ed0a6b28a13db80197951cd#diff-a27b9d3ba68457069cc8ff521208ae9d0cc6d9256f6f48ada6316fc2d732ba7e
so the `setSession(null)` is not needed anymore.
I created #5198 to fix the issue.

aframe 1.3.0 was using r137 so the issue is not new.

**Comment by dmarcos** [comment]
Thanks @wyzwon for the extra info. it was really helpful

**Comment by wyzwon** [comment]
> aframe 1.3.0 was using r137 so the issue is not new.

Odd, I only get the error report and complete freeze post 1.3.0 though? I will certainly test it post fix though. Thanks for all your work!

**Comment by wyzwon** [comment]
The error is not showing up in 1.4.1 👍

I am still getting a warning (twice each time the XR session ends), but it's clearly a different issue, so I will try to get a new issue report up for it.

Progressive relaunches are also still more and more jittery until the scene stops redrawing entirely, but this appears to be true for [ImmersiveWeb](https://immersiveweb.dev/) demos as well so I suspect it's at least outside the scope of AFrame.
