### ISSUE TITLE
VR button missing on iPhone

### ISSUE THREAD

**Issue by Metricweb** [aframevr/aframe#5236]
Hi there. I wanted to ask why the VR and AR button doesn't appear on the iPhone. I use aframe version 1.4.0
Thank you.

- A-Frame Version: 1.4.0
- Platform / Device: iOS
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
AR button was never available on iOS since Safari doesn't have WebXR AR or VR capabilities. As for the VR button we have deprecated cardboard mode. Experience was not great. Problem became intractable due to the proliferation of screen sizes and different browser policies when it comes to fulllscreen mode.

**Comment by Metricweb** [comment]
Thanks for the reply. Using version 1.0.4 it works on all iPhones I've tried (from 6 to 14) The problem is that when you switch to VR mode the address bar remains visible.

**Comment by dmarcos** [comment]
Yes, remaining bar on Safari is just one of the problems. Fullscreen behavior and policies change continuously. Cardboard usage is down and harder and harder to find holders specially for newer devices / screen sizes. 

If it's something you need the code is still around and you can renable as below but not longer maintained and will be removed in the future

```
 <a-scene vr-mode-ui="cardboardModeEnabled: true"> 
```
