### ISSUE TITLE
It does not automatically switch to VR mode in version 1.4.2

### ISSUE THREAD

**Issue by jhfrek** [aframevr/aframe#5276]
Hi!
It does not automatically switch to VR mode in version 1.4.2. In version 1.0.1, it switched to webview on android, but it does not switch to google chrome. How to make the program switch to VR mode automatically. I have several VR pages and I would like them to automatically get into VR mode when I navigate through the pages.

I have already tried to write in different ways:

<a-scene auto-enter-vr renderer="antialias: true;" background="color: #FAFAFA">
---
var sceneVR = document.querySelector('a-scene');
sceneVR.enterVR(false);
----
AFRAME.registerComponent('auto-enter-vr', {
        init: function () {
          this.el.sceneEl.enterVR();
   }
 });
---
Xiaomi redmi note 10 t
Android 12

https://frill-glaze-bottle.glitch.me
https://glitch.com/edit/#!/frill-glaze-bottle

**Comment by dmarcos** [comment]
You cannot enter VR automatically. This is a constraint of the WebXR standard (not A-Frame) where a user gesture is required to enter immersive mode due to privacy and security policies.

**Comment by roy-mdr** [comment]
I had the same thought... I swear before updating I could navigate between A-Frame pages without exiting VR, but after updating to 1.4.2 after a while I get back to the browser when the new page loads.
However I did a rollback I still the same behavior so maybe my Oculus Quest Browser updated and now it doesn't allow that action.
I guess since its not a standard yet, this function will be inconsistent regardless A-Frame.

**Comment by dmarcos** [comment]
I don't think there's anything actionable here. Closing but can reopen if necessary
