### ISSUE TITLE
What is the difference between renderer and gltf-model in a-scene?

### ISSUE THREAD

**Issue by jiahuamld** [aframevr/aframe#5287]
**Description:**

- A-Frame Version:1.4.2
- Platform / Device: iphone

**Comment by jiahuamld** [comment]
What is the difference between renderer and gltf-model in a-scene?

**Comment by jiahuamld** [comment]
Accept the difference between the two parameters

**Comment by jiahuamld** [comment]
![image](https://user-images.githubusercontent.com/11866846/236380905-78ebc01c-4bcb-4187-bd61-71e98314127b.png)

**Comment by jiahuamld** [comment]
a-scene
          gltf-model="meshoptDecoderPath: https://unpkg.com/meshoptimizer@0.19.0/meshopt_decoder.js"

What happens if this parameter is accepted?
This should be a switch instead of accepting a remote connection

**Comment by dmarcos** [comment]
You can read the docs:

https://aframe.io/docs/1.3.0/components/renderer.html#sidebar

https://aframe.io/docs/1.3.0/components/gltf-model.html#scene-properties

Not sure I understand the question. FYI, we use github issues for bug reports and feature requests. 

For usage questions we recommend [StackOverflow](https://stackoverflow.com/questions/tagged/aframe) and [Discord](https://discord.gg/zbZk6TyM). Very nice people there to help and answer questions. You'll get much more visibility.

I'm closing this because there's nothing actionable on A-Frame code. Thanks for understanding and best of luck
