### ISSUE TITLE
AFRAME is not working on iOS since switch to THREE 0.152

### ISSUE THREAD

**Issue by Dirk-27** [aframevr/aframe#5306]
**Description:**

- A-Frame Version: master
- Platform / Device: iOS
- Reproducible Code Snippet or URL:
    - example: https://worried-remarkable-modem.glitch.me
    - code: https://glitch.com/edit/#!/worried-remarkable-modem

We updated our examples to the the master version of aframe because we need the getBoundingBox-Feature for instanced meshes which is part of three.js since 0.151.

Than the examples didn't work on iOS devices. We see no rendering in the canvas - it stays white. There is no error in the log. We also tried to update super-three to the master version with no better result.

**Comment by vincentfretin** [comment]
Yes, see https://github.com/aframevr/aframe/issues/5292#issuecomment-1586393270

**Comment by mrxz** [comment]
You're probably facing #5292, though there really should be an error logged.

> We also tried to update super-three to the master version with no better result.

The development head of super-three is the `dev` branch, not `master`. Also note that since A-Frame includes (super-)three  in its bundle you can only update it by bundling it with a different version. Things like package overrides or including a separate copy won't do the trick.

**Comment by Dirk-27** [comment]
Yes, this is the solution. I added the function to the WebVRManager.getEnvironmentBlendMode() function and save a patched min.js file as aframe-v1.4.2_ad40be-p1.min.js

No it works! Thanks to @mrxz and @vincentfretin !

See: https://worried-remarkable-modem.glitch.me

**Comment by Dirk-27** [comment]
Closed as duplicate of #5292
