### ISSUE TITLE
the images in the plans do not work on iphone 13 and 14 appear black

### ISSUE THREAD

**Issue by Alan4745** [aframevr/aframe#5344]
**Description:**
It is that the images used do not work on iPhone but on other platforms. 
![image](https://github.com/aframevr/aframe/assets/115485379/679e4b59-b9d4-455f-8876-11b979b50970)

- A-Frame Version: 1.0.4
- Platform / Device: iphone 14 a
- Reproducible Code Snippet or URL: https://ceramxvr.com/ dominia , code https://github.com/Alan4745/ceramxvr

**Comment by dmarcos** [comment]
Make sure you are in A-Frame latest version (1.4.2). If it doesn't work can try master builds: [links in commit messages](https://github.com/aframevr/aframe/commits/master)

If you still have issues I would check console for error messages and I recommend creating a simple example that reproduces the issue since people won't have the bandwidth to debug the whole application. https://glitch.com/~aframe is great. Best of luck

**Comment by Alan4745** [comment]
hello everyone, maybe someone else can help you, I could already see what the error was, it is that the images are resized badly, they are in a pixel format, for example, 200 x 258 and that is generally complicated with iPhones, it is better to use the formats that mentions us in colossa aframe.js 
![image](https://github.com/aframevr/aframe/assets/115485379/bfa7b2fd-bc57-42a2-b164-c3e4b211a30b)

Now with the images resized correctly they were already shown on the devices
Well I hope this comment helps more than someone :)
