### ISSUE TITLE
Error cors

### ISSUE THREAD

**Issue by ilsanto17** [aframevr/aframe#5355]
Hi everyone, I'm developing an app with ionic using aframe. When I try to call a URL with an image I get a cors error. How can I solve this problem?
` <a-scene>
    <a-assets>
      
  
      
      <img id="city" [src]=panorama crossorigin="anonymous">
      
    </a-assets>
  
    
    <a-sky id="image-360" radius="10" [src]="'#city'" crossorigin="anonymous"></a-sky>
  
   
    
    <a-camera>
      <a-cursor
        id="cursor"
        animation__click="property: scale; from: 0.1 0.1 0.1; to: 1 1 1; easing: easeInCubic; dur: 150; startEvents: click"
        animation__clickreset="property: scale; to: 0.1 0.1 0.1; dur: 1; startEvents: animationcomplete__click"
        animation__fusing="property: scale; from: 1 1 1; to: 0.1 0.1 0.1; easing: easeInCubic; dur: 150; startEvents: fusing"></a-cursor>
    </a-camera>
     
     <a-image
     position="2 2 -5" 
     src="../assets/icon/favicon.png"
     width="0.5" 
     height="0.5"  
     clickable="true" 
     animation__click="property: scale; from: 1 1 1; to: 1.2 1.2 1.2; easing: easeInCubic; dur: 150; startEvents: click" ></a-image>
     
  
  </a-scene>`

**Comment by dmarcos** [comment]
That's browser policy not A-Frame limitation. Need to serve image from own domain or one that has CORS headers enabled. Covered in FAQ

https://aframe.io/docs/1.4.0/introduction/faq.html#why-does-my-asset-e-g-image-video-model-not-load

Best of luck!. Closing because there's no work to do on A-Frame side. For usage questions I recommend joining the community on [discord](https://discord.gg/qeThe9zn) or [Stack Overflow](https://stackoverflow.com/questions/tagged/aframe)
