### ISSUE TITLE
Missing a way to set the start time of sound components

### ISSUE THREAD

**Issue by JonathannJacobs** [aframevr/aframe#5364]
Hi, well first thing, it's not a bug but a missing feature.

I wish to have a way to play a sound entirely at first loop and then rewind at some specific start loop value different than zero.
So far i had the following code : 

this.el.removeAttribute('sound')
this.el.setAttribute('sound', 'src', 'assets/some.mp3');
this.el.components.sound.playSound()
this.el.addEventListener('sound-ended', () => {
  // Missing here a way to set the next playSound start value
  this.el.components.sound.playSound()
});

And that is sad because i could totally do it with a regular audio html element that lacks positionnal audio and pool.

Currently my best shot is to split my file into two mp3: one for the intro and another for the looping part.

- A-Frame Version: 1.4.2
- Platform / Device: All

**Comment by mrxz** [comment]
It would be nice for the built-in sound component to expose a `loopStart` and `loopEnd`, but currently it doesn't. Luckily you can quite easily reach into the sound component and get to the `THREE.Audio` instance or even further to the underlying WebAudio Nodes.

For example:
```js
const soundComponent = this.el.components['sound'];
const audio = soundComponent.pool.children[0]; // THREE.Audio
audio.setLoopStart(/* start time in seconds */);
audio.setLoopEnd(audio.buffer.duration)
```

It can be a bit tricky when to execute this, as it needs to take place _after_ the sound component has initialized (and the sound loaded, for the duration), but before playing the audio (otherwise the `loopStart` and `loopEnd` of THREE.Audio don't apply). Should be good to handle it in `sound-loaded`:  `this.el.addEventListener('sound-loaded', e => {})`

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/5365
