### ISSUE TITLE
locomotion in the VR scene (feature request)

### ISSUE THREAD

**Issue by addy1997** [aframevr/aframe#5392]
Moving in different directions in the VR scene by pinching in particular directions.

- A-Frame Version: 1.5
- Platform / Device: Meta Quest 3
- Reproducible Code Snippet or URL: NA

Although [aframe-hand-tracking-control-extras](https://github.com/gftruj/aframe-hand-tracking-controls-extras) component serves the purpose, it's quite unstable in that object manipulation becomes challenging when used. It also throws a lot of script-related errors.

There is a component [pinch-to-move](https://github.com/mozilla/hubs/blob/master/src/components/pinch-to-move.js)  from **Mozilla hubs** which I think can be used for locomotion but I am not sure. I'll be more than happy to write a component but need some guidance.

Please can anybody provide a solution or guide?

**Comment by dmarcos** [comment]
This functionality is more suitable for a 3rd party / community component. For guidance and questions I recommend joining the community on the #aframe channels in the [WebXR](https://discord.gg/NXTkdRuT) or [Supermedium](https://discord.gg/fFfmB8t2) Discords.

Closing this since we use Github for bug reports and feature requests. Best of luck
