### ISSUE TITLE
Texture bug after modifying an a-sky src

### ISSUE THREAD

**Issue by unlimi-ted** [aframevr/aframe#5557]
**Description:**
Sometimes a change of the a-sky src property is not properly done: the new image is not replacing the former one, but you can see multiple images on different part of the sky. Using the A-frame Inspector, if I duplicate the a-sky entity the new one is correct.

This bug was appearing with A-frame 1.6.0, I can reproduce it with one image coming from StreetView (event in full size, resized or compressed) but I don't know how this bug it really related to this image. Using A-frame 1.5 everything is fine.

- A-Frame Version: 1.6.0
- Platform / Device: Firefox 128.0 Linux, Chrome 126.0.6478.126, Debian12
- Reproducible Code Snippet or URL: https://360reports.skilltech.tools/ https://360reports.skilltech.tools/archive.zip

**Comment by vincentfretin** [comment]
Do you reproduce with a master build? There were some fixes on master around textures disposal like #5529

**Comment by unlimi-ted** [comment]
I cannot reproduce the bug with a master build, so it seems that the bug is already fixed in master

**Comment by vincentfretin** [comment]
Ok great, then you can close the issue.

**Comment by PierreAtUptale** [comment]
Jumping in just to report that this occurs also to `a-image` tags on version 1.6 of aframe, with the following WebGL warning appearing in the console, in case other users are looking for the cause of a similar problem:

```
A [.WebGL-0x316415630000] GL_INVALID_OPERATION: glTexStorage2D: Texture is immutable.
```

A workaround for projects that for one reason or another cannot upgrade to `aframe >1.7.0`, like us, can be to first clear the `src` of the `a-entity` before setting the new value.

I'm also linking this PR to the following related ones to ease discoverability, as it's otherwise not obvious from the release notes of version `1.7.0` that this has been fixed by it:
#5593 #5529

**Comment by mrxz** [comment]
> A workaround for projects that for one reason or another cannot upgrade to `aframe >1.7.0`, like us, can be to first clear the `src` of the `a-entity` before setting the new value.

@PierreAtUptale Clearing the `src` before setting a new value should indeed work around the issue, as the texture gets disposed immediately that way. Since you mention being unable to upgrade to A-Frame 1.7.0, do not hesitate to open issue(s) in case there's something on the A-Frame side preventing you from upgrading.
