### ISSUE TITLE
Camera animation is not working in v1.6.0

### ISSUE THREAD

**Issue by AliSeyfollahi** [aframevr/aframe#5558]
### Issue Description

**A-Frame Version:** 1.6.0

In the new version of A-Frame (1.6.0), there is a bug related to camera animations that did not exist in version 1.5.0. Specifically, when attempting to move the camera using an animation, the camera moves instantly without the expected animation effect.

#### Steps to Reproduce

1. Open the provided sandbox for A-Frame v1.5.0: [CodePen Example for 1.5.0](https://codepen.io/aliseyfollahi/pen/dyBYrJy)
   - The camera moves smoothly with the specified animation.

2. Open the provided sandbox for A-Frame v1.6.0: [CodePen Example for 1.6.0](https://codepen.io/aliseyfollahi/pen/poXjYdL)
   - The camera moves instantly without any animation.

#### Expected Behavior

The camera should move smoothly from one position to another using the defined animation parameters.

#### Actual Behavior

In A-Frame v1.6.0, the camera jumps instantly to the target position without the smooth animation effect.

#### Additional Context

This issue seems to be a regression introduced in the latest version of A-Frame. Any help in resolving this would be greatly appreciated, as smooth camera animations are crucial for user experience in many applications.

Thank you for your attention to this matter.

**Comment by mrxz** [comment]
The problem is that you have two components (`animation` and `look-controls`) setting the rotation of the camera each tick. In 1.5.0 the order of these depended on the order the behaviours are added to the scene, and since you add the animation upon click, it gets executed last. Since 1.6.0 the order of component updates is fixed, and `animation` is executed before `look-controls`.

In general it's advised to perform manual positioning/rotating through a camera rig. Though, in your case it seems the intention is only to animate a transition, so you could perhaps look into disabling the `look-controls` component for the duration of the animation. That should also fix the bug where the user drags _while_ the animation is playing.

Alternatively you could create your own component based on `look-controls` that handles the animation or otherwise ensures it doesn't conflict with any running animation.
