### ISSUE TITLE
Status of generative scene modeling

### ISSUE THREAD

**Issue by wetoo-cando** [aframevr/aframe#5575]
I remember seeing a video demo of generative scene modeling as part of the GitHub accelerator application of a-frame.

Where can I find updates on this initiative?

**Comment by dmarcos** [comment]
We have a text to 3D model API at the moment. Details here https://supermedium.com/ Let us know what you think!

Working on more stuff but not public yet.

I'm closing this because we use Github issues for bug reports and feature requests. For other matters I recommend [Discord](https://discord.gg/uhBVX6GDSf)
