### ISSUE TITLE
error switching to AR mode on Galaxy Tab A9+

### ISSUE THREAD

**Issue by polytropoi** [aframevr/aframe#5610]
**Description:**
console shows this error on all scenes tested (including https://aframe.io/aframe/examples/boilerplate/ar-hello-world/) when switching to AR mode:

src-loader.js:23 Uncaught TypeError: n is not a function
    at src-loader.js:23:5
    at XMLHttpRequest.<anonymous> (src-loader.js:146:11)

I don't have another suitable android device to test with, and it may not impact functionality, but it is scary...

- A-Frame Version: 1.6.0
- Platform / Device: Galaxy Tab A9+
- Reproducible Code Snippet or URL: https://aframe.io/aframe/examples/boilerplate/ar-hello-world

**Comment by mrxz** [comment]
Was able to reproduce the issue. This has to do with the `light-estimation` component and light probes. Instead of using images as source for the light probe, the `light-estimation` component sets the light probe values directly. However, the code incorrectly still tried to load a cube map, resulting in this error.

It should not have any impact on functionality as the cube map that failed to load simply goes unused. I've created a PR that fixes this bug: #5611
