### ISSUE TITLE
Investigate slow raycasting

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#829]
From @brianchirls on [WebVR Slack](https://webvr.slack.com/messages/help-and-bugs/):

> __brianchirls [5:53 AM]__
> @joshcarpenter et al: I ran a quick CPU profile of a-frame, and it looks like raycasting is the slowest thing. I’ll be working on my own optimized solution for that today and will let you know what I find out. But…a good way to speed it up is to turn off raycasting for photo spheres, since they’ll ​*always*​ show up wherever you look. Or even exclude any objects that don’t have an event listener or something on them.

**Comment by brianchirls** [comment]
The big problem here is that raycasting as implemented in three.js is unavoidably slow. By default, it loops through every single object in your list, and then through every single face on any object that matches both the bounding sphere and the bounding box. Even if you use an [octree](http://threejs.org/examples/webgl_octree_raycasting.html), it still runs at O(n) through every single face...unless you have a `BufferGeometry`, in which case it does nothing or breaks, since it's just not supported in the provided octree raycasting code.

To make performance matters worse, however you do it, the search is undirected so it has to find every single object that intersects your ray and then sort them by distance to find the first hit. It has no way of ignoring potential objects that are farther away than your best solution so far.

One alternative is to try [GPU picking](http://brianxu.github.io/GPUPicker/), which is MUCH faster. But it has a couple of problems:
1. It gets pretty complicated if you want to get anything other than the id of the object you've selected. If you want the position and normal of the point of intersection, that's more information than you can squeeze through a single 4-byte pixel.
2. It requires a `readPixels` call, which causes GPU/CPU sync, potentially a pretty large delay, enough to cause serious jank.

I'm considering a more optimized CPU-side approach, which is to use octrees at two levels: one for bounding spheres and boxes of objects, and then one for each geometry instance. For each object that matches, the ray would be transformed into the local object space, and then the search would proceed at O(log n) through the triangle faces of that object. The search would run depth-first, prioritizing octree nodes that are closest to the origin of the ray (and within the max distance, of course). In theory, this should allow you to stop early - not after the very first match, but a hell of a lot less than every single node, object and triangle. The object-level octree would have to be updated every time an object moves, but 

I have some concerns/questions about this approach:
1. Will the geometry octree take up too much memory?
2. Will it take too long to generate the geometry octree the first time?
3. Maybe there's some way to represent it compactly in a typed array or two, so it can be generated in a worker and transferred over, addressing both of the above?
4. Are there any other uses for such a data structure, as long as we're going to the trouble?
5. What about morphing/animated geometries?

Does anyone have a better idea?

**Comment by brianchirls** [comment]
Incidentally, there is already an [issue](https://github.com/mrdoob/three.js/issues/5691) for this at the three.js repo, but it has not had much attention.

**Comment by dmarcos** [comment]
Thanks for analysis and raising the performance issue. In the issue you posted there's a link to an octree based raycaster implementation. I think this should be fixed on the three.js side. @brianchirls Do you think there's something on the aframe side we should do?

**Comment by brianchirls** [comment]
@dmarcos Yes, I do think that aframe needs to raycast fewer things, as [noted above](https://github.com/aframevr/aframe/issues/829#issue-126553429): in particular, photo spheres. Until this gets fixed in three.js (if ever), a photo or video sphere will match every single time and require searching through every single triangle on every frame.

Also, I agree that this should be addressed over in three.js, but the existing implementation is mostly useless (not to mention undocumented and hard to find) and the discussion over there seems to have been lost in the pile. I figured we could discuss it over here since this community seems a bit more focused. If I could get some feedback on the idea, I can make an attempt to fix it and make a pull request over there, or even publish it as a separate repo.

**Comment by jerbob92** [comment]
Could it be that hidden objects are also included in the raycasts?
I tried to create a multi-scene environment in A-Frame by hiding/showing objects, every added object seemed to slow it down more, even when the object is hidden. I know, this approach isn't ideal, but it appeared to be the best way to have multiple "rooms" currently. 

I also had strange behaviour when a hidden object was on top of a shown object, when the shown object was being clicked, nothing happened, but the hidden object did seem to pick up clicks.

**Comment by jerbob92** [comment]
The unclickable items because of overlaying hidden objects is fixed in the latest dev.
I tried to speed up raycasting a bit locally, see:

https://github.com/jerbob92/aframe/commit/d8c208cec71d534e7bb2e1d9bb8b942e3a40cd15

Not sure if it's the right approach but it seems to be smoother on my HTC One M9.

**Comment by brianchirls** [comment]
@jerbob92 Looks like a big step in the right direction.

BTW, are you guys building geometry for a single-color background "sky"? Might it not be much more efficient to just set the clear color?

**Comment by ngokevin** [comment]
The easiest thing I plan on doing is adding options to the raycaster component to whitelist (and possibly ignore) targets. Then reflect that in the cursor component.

Clear color rather than single-color skyspheres would also be a good enhancement.
