### ISSUE TITLE
Text takes too long to load on examples site

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#896]
When our webfont loads, all the text disappears and flashes in.

**Comment by dmarcos** [comment]
Is not the chache working for the font?

**Comment by ngokevin** [comment]
@cvan forced it to defer with some JS since his site was down for a bit. I think we can just put it back in `<head>` if we moved the webfont to a proper CDN.

**Comment by cvan** [comment]
> @cvan forced it to defer with some JS since his site was down for a bit. I think we can just put it back in `<head>` if we moved the webfont to a proper CDN.

yeah, I'm making it such that [we don't block the loading of the page on the web font](https://github.com/aframevr/aframe/blob/e816115/examples/index.html#L198). the reason is because the Mozilla Fira CDN has proved unreliable in the past (it would time out a ton for no apparent reason); it times out regularly and CORS headers are not set (see mozilla/Fira#72).

I'd rather we just include the URLs to the fonts on https://aframe.io/'s CDN (https://aframe.io/fonts/fira/ttf/FiraSans-Hair.ttf, etc.) - or include Fira again in this repo. The former is preferable. But, again, if you shove any external webfont to the `<head>`, and the web font can't be reached (e.g., if you're offline, https://aframe.io/ has issues, etc.), the Examples page will block on that request and it'll suck. :-1:

**Comment by ngokevin** [comment]
fixed
