### ISSUE TITLE
WASD controls should not be engaged w/ shift/control/alt/meta keys

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#932]
(Similar but different from #927.)

STR:

1. Load https://aframe.io/aframe/examples/showcase-spheres-and-fog/
2. Hold down the `Command` + `A` keys
3. Release the keys
4. Notice you keep moving left

For WASD controls, we should abort if `shiftKey`, `ctrlKey`, `altKey`, or `metaKey` are also being held.

**Comment by donmccurdy** [comment]
This may only affect `metaKey` – see issue #3 here: http://bitspushedaround.com/on-a-few-things-you-may-not-know-about-the-hellish-command-key-and-javascript-events/

**Comment by cvan** [comment]
I think it affects all except perhaps `shiftKey`

**Comment by donmccurdy** [comment]
Ah, that's an issue too, but different cause: shift key changes `KeyboardEvent::key` case, so it might be "a" on keydown and "A" on keyup, which similarly breaks everything. I'm running a fork of `wasd-controls` [here](https://github.com/donmccurdy/aframe-keyboard-controls), and am leaning towards using `KeyboardEvent::code` rather than `key`, since (1) it's case-insensitive, and (2) it has nice default behavior w/ Spacebar.
