### ISSUE TITLE
Consider adding scenes into `examples` as test cases

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#947]
It'd be nice if we had folks' scenes checked into the repo. We could then easily test scenes with new code to know that we aren't regressing folks' scenes.

Some to choose from:

http://drawvr.com/
http://drawvr.com/tron/
http://drawvr.com/theater/
http://drawvr.com/minecraft/
http://infiverse.com/
https://www.ideaspacevr.org/examples/aframe/aframe-360-degree-photosphere/
http://x627.com/testscape/
https://hellocreep.github.io/webvr/
http://stampswebdesign.com/withersc/hud/
https://htmlpreview.github.io/?https://github.com/davexoxide/sweet-lights/blob/master/index.html

**Comment by ngokevin** [comment]
Don't think we need to maintain community scenes within the core repo. Scenes are versioned on an A-Frame so there's no issue of hot-regressing. This idea could potentially catch issues, but there's work in migrating each scene over API breaking patches. I think since we have the bleeding edge master releases, people try out new builds and catch issues often.
