### ISSUE TITLE
Revisiting setAttribute/attributeChangedCallback behavior

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#960]
We're hitting some issues with multiple calls to `setEntityAttribute` on a single call to `setAttribute`. There are two separate problems:
1. Firefox uses the register-element polyfill. Our wrapped getAttribute is used to retrieve the old attribute value to check if oldValue === newValue. The check fails because we end up comparing objects instead of strings and `attributeChangedCallback` is always called. The native implementation in Chrome doesn't have this problem. A PR into the [register-element polyfill](https://github.com/WebReflection/document-register-element) to invoke `HTMLElement.getAttribute` instead of our wrapped `getAttribute` might be the clean solution. There's no downside for them and it will make the polyfill more robust.
2. `attributeChangedCallback` behaves synchronously and when a component data changes we call `setEntityAttribute` twice. First in the `attributeChangedCallback` and later in our `setAttribute` wrapper. We need to find a way to avoid redundant calls.

@ngokevin thoughs?

**Comment by ngokevin** [comment]
1. I was also running into that issue. When doing `setAttribute`, it would do `getAttribute` to figure out what changed. For the obj-model component, that was returning a parsed/deserialized object. Since the obj-model uses the `src` type, it breaks because the `src` type does not produce the same value when called twice in a row. So a PR should fix that.

2. We could remove the `setEntityAttribute` from the `setAttribute` since `attributeChangedCallback` is called anways, but in the case we do like `setAttribute('material', 'color', 'red')`, we need to call `setEntityAttribute` with some processed data. So, yeah we need to refactor somehow.

By the way, how do I go confirm that `attributeChangedCallback` is in fact getting called synchronously? Using `setTimeout`?

**Comment by dmarcos** [comment]
I use the debugger. If attributeChangedCallback is called before the line below then it means is synchronous:

https://github.com/aframevr/aframe/blob/dev/src/core/a-entity.js#L479

**Comment by cvan** [comment]
Have y'all thought about switching to the webcomponents.js custom elements polyfill? (filed as #567.) perhaps just try it first.

**Comment by ngokevin** [comment]
`setEntityAttribute` now no longer called in `setAttribute`
