### ISSUE TITLE
look-at with a vec3 target doesn't work

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#965]

**Comment by nylki** [comment]
The rotation matrix of the object3D gets reset between `update` and first `tick`.
If you add the `lookat` in the `tick` function but only execute it on the first tick (tested with a simple counter), the element does actually `look-at` the element.


I added some log prints to see if the rotation gets reset.
```.js
   tick: function (t) {
    this.tickCount++;
    // Track target object position. Depends on parent object keeping global transforms up
    // to state with updateMatrixWorld(). In practice, this is handled by the renderer.
    var target3D = this.target3D;
    if (target3D) {
      return this.el.object3D.lookAt(this.vector.setFromMatrixPosition(target3D.matrixWorld));
    } else if (this.tickCount === 1) {
      console.log('rotation in first tick', this.el.object3D.rotation);
      this.el.object3D.lookAt(new THREE.Vector3(this.data.x, this.data.y, this.data.z));
      console.log('rotation after setting it again to lookat vector:', this.el.object3D.rotation);
    }
  }
```

![lookat_2](https://cloud.githubusercontent.com/assets/1710598/13368420/6c2e7780-dcea-11e5-9fef-d6899aeb9b9a.png)

**Comment by ngokevin** [comment]
Ah, the rotation component must be overriding it?

**Comment by nylki** [comment]
@ngokevin To test it, I set rotation, position, scale and visibility all as dependency. It helps but actually only postpones a reset to `0 0 0`,  it must come from somewhere else. Investigating further.

**Comment by andreasplesch** [comment]
To avoid overriding issues, it may work to calculate the proper rotation in the look-at component (rather than use .lookAt() ) and then setAttribute on the rotation component, and let it do the updating of the Object3D rotation ?
Three.js calculates the rotation here:
https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L262

**Comment by andreasplesch** [comment]
Using look-at to a vec3 on a wrapper around the camera component does not seem to work. In the codepen below, moving the camera with keyboard should keep the camera on the red sphere but it does not.
In addition, when using a selector instead of vec3 the scene does not get drawn at all. Preliminary debugging (in codepen ...) suggests that tick() may never be called in this case.

http://codepen.io/anon/pen/LNgLWx

**Comment by ngokevin** [comment]
moved to https://github.com/ngokevin/aframe-look-at-component/issues/2
