### ISSUE TITLE
Beef up `CONTRIBUTING.md` to include helpful commands for dev env, GitHub/PR workflows, how to contribute

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#971]
à la https://github.com/servo/servo/blob/master/HACKING_QUICKSTART.md

Perhaps move/duplicate a bunch of the commands from the [`README.md`](https://github.com/aframevr/aframe/blob/dev/README.md) and throw them here. The [A-Frame Docs](https://aframe.io/docs/) are specific to _usage_ of A-Frame as a library, not about contributing to the A-Frame codebase itself.

**Comment by ngokevin** [comment]
consider consolidating into CONTRIBUTING to avoid plethora of `.md` files

**Comment by ngokevin** [comment]
@joshgalvin: "most windows node devs don't have the node-gyp compiler tool chain installed"

need to note that

**Comment by nylki** [comment]
I had issues with the testing envorinment (via `npm test`). `npm install` itself didn't seem to install all the necessary dendencies for karma, which complained about missing *lolex*. I had to manually do `npm install chai lolex sinon sinon-chai` to succesfully use `npm test`. Not sure if this problem was just on my side or if those were missing in package.json.
In the first case, could be useful to add to the .md for devs that encounter this issue.

I am on Fedora 23, npm 3.6.0, node 5.6.0

**Comment by ngokevin** [comment]
some updates https://github.com/aframevr/aframe/commit/35de321a704578cb284667c630a6cc7c2673370d

could go into more detail like writing tests or style guide

**Comment by cvan** [comment]
I was going to file a separate issue, but it's probably fine to add as a comment here. We need to document how to enable the debug-level console logs.

I had this information in the README, but [it was removed](https://github.com/aframevr/aframe/commit/4171d021#diff-04c6e90faac2675aa89e2176d2eec7d8L52).

I couldn't find this info. anywhere in the docs, only [in the code as comment](https://github.com/aframevr/aframe/blob/701e47e/src/utils/debug.js#L73-L82).

Let's add it probably to both the docs and the `CONTRIBUTING.md`.

```js
localStorage.logs = 1
```

**Comment by ngokevin** [comment]
FWIW, we only have one debug-level log in the whole codebase, and I've never used it.

**Comment by ngokevin** [comment]
Things I would add:

**Contributing Code:**

- [ ] Mention of style guide (`semistandard`) and to use `npm run lint` to check.
- [ ] Add a note on how to rebase
- [ ] Add a note on testing and link to tests/README.md

- [ ] **Spreading the Word** (maybe)
  - [ ] Links to good slidedecks for A-Frame/WebVR evanglism until we have an official onboard kit
  - [ ] Where to give talks (e.g., meetups, contact Mozilla reps)

In tests/README.md, I would add more details on how to use the test suite. (explain the tool chain of karma/mocha/sinon, the process of adding a test).

**Comment by mkungla** [comment]
Add a note on how to rebase is good idea, but also other git stuff for PR life cycle  
Since you most likely first clone you fork then that is your `origin` remote
1. **first you add upstream remote**
`git remote add upstream git@github.com:aframevr/aframe.git`
2. If you want to make contibution you would create new branch shortly describing what you working on or just name it `patch-x`
`git fetch --all`  *to update trackers*
`git checkout -b patch-x upstream/master` *checkout new branch from upstream master*
`git push -u origin HEAD` *push and create new branch under your github*
3. Do some work, commit it, push and PR
4. If you branch fells behind or needs rebase run
`git fetch --all` * to update trackers*
`git rebase upstream/master` to rebase and play your commits on top
`git push -f` to fast forward your `patch-x` branch on github
5. After PR is merged you can just delete this branch by running
`git branch -D patch-x`
`git push origin :patch-x`

**Comment by darkwing** [comment]
I have a post about squashing commits if you think it would be a useful reference:  https://davidwalsh.name/squash-commits-git

**Comment by ngokevin** [comment]
Yeah, thanks. I saw that is already linked in the CONTRIBUTING guide. Just wanted to address rebasing because sometimes people's branches get all messed up and they have to open a new PR.

**Comment by darkwing** [comment]
Oh sweet, I didn't know that :)
